# -*- coding: utf-8 -*-
"""Adds COST challenges 1-30 to CHALLENGE_SCENARIOS."""

COST_BLOCK = r"""const COST_CHALLENGES: Record<number, ChalScenario> = {
  1: {
    id: 'COST-01', title: 'COST-01 AWS Budgets 알람 설정',
    scenario: '월말마다 AWS 청구서를 받고 나서야 비용 초과를 알게 됩니다. AWS Budgets로 월 $500 예산을 설정하고 80% 도달 시 이메일 알람을 받으세요.',
    steps: [
      { title: '현재 월 비용 확인', desc: 'Cost Explorer로 이번 달 현재까지 발생한 비용을 확인하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --query "ResultsByTime[0].Total.BlendedCost"',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --query "resultsbytime[0].total.blendedcost"'],
        successOutput: ['{"Amount": "347.82", "Unit": "USD"}'] },
      { title: '월 예산 생성', desc: '월 $500 비용 예산을 생성하세요.',
        hint: 'aws budgets create-budget --account-id 123456789012 --budget BudgetName=monthly-500,BudgetLimit={Amount=500,Unit=USD},TimeUnit=MONTHLY,BudgetType=COST',
        answers: ['aws budgets create-budget --account-id 123456789012 --budget budgetname=monthly-500,budgetlimit={amount=500,unit=usd},timeunit=monthly,budgettype=cost'],
        successOutput: [''] },
      { title: '80% 알람 설정', desc: '예산의 80%($400) 도달 시 이메일 알람을 추가하세요.',
        hint: 'aws budgets create-notification --account-id 123456789012 --budget-name monthly-500 --notification NotificationType=ACTUAL,ComparisonOperator=GREATER_THAN,Threshold=80,ThresholdType=PERCENTAGE --subscribers SubscriptionType=EMAIL,Address=admin@company.com',
        answers: ['aws budgets create-notification --account-id 123456789012 --budget-name monthly-500 --notification notificationtype=actual,comparisonoperator=greater_than,threshold=80,thresholdtype=percentage --subscribers subscriptiontype=email,address=admin@company.com'],
        successOutput: [''] },
      { title: '예산 조회', desc: '생성된 예산과 현재 사용량을 확인하세요.',
        hint: 'aws budgets describe-budget --account-id 123456789012 --budget-name monthly-500 --query "Budget.{Limit:BudgetLimit,ActualSpend:CalculatedSpend.ActualSpend}"',
        answers: ['aws budgets describe-budget --account-id 123456789012 --budget-name monthly-500 --query "budget.{limit:budgetlimit,actualspend:calculatedspend.actualspend}"'],
        successOutput: ['{"Limit": {"Amount": "500.0", "Unit": "USD"}, "ActualSpend": {"Amount": "347.82", "Unit": "USD"}}'] },
    ],
    explanation: 'AWS Budgets는 비용, 사용량, 예약 인스턴스, Savings Plans 예산을 설정할 수 있습니다. 실제 비용 외에 예측 비용 기준으로도 알람을 설정할 수 있습니다. SNS 토픽으로 연결하면 Slack 등 다양한 채널로 알림을 보낼 수 있습니다.',
  },
  2: {
    id: 'COST-02', title: 'COST-02 EC2 Savings Plans 구매',
    scenario: '운영 EC2 인스턴스가 항상 켜져 있는데 On-Demand 요금을 내고 있습니다. 1년 Compute Savings Plans를 구매해 최대 66% 비용을 절감하세요.',
    steps: [
      { title: 'Savings Plans 권고 확인', desc: 'Cost Explorer에서 Savings Plans 구매 권고를 확인하세요.',
        hint: 'aws ce get-savings-plans-purchase-recommendation --savings-plans-type COMPUTE_SP --term-in-years ONE_YEAR --payment-option NO_UPFRONT --lookback-period-in-days THIRTY_DAYS',
        answers: ['aws ce get-savings-plans-purchase-recommendation --savings-plans-type compute_sp --term-in-years one_year --payment-option no_upfront --lookback-period-in-days thirty_days'],
        successOutput: ['{"Recommendations": [{"SavingsPlansDetails": {"HourlyCommitmentToDeploy": "0.50", "EstimatedSavingsAmount": "876.00", "EstimatedSavingsPercentage": "36.5"}}]}'] },
      { title: '현재 On-Demand 사용량 확인', desc: 'EC2 On-Demand 비용을 서비스별로 조회하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --group-by Type=DIMENSION,Key=INSTANCE_TYPE --filter file://ec2-filter.json',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --group-by type=dimension,key=instance_type --filter file://ec2-filter.json'],
        successOutput: ['{"ResultsByTime": [{"Groups": [{"Keys": ["t3.medium"], "Metrics": {"BlendedCost": {"Amount": "62.42"}}}, {"Keys": ["c5.xlarge"], "Metrics": {"BlendedCost": {"Amount": "124.85"}}}]}]}'] },
      { title: 'Savings Plans 구매', desc: '시간당 $0.50 Compute Savings Plans를 구매하세요.',
        hint: 'aws savingsplans create-savings-plan --savings-plan-offering-id offering-abc123 --commitment 0.50 --purchase-time 2024-01-01T00:00:00Z',
        answers: ['aws savingsplans create-savings-plan --savings-plan-offering-id offering-abc123 --commitment 0.50 --purchase-time 2024-01-01t00:00:00z'],
        successOutput: ['{"savingsPlanId": "sp-abc123def456", "status": "active"}'] },
      { title: 'Savings Plans 적용 현황 확인', desc: '구매한 Savings Plans의 활용률을 확인하세요.',
        hint: 'aws ce get-savings-plans-utilization --time-period Start=2024-01-01,End=2024-01-31 --query "Total.{Utilization:Utilization.UtilizationPercentage,NetSavings:Savings.NetSavings}"',
        answers: ['aws ce get-savings-plans-utilization --time-period start=2024-01-01,end=2024-01-31 --query "total.{utilization:utilization.utilizationpercentage,netsavings:savings.netsavings}"'],
        successOutput: ['{"Utilization": "94.5", "NetSavings": "68.42"}'] },
    ],
    explanation: 'Compute Savings Plans는 EC2, Lambda, Fargate에 적용되는 가장 유연한 플랜입니다. 1년 No Upfront 기준 최대 66% 절감됩니다. 활용률이 낮으면 구매 금액이 낭비되므로 권고 금액의 80-90%로 시작해 점차 늘리는 전략이 좋습니다.',
  },
  3: {
    id: 'COST-03', title: 'COST-03 EC2 Spot 인스턴스 활용',
    scenario: '배치 분석 워크로드가 하루 2시간 실행됩니다. On-Demand c5.2xlarge 대신 Spot 인스턴스로 교체하면 최대 90% 절감됩니다. Spot Fleet으로 중단에도 안전하게 배치를 실행하세요.',
    steps: [
      { title: '현재 Spot 가격 확인', desc: 'c5.2xlarge의 현재 Spot 가격을 확인하세요.',
        hint: 'aws ec2 describe-spot-price-history --instance-types c5.2xlarge --product-descriptions Linux/UNIX --start-time 2024-01-01T00:00:00Z --query "SpotPriceHistory[0:3].{AZ:AvailabilityZone,Price:SpotPrice}"',
        answers: ['aws ec2 describe-spot-price-history --instance-types c5.2xlarge --product-descriptions linux/unix --start-time 2024-01-01t00:00:00z --query "spotpricehistory[0:3].{az:availabilityzone,price:spotprice}"'],
        successOutput: ['[{"AZ": "us-east-1a", "Price": "0.0912"}, {"AZ": "us-east-1b", "Price": "0.0887"}, {"AZ": "us-east-1c", "Price": "0.0943"}]'] },
      { title: 'Spot Fleet 요청 생성', desc: '목표 용량 4 vCPU로 Spot Fleet을 요청하세요.',
        hint: 'aws ec2 request-spot-fleet --spot-fleet-request-config file://spot-fleet-config.json',
        answers: ['aws ec2 request-spot-fleet --spot-fleet-request-config file://spot-fleet-config.json'],
        successOutput: ['{"SpotFleetRequestId": "sfr-abc123def-4567-890a-bcde-f01234567890"}'] },
      { title: 'Spot Fleet 상태 확인', desc: 'Spot Fleet이 인스턴스를 확보했는지 확인하세요.',
        hint: 'aws ec2 describe-spot-fleet-requests --spot-fleet-request-ids sfr-abc123def-4567-890a-bcde-f01234567890 --query "SpotFleetRequestConfigs[0].{State:SpotFleetRequestState,Fulfilled:FulfilledCapacity}"',
        answers: ['aws ec2 describe-spot-fleet-requests --spot-fleet-request-ids sfr-abc123def-4567-890a-bcde-f01234567890 --query "spotfleetrequestconfigs[0].{state:spotfleetrequeststate,fulfilled:fulfilledcapacity}"'],
        successOutput: ['{"State": "active", "Fulfilled": 4.0}'] },
      { title: 'Spot 중단 알람 설정', desc: 'Spot 인스턴스 중단 2분 전 알림을 위한 EventBridge 규칙을 만드세요.',
        hint: 'aws events put-rule --name spot-interruption --event-pattern "{\"source\":[\"aws.ec2\"],\"detail-type\":[\"EC2 Spot Instance Interruption Warning\"]}" --state ENABLED',
        answers: ['aws events put-rule --name spot-interruption --event-pattern "{\"source\":[\"aws.ec2\"],\"detail-type\":[\"ec2 spot instance interruption warning\"]}" --state enabled'],
        successOutput: ['{"RuleArn": "arn:aws:events:us-east-1:123456789012:rule/spot-interruption"}'] },
    ],
    explanation: 'Spot 인스턴스는 On-Demand 대비 최대 90% 저렴합니다. 중단(2분 전 통보)에 대비해 작업 체크포인트를 저장하거나 SQS로 작업을 분산하세요. Spot Fleet의 다양한 인스턴스 타입과 AZ 조합으로 중단 가능성을 낮출 수 있습니다.',
  },
  4: {
    id: 'COST-04', title: 'COST-04 S3 Lifecycle 정책으로 스토리지 비용 절감',
    scenario: 'S3 버킷에 로그 파일이 쌓여 수백 GB가 됐습니다. 30일 이후 파일은 잘 안 보는데 Standard 요금을 내고 있습니다. Lifecycle 정책으로 자동으로 저렴한 스토리지 클래스로 전환하세요.',
    steps: [
      { title: '버킷 스토리지 사용량 확인', desc: '버킷의 총 크기와 객체 수를 확인하세요.',
        hint: 'aws s3api list-objects-v2 --bucket app-logs-bucket --query "{Count:length(Contents),TotalSize:sum(Contents[].Size)}"',
        answers: ['aws s3api list-objects-v2 --bucket app-logs-bucket --query "{count:length(contents),totalsize:sum(contents[].size)}"'],
        successOutput: ['{"Count": 184293, "TotalSize": 429496729600}'] },
      { title: 'Lifecycle 규칙 추가', desc: '30일 후 S3-IA, 90일 후 Glacier로 전환하는 규칙을 설정하세요.',
        hint: 'aws s3api put-bucket-lifecycle-configuration --bucket app-logs-bucket --lifecycle-configuration file://lifecycle.json',
        answers: ['aws s3api put-bucket-lifecycle-configuration --bucket app-logs-bucket --lifecycle-configuration file://lifecycle.json'],
        successOutput: [''] },
      { title: 'Lifecycle 규칙 확인', desc: '설정된 Lifecycle 규칙을 확인하세요.',
        hint: 'aws s3api get-bucket-lifecycle-configuration --bucket app-logs-bucket',
        answers: ['aws s3api get-bucket-lifecycle-configuration --bucket app-logs-bucket'],
        successOutput: ['{"Rules": [{"ID": "log-tiering", "Status": "Enabled", "Transitions": [{"Days": 30, "StorageClass": "STANDARD_IA"}, {"Days": 90, "StorageClass": "GLACIER"}], "Expiration": {"Days": 365}}]}'] },
      { title: 'S3 스토리지 클래스 분석 활성화', desc: '접근 패턴 분석을 위해 Storage Class Analysis를 켜세요.',
        hint: 'aws s3api put-bucket-analytics-configuration --bucket app-logs-bucket --id all-objects --analytics-configuration Id=all-objects,StorageClassAnalysis={DataExport={OutputSchemaVersion=V_1,Destination={S3BucketDestination={Format=CSV,Bucket=arn:aws:s3:::analytics-results-bucket}}}}',
        answers: ['aws s3api put-bucket-analytics-configuration --bucket app-logs-bucket --id all-objects --analytics-configuration id=all-objects,storageclassanalysis={dataexport={outputschemaversion=v_1,destination={s3bucketdestination={format=csv,bucket=arn:aws:s3:::analytics-results-bucket}}}}'],
        successOutput: [''] },
    ],
    explanation: 'S3 Lifecycle 정책은 객체를 자동으로 더 저렴한 스토리지 클래스로 이동하거나 삭제합니다. Standard → Standard-IA: 58% 절감, Standard-IA → Glacier: 80% 절감. 단, Standard-IA는 128KB 최소 크기와 30일 최소 보관 요금이 있으므로 작은 파일이 많으면 오히려 비용이 늘 수 있습니다.',
  },
  5: {
    id: 'COST-05', title: 'COST-05 EBS 미사용 볼륨 정리',
    scenario: '인스턴스 종료 후에도 EBS 볼륨이 남아 비용이 청구됩니다. 연결되지 않은(available) EBS 볼륨을 찾아 스냅샷을 찍고 삭제하세요.',
    steps: [
      { title: '미연결 EBS 볼륨 목록 조회', desc: 'available 상태인 EBS 볼륨 목록을 확인하세요.',
        hint: 'aws ec2 describe-volumes --filters Name=status,Values=available --query "Volumes[*].{Id:VolumeId,Size:Size,Type:VolumeType,Created:CreateTime}" --output table',
        answers: ['aws ec2 describe-volumes --filters name=status,values=available --query "volumes[*].{id:volumeid,size:size,type:volumetype,created:createtime}" --output table'],
        successOutput: ['----------------------------------------------------------\n|                    DescribeVolumes                     |\n+------------------------+-------+----------+------------+\n|          Id            | Size  |  Type    |  Created   |\n+------------------------+-------+----------+------------+\n| vol-0aaa111222333444   |  50   |  gp3    | 2024-01-01 |\n| vol-0bbb222333444555   | 100   |  gp2    | 2024-01-05 |\n+------------------------+-------+----------+------------+'] },
      { title: 'EBS 스냅샷 생성', desc: '삭제 전 볼륨 스냅샷을 생성하세요.',
        hint: 'aws ec2 create-snapshot --volume-id vol-0aaa111222333444 --description "Backup before deletion 2024-01-15"',
        answers: ['aws ec2 create-snapshot --volume-id vol-0aaa111222333444 --description "backup before deletion 2024-01-15"'],
        successOutput: ['{"SnapshotId": "snap-0abc123def456789", "State": "pending", "VolumeId": "vol-0aaa111222333444", "VolumeSize": 50, "Description": "Backup before deletion 2024-01-15"}'] },
      { title: '스냅샷 완료 대기', desc: '스냅샷이 completed 상태가 됐는지 확인하세요.',
        hint: 'aws ec2 describe-snapshots --snapshot-ids snap-0abc123def456789 --query "Snapshots[0].{State:State,Progress:Progress}"',
        answers: ['aws ec2 describe-snapshots --snapshot-ids snap-0abc123def456789 --query "snapshots[0].{state:state,progress:progress}"'],
        successOutput: ['{"State": "completed", "Progress": "100%"}'] },
      { title: 'EBS 볼륨 삭제', desc: '스냅샷 완료 후 미사용 볼륨을 삭제하세요.',
        hint: 'aws ec2 delete-volume --volume-id vol-0aaa111222333444',
        answers: ['aws ec2 delete-volume --volume-id vol-0aaa111222333444'],
        successOutput: [''] },
    ],
    explanation: 'EBS 볼륨은 인스턴스에 연결되지 않아도 provisioned 크기에 따라 비용이 청구됩니다. 정기적으로 available 상태 볼륨을 감사하세요. AWS Trusted Advisor와 Cost Explorer의 리소스 최적화 권고도 미사용 리소스를 찾는 데 도움이 됩니다.',
  },
  6: {
    id: 'COST-06', title: 'COST-06 미사용 Elastic IP 해제',
    scenario: 'EC2 인스턴스를 삭제했는데 Elastic IP가 연결되지 않은 채 남아 있습니다. 연결되지 않은 EIP는 시간당 요금이 부과됩니다. 미사용 EIP를 찾아 해제하세요.',
    steps: [
      { title: '미연결 Elastic IP 조회', desc: 'InstanceId가 없는 Elastic IP를 찾으세요.',
        hint: 'aws ec2 describe-addresses --query "Addresses[?!InstanceId].{AllocationId:AllocationId,PublicIp:PublicIp,AssociationId:AssociationId}"',
        answers: ['aws ec2 describe-addresses --query "addresses[?!instanceid].{allocationid:allocationid,publicip:publicip,associationid:associationid}"'],
        successOutput: ['[{"AllocationId": "eipalloc-0abc123def456789", "PublicIp": "54.210.123.45", "AssociationId": null}, {"AllocationId": "eipalloc-0def456789abc012", "PublicIp": "52.90.234.56", "AssociationId": null}]'] },
      { title: 'EIP 사용 여부 재확인', desc: 'Route53 등 다른 서비스에서 참조하는지 확인 후 해제하세요.',
        hint: 'aws ec2 describe-addresses --allocation-ids eipalloc-0abc123def456789 --query "Addresses[0].{PublicIp:PublicIp,Domain:Domain,Tags:Tags}"',
        answers: ['aws ec2 describe-addresses --allocation-ids eipalloc-0abc123def456789 --query "addresses[0].{publicip:publicip,domain:domain,tags:tags}"'],
        successOutput: ['{"PublicIp": "54.210.123.45", "Domain": "vpc", "Tags": [{"Key": "Name", "Value": "old-prod-ip"}]}'] },
      { title: 'EIP 해제', desc: 'Elastic IP를 해제(release)하세요.',
        hint: 'aws ec2 release-address --allocation-id eipalloc-0abc123def456789',
        answers: ['aws ec2 release-address --allocation-id eipalloc-0abc123def456789'],
        successOutput: [''] },
      { title: '남은 EIP 확인', desc: '해제 후 남아있는 EIP 목록을 확인하세요.',
        hint: 'aws ec2 describe-addresses --query "Addresses[*].{IP:PublicIp,Instance:InstanceId,Status:Domain}"',
        answers: ['aws ec2 describe-addresses --query "addresses[*].{ip:publicip,instance:instanceid,status:domain}"'],
        successOutput: ['[{"IP": "52.90.234.56", "Instance": null, "Status": "vpc"}]'] },
    ],
    explanation: '연결되지 않은 Elastic IP는 시간당 $0.005가 청구됩니다(월 약 $3.60). 작아 보이지만 수십 개가 쌓이면 의미 있는 비용입니다. 인스턴스 종료 시 자동으로 EIP도 해제되도록 IaC 코드(Terraform 등)를 업데이트하는 것이 좋습니다.',
  },
  7: {
    id: 'COST-07', title: 'COST-07 CloudWatch Logs 보존 기간 설정',
    scenario: 'CloudWatch Logs 그룹이 기본 "무제한" 보존으로 설정돼 로그가 무한정 쌓이고 있습니다. 자주 조회하지 않는 로그 그룹에 보존 기간을 설정해 비용을 줄이세요.',
    steps: [
      { title: '로그 그룹 목록 및 보존 기간 확인', desc: '보존 기간이 설정되지 않은 로그 그룹을 찾으세요.',
        hint: 'aws logs describe-log-groups --query "logGroups[?!retentionInDays].{Name:logGroupName,Size:storedBytes}" --output table',
        answers: ['aws logs describe-log-groups --query "loggroups[?!retentionindays].{name:loggroupname,size:storedbytes}" --output table'],
        successOutput: ['------------------------------------------------------------\n|               DescribeLogGroups                          |\n+---------------------------------+-----------+\n|              Name               |   Size    |\n+---------------------------------+-----------+\n| /aws/lambda/api-handler         | 524288000 |\n| /aws/rds/cluster/prod-aurora    | 838860800 |\n+---------------------------------+-----------+'] },
      { title: 'Lambda 로그 보존 30일로 설정', desc: '/aws/lambda/api-handler 로그 그룹 보존 기간을 30일로 설정하세요.',
        hint: 'aws logs put-retention-policy --log-group-name /aws/lambda/api-handler --retention-in-days 30',
        answers: ['aws logs put-retention-policy --log-group-name /aws/lambda/api-handler --retention-in-days 30'],
        successOutput: [''] },
      { title: 'RDS 로그 보존 14일로 설정', desc: '/aws/rds/cluster/prod-aurora 로그 그룹 보존 기간을 14일로 설정하세요.',
        hint: 'aws logs put-retention-policy --log-group-name /aws/rds/cluster/prod-aurora --retention-in-days 14',
        answers: ['aws logs put-retention-policy --log-group-name /aws/rds/cluster/prod-aurora --retention-in-days 14'],
        successOutput: [''] },
      { title: '설정 확인', desc: '보존 기간이 올바르게 설정됐는지 확인하세요.',
        hint: 'aws logs describe-log-groups --query "logGroups[*].{Name:logGroupName,RetentionDays:retentionInDays}"',
        answers: ['aws logs describe-log-groups --query "loggroups[*].{name:loggroupname,retentiondays:retentionindays}"'],
        successOutput: ['[{"Name": "/aws/lambda/api-handler", "RetentionDays": 30}, {"Name": "/aws/rds/cluster/prod-aurora", "RetentionDays": 14}]'] },
    ],
    explanation: 'CloudWatch Logs는 저장 용량에 따라 GB당 $0.03/월이 청구됩니다. 보존 기간을 설정하면 기간 초과 로그가 자동 삭제됩니다. 장기 보관이 필요한 로그는 S3로 내보내고 CloudWatch에서는 짧게 유지하세요. 규정 준수 요건에 따라 보존 기간을 결정하세요.',
  },
  8: {
    id: 'COST-08', title: 'COST-08 NAT Gateway 비용 최적화',
    scenario: '여러 AZ에 각각 NAT Gateway가 있어 비용이 높습니다. 또한 S3로 가는 트래픽도 NAT Gateway를 경유하고 있습니다. VPC Endpoint를 추가해 S3 트래픽 비용을 없애세요.',
    steps: [
      { title: 'NAT Gateway 비용 확인', desc: '현재 NAT Gateway 비용을 서비스별로 조회하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --filter "{\"Dimensions\":{\"Key\":\"SERVICE\",\"Values\":[\"AWS Data Transfer\",\"Amazon VPC\"]}}" --group-by Type=DIMENSION,Key=USAGE_TYPE',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --filter "{\"dimensions\":{\"key\":\"service\",\"values\":[\"aws data transfer\",\"amazon vpc\"]}}" --group-by type=dimension,key=usage_type'],
        successOutput: ['{"ResultsByTime": [{"Groups": [{"Keys": ["USE1-NatGateway-Bytes"], "Metrics": {"BlendedCost": {"Amount": "182.50"}}}, {"Keys": ["USE1-NatGateway-Hours"], "Metrics": {"BlendedCost": {"Amount": "97.20"}}}]}]}'] },
      { title: 'S3 Gateway VPC Endpoint 생성', desc: 'S3 트래픽이 NAT Gateway를 거치지 않도록 Gateway Endpoint를 생성하세요.',
        hint: 'aws ec2 create-vpc-endpoint --vpc-id vpc-0abc123def456789 --service-name com.amazonaws.us-east-1.s3 --route-table-ids rtb-0abc123 rtb-0def456',
        answers: ['aws ec2 create-vpc-endpoint --vpc-id vpc-0abc123def456789 --service-name com.amazonaws.us-east-1.s3 --route-table-ids rtb-0abc123 rtb-0def456'],
        successOutput: ['{"VpcEndpoint": {"VpcEndpointId": "vpce-0abc123def456789", "State": "available", "ServiceName": "com.amazonaws.us-east-1.s3", "VpcEndpointType": "Gateway"}}'] },
      { title: 'DynamoDB VPC Endpoint 추가', desc: 'DynamoDB도 VPC Endpoint로 연결하세요.',
        hint: 'aws ec2 create-vpc-endpoint --vpc-id vpc-0abc123def456789 --service-name com.amazonaws.us-east-1.dynamodb --route-table-ids rtb-0abc123 rtb-0def456',
        answers: ['aws ec2 create-vpc-endpoint --vpc-id vpc-0abc123def456789 --service-name com.amazonaws.us-east-1.dynamodb --route-table-ids rtb-0abc123 rtb-0def456'],
        successOutput: ['{"VpcEndpoint": {"VpcEndpointId": "vpce-0def456789abc012", "State": "available", "ServiceName": "com.amazonaws.us-east-1.dynamodb", "VpcEndpointType": "Gateway"}}'] },
      { title: 'VPC Endpoint 목록 확인', desc: '생성된 VPC Endpoint를 확인하세요.',
        hint: 'aws ec2 describe-vpc-endpoints --filters Name=vpc-id,Values=vpc-0abc123def456789 --query "VpcEndpoints[*].{Id:VpcEndpointId,Service:ServiceName,State:State}"',
        answers: ['aws ec2 describe-vpc-endpoints --filters name=vpc-id,values=vpc-0abc123def456789 --query "vpcendpoints[*].{id:vpcendpointid,service:servicename,state:state}"'],
        successOutput: ['[{"Id": "vpce-0abc123def456789", "Service": "com.amazonaws.us-east-1.s3", "State": "available"}, {"Id": "vpce-0def456789abc012", "Service": "com.amazonaws.us-east-1.dynamodb", "State": "available"}]'] },
    ],
    explanation: 'S3/DynamoDB Gateway Endpoint는 무료입니다. 프라이빗 서브넷에서 S3로 가는 트래픽이 NAT Gateway를 우회하므로 데이터 처리 비용($0.045/GB)이 절감됩니다. 대용량 S3 작업이 많은 환경에서는 월 수백 달러 절감도 가능합니다.',
  },
  9: {
    id: 'COST-09', title: 'COST-09 RDS Reserved Instance 구매',
    scenario: '운영 RDS db.r5.large 인스턴스가 24/7 실행 중입니다. 1년 예약 인스턴스로 전환하면 On-Demand 대비 최대 42% 절감됩니다.',
    steps: [
      { title: '현재 RDS 인스턴스 확인', desc: '운영 중인 RDS 인스턴스 목록을 확인하세요.',
        hint: 'aws rds describe-db-instances --query "DBInstances[*].{Id:DBInstanceIdentifier,Class:DBInstanceClass,Engine:Engine,MultiAZ:MultiAZ}" --output table',
        answers: ['aws rds describe-db-instances --query "dbinstances[*].{id:dbinstanceidentifier,class:dbinstanceclass,engine:engine,multiaz:multiaz}" --output table'],
        successOutput: ['--------------------------------------------------------------\n|                  DescribeDBInstances                       |\n+-----------+---------------+-------+----------+\n|    Id     |    Class      |Engine | MultiAZ  |\n+-----------+---------------+-------+----------+\n| prod-mysql| db.r5.large   | mysql |  True    |\n| prod-pg   | db.r5.xlarge  | postgres| False  |\n+-----------+---------------+-------+----------+'] },
      { title: 'RDS 예약 인스턴스 오퍼링 조회', desc: 'db.r5.large MySQL 1년 No Upfront 예약 가격을 확인하세요.',
        hint: 'aws rds describe-reserved-db-instances-offerings --db-instance-class db.r5.large --product-description mysql --duration 31536000 --offering-type No Upfront --query "ReservedDBInstancesOfferings[0].{OfferingId:ReservedDBInstancesOfferingId,HourlyPrice:UsagePrice,FixedPrice:FixedPrice}"',
        answers: ['aws rds describe-reserved-db-instances-offerings --db-instance-class db.r5.large --product-description mysql --duration 31536000 --offering-type no upfront --query "reserveddbinstancesofferings[0].{offeringid:reserveddbinstancesofferingid,hourlyprice:usageprice,fixedprice:fixedprice}"'],
        successOutput: ['{"OfferingId": "rds-offering-abc123", "HourlyPrice": 0.145, "FixedPrice": 0.0}'] },
      { title: 'RDS 예약 인스턴스 구매', desc: 'db.r5.large MySQL 예약 인스턴스를 구매하세요.',
        hint: 'aws rds purchase-reserved-db-instances-offering --reserved-db-instances-offering-id rds-offering-abc123 --reserved-db-instance-id prod-mysql-ri-2024',
        answers: ['aws rds purchase-reserved-db-instances-offering --reserved-db-instances-offering-id rds-offering-abc123 --reserved-db-instance-id prod-mysql-ri-2024'],
        successOutput: ['{"ReservedDBInstance": {"ReservedDBInstanceId": "prod-mysql-ri-2024", "DBInstanceClass": "db.r5.large", "Duration": 31536000, "State": "payment-pending"}}'] },
      { title: '예약 인스턴스 적용 확인', desc: '구매한 예약 인스턴스 상태를 확인하세요.',
        hint: 'aws rds describe-reserved-db-instances --reserved-db-instance-id prod-mysql-ri-2024 --query "ReservedDBInstances[0].{State:State,StartTime:StartTime,Duration:Duration}"',
        answers: ['aws rds describe-reserved-db-instances --reserved-db-instance-id prod-mysql-ri-2024 --query "reserveddbinstances[0].{state:state,starttime:starttime,duration:duration}"'],
        successOutput: ['{"State": "active", "StartTime": "2024-01-01T00:00:00Z", "Duration": 31536000}'] },
    ],
    explanation: 'RDS Reserved Instance는 1년 No Upfront 기준 약 42%, All Upfront 기준 약 43% 절감됩니다. 예약 인스턴스는 자동으로 같은 엔진/클래스/리전의 On-Demand 인스턴스에 적용됩니다. Multi-AZ 예약 인스턴스는 Multi-AZ 인스턴스에만 적용됩니다.',
  },
  10: {
    id: 'COST-10', title: 'COST-10 Lambda ARM (Graviton2) 마이그레이션',
    scenario: 'Lambda 함수가 x86_64 아키텍처로 실행 중입니다. arm64(Graviton2)로 전환하면 동일 성능에 20% 저렴합니다. 아키텍처를 변경하고 비용 절감을 확인하세요.',
    steps: [
      { title: '현재 Lambda 아키텍처 확인', desc: '함수의 아키텍처와 런타임을 확인하세요.',
        hint: 'aws lambda get-function-configuration --function-name data-processor --query "{Runtime:Runtime,Arch:Architectures,Memory:MemorySize}"',
        answers: ['aws lambda get-function-configuration --function-name data-processor --query "{runtime:runtime,arch:architectures,memory:memorysize}"'],
        successOutput: ['{"Runtime": "python3.12", "Arch": ["x86_64"], "Memory": 512}'] },
      { title: 'ARM64로 아키텍처 변경', desc: '함수를 arm64로 업데이트하세요.',
        hint: 'aws lambda update-function-configuration --function-name data-processor --architectures arm64',
        answers: ['aws lambda update-function-configuration --function-name data-processor --architectures arm64'],
        successOutput: ['{"FunctionName": "data-processor", "Architectures": ["arm64"], "LastUpdateStatus": "Successful"}'] },
      { title: '함수 테스트 실행', desc: 'ARM64로 변경 후 함수가 정상 동작하는지 테스트하세요.',
        hint: 'aws lambda invoke --function-name data-processor --payload "{\"test\":true}" --cli-binary-format raw-in-base64-out response.json',
        answers: ['aws lambda invoke --function-name data-processor --payload "{\"test\":true}" --cli-binary-format raw-in-base64-out response.json'],
        successOutput: ['{"StatusCode": 200, "ExecutedVersion": "$LATEST"}'] },
      { title: '비용 비교 확인', desc: 'Lambda 비용 메트릭을 CloudWatch로 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/Lambda --metric-name Duration --dimensions Name=FunctionName,Value=data-processor --start-time 2024-01-02T00:00:00Z --end-time 2024-01-02T01:00:00Z --period 300 --statistics Average',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/lambda --metric-name duration --dimensions name=functionname,value=data-processor --start-time 2024-01-02t00:00:00z --end-time 2024-01-02t01:00:00z --period 300 --statistics average'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-02T00:05:00Z", "Average": 412.3, "Unit": "Milliseconds"}], "Label": "Duration"}'] },
    ],
    explanation: 'Lambda ARM64(Graviton2)는 x86_64 대비 20% 저렴하고 성능도 비슷하거나 더 빠릅니다. Python, Node.js, Java, Go 등 대부분의 런타임이 지원됩니다. 단, C 확장 라이브러리가 있는 경우 재컴파일이 필요합니다. Fargate ARM64도 동일하게 20% 저렴합니다.',
  },
  11: {
    id: 'COST-11', title: 'COST-11 EC2 우측 크기 조정 (Right Sizing)',
    scenario: 'EC2 인스턴스들의 CPU 사용률이 평균 5% 미만입니다. AWS Compute Optimizer 권고를 확인하고 과도하게 프로비저닝된 인스턴스를 적정 크기로 줄이세요.',
    steps: [
      { title: 'Compute Optimizer 권고 확인', desc: 'EC2 인스턴스에 대한 최적화 권고를 조회하세요.',
        hint: 'aws compute-optimizer get-ec2-instance-recommendations --query "instanceRecommendations[*].{Instance:instanceArn,Finding:finding,RecommendedType:recommendationOptions[0].instanceType,EstimatedSavings:recommendationOptions[0].estimatedMonthlySavings.value}"',
        answers: ['aws compute-optimizer get-ec2-instance-recommendations --query "instancerecommendations[*].{instance:instancearn,finding:finding,recommendedtype:recommendationoptions[0].instancetype,estimatedsavings:recommendationoptions[0].estimatedmonthlysavings.value}"'],
        successOutput: ['[{"Instance": "arn:aws:ec2:us-east-1:123456789012:instance/i-0abc1234567890abc", "Finding": "OVER_PROVISIONED", "RecommendedType": "t3.small", "EstimatedSavings": 18.50}]'] },
      { title: 'CPU 사용률 확인', desc: '지난 30일간 평균 CPU 사용률을 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name CPUUtilization --dimensions Name=InstanceId,Value=i-0abc1234567890abc --start-time 2024-01-01T00:00:00Z --end-time 2024-01-31T00:00:00Z --period 86400 --statistics Average',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/ec2 --metric-name cpuutilization --dimensions name=instanceid,value=i-0abc1234567890abc --start-time 2024-01-01t00:00:00z --end-time 2024-01-31t00:00:00z --period 86400 --statistics average'],
        successOutput: ['{"Datapoints": [{"Average": 3.2, "Unit": "Percent"}, {"Average": 4.1, "Unit": "Percent"}], "Label": "CPUUtilization"}'] },
      { title: '인스턴스 중지 및 타입 변경', desc: '인스턴스를 중지하고 t3.medium에서 t3.small로 변경하세요.',
        hint: 'aws ec2 stop-instances --instance-ids i-0abc1234567890abc && aws ec2 wait instance-stopped --instance-ids i-0abc1234567890abc && aws ec2 modify-instance-attribute --instance-id i-0abc1234567890abc --instance-type Value=t3.small',
        answers: ['aws ec2 stop-instances --instance-ids i-0abc1234567890abc && aws ec2 wait instance-stopped --instance-ids i-0abc1234567890abc && aws ec2 modify-instance-attribute --instance-id i-0abc1234567890abc --instance-type value=t3.small'],
        successOutput: ['{"StoppingInstances": [{"CurrentState": {"Name": "stopping"}}]}', '', ''] },
      { title: '인스턴스 재시작 후 확인', desc: '인스턴스를 시작하고 변경된 타입을 확인하세요.',
        hint: 'aws ec2 start-instances --instance-ids i-0abc1234567890abc && aws ec2 describe-instances --instance-ids i-0abc1234567890abc --query "Reservations[0].Instances[0].InstanceType"',
        answers: ['aws ec2 start-instances --instance-ids i-0abc1234567890abc && aws ec2 describe-instances --instance-ids i-0abc1234567890abc --query "reservations[0].instances[0].instancetype"'],
        successOutput: ['{"StartingInstances": [{"CurrentState": {"Name": "pending"}}]}', '"t3.small"'] },
    ],
    explanation: 'AWS Compute Optimizer는 CloudWatch 메트릭을 분석해 최적 인스턴스 타입을 추천합니다. CPU 사용률 5% 미만은 명백한 과도 프로비저닝입니다. 단, 피크 시 트래픽도 고려해 최소 P95 사용률 기준으로 결정하세요.',
  },
  12: {
    id: 'COST-12', title: 'COST-12 S3 Intelligent-Tiering 설정',
    scenario: '접근 패턴이 불규칙한 S3 버킷이 있습니다. 자주 쓸 때는 Standard가 필요하지만 몇 달씩 안 쓰는 파일도 있습니다. Intelligent-Tiering으로 자동으로 최적 스토리지 클래스를 선택하게 하세요.',
    steps: [
      { title: '버킷 스토리지 클래스 분포 확인', desc: '버킷 내 스토리지 클래스별 객체 수를 확인하세요.',
        hint: 'aws s3api list-objects-v2 --bucket media-assets-bucket --query "Contents[*].StorageClass" --output text | sort | uniq -c',
        answers: ['aws s3api list-objects-v2 --bucket media-assets-bucket --query "contents[*].storageclass" --output text | sort | uniq -c'],
        successOutput: ['  184293 STANDARD'] },
      { title: 'Intelligent-Tiering 전환 Lifecycle 규칙 추가', desc: '모든 객체를 Intelligent-Tiering으로 전환하는 규칙을 설정하세요.',
        hint: 'aws s3api put-bucket-lifecycle-configuration --bucket media-assets-bucket --lifecycle-configuration "{\"Rules\":[{\"ID\":\"to-intelligent-tiering\",\"Status\":\"Enabled\",\"Filter\":{\"Prefix\":\"\"},\"Transitions\":[{\"Days\":0,\"StorageClass\":\"INTELLIGENT_TIERING\"}]}]}"',
        answers: ['aws s3api put-bucket-lifecycle-configuration --bucket media-assets-bucket --lifecycle-configuration "{\"rules\":[{\"id\":\"to-intelligent-tiering\",\"status\":\"enabled\",\"filter\":{\"prefix\":\"\"},\"transitions\":[{\"days\":0,\"storageclass\":\"intelligent_tiering\"}]}]}"'],
        successOutput: [''] },
      { title: 'Intelligent-Tiering Archive 설정', desc: '90일 미접근 시 Archive 티어, 180일 시 Deep Archive 티어로 이동하도록 설정하세요.',
        hint: 'aws s3api put-bucket-intelligent-tiering-configuration --bucket media-assets-bucket --id media-it-config --intelligent-tiering-configuration Id=media-it-config,Status=Enabled,Tierings=[{Days=90,AccessTier=ARCHIVE_ACCESS},{Days=180,AccessTier=DEEP_ARCHIVE_ACCESS}]',
        answers: ['aws s3api put-bucket-intelligent-tiering-configuration --bucket media-assets-bucket --id media-it-config --intelligent-tiering-configuration id=media-it-config,status=enabled,tierings=[{days=90,accesstier=archive_access},{days=180,accesstier=deep_archive_access}]'],
        successOutput: [''] },
      { title: 'Intelligent-Tiering 설정 확인', desc: 'Intelligent-Tiering 구성을 확인하세요.',
        hint: 'aws s3api get-bucket-intelligent-tiering-configuration --bucket media-assets-bucket --id media-it-config',
        answers: ['aws s3api get-bucket-intelligent-tiering-configuration --bucket media-assets-bucket --id media-it-config'],
        successOutput: ['{"IntelligentTieringConfiguration": {"Id": "media-it-config", "Status": "Enabled", "Tierings": [{"Days": 90, "AccessTier": "ARCHIVE_ACCESS"}, {"Days": 180, "AccessTier": "DEEP_ARCHIVE_ACCESS"}]}}'] },
    ],
    explanation: 'Intelligent-Tiering은 접근 패턴에 따라 자동으로 Frequent/Infrequent/Archive 티어를 이동합니다. 관리 비용(객체당 $0.0025/1000)이 있으므로 128KB 이하 작은 파일이 많으면 오히려 비쌀 수 있습니다. 접근 패턴 예측이 어려운 대용량 객체에 적합합니다.',
  },
  13: {
    id: 'COST-13', title: 'COST-13 AWS Cost Anomaly Detection',
    scenario: '갑자기 AWS 비용이 평소의 3배로 뛰었는데 원인을 뒤늦게 알았습니다. Cost Anomaly Detection을 설정해 비정상적인 비용 급증을 즉시 감지하세요.',
    steps: [
      { title: '비용 모니터 생성', desc: 'EC2 서비스 비용을 모니터링하는 Cost Monitor를 생성하세요.',
        hint: 'aws ce create-anomaly-monitor --anomaly-monitor MonitorName=ec2-monitor,MonitorType=DIMENSIONAL,MonitorDimension=SERVICE',
        answers: ['aws ce create-anomaly-monitor --anomaly-monitor monitorname=ec2-monitor,monitortype=dimensional,monitordimension=service'],
        successOutput: ['{"MonitorArn": "arn:aws:ce::123456789012:anomalymonitor/abc123def-4567-890a-bcde-f01234567890"}'] },
      { title: '알람 구독 생성', desc: '비용이 $50 이상 급증 시 이메일 알람을 설정하세요.',
        hint: 'aws ce create-anomaly-subscription --anomaly-subscription SubscriptionName=cost-alert,MonitorArnList=arn:aws:ce::123456789012:anomalymonitor/abc123def-4567-890a-bcde-f01234567890,Subscribers=[{Address=admin@company.com,Type=EMAIL}],Threshold=50,Frequency=DAILY',
        answers: ['aws ce create-anomaly-subscription --anomaly-subscription subscriptionname=cost-alert,monitorarnlist=arn:aws:ce::123456789012:anomalymonitor/abc123def-4567-890a-bcde-f01234567890,subscribers=[{address=admin@company.com,type=email}],threshold=50,frequency=daily'],
        successOutput: ['{"SubscriptionArn": "arn:aws:ce::123456789012:anomalysubscription/def456789-0abc-1234-5678-90abcdef0123"}'] },
      { title: '이상 탐지 이력 조회', desc: '탐지된 비용 이상 목록을 확인하세요.',
        hint: 'aws ce get-anomalies --date-interval StartDate=2024-01-01,EndDate=2024-01-31 --query "Anomalies[*].{Service:RootCauses[0].Service,Impact:Impact.TotalImpact,StartDate:AnomalyStartDate}"',
        answers: ['aws ce get-anomalies --date-interval startdate=2024-01-01,enddate=2024-01-31 --query "anomalies[*].{service:rootcauses[0].service,impact:impact.totalimpact,startdate:anomalystartdate}"'],
        successOutput: ['[{"Service": "Amazon EC2", "Impact": 245.60, "StartDate": "2024-01-15"}]'] },
      { title: '모니터 목록 확인', desc: '생성된 비용 모니터 목록을 확인하세요.',
        hint: 'aws ce get-anomaly-monitors --query "AnomalyMonitors[*].{Name:MonitorName,Type:MonitorType,Status:CreationDate}"',
        answers: ['aws ce get-anomaly-monitors --query "anomalymonitors[*].{name:monitorname,type:monitortype,status:creationdate}"'],
        successOutput: ['[{"Name": "ec2-monitor", "Type": "DIMENSIONAL", "Status": "2024-01-01"}]'] },
    ],
    explanation: 'Cost Anomaly Detection은 머신러닝으로 비용 패턴을 학습하고 이상 지출을 감지합니다. 서비스 전체, 연결된 계정, 비용 할당 태그, 비용 범주 기준으로 모니터를 만들 수 있습니다. 기존 알람보다 오탐이 적고 근본 원인(서비스/리전/사용 유형)도 제공합니다.',
  },
  14: {
    id: 'COST-14', title: 'COST-14 비용 할당 태그 활성화',
    scenario: '개발팀, 운영팀, 데이터팀의 비용을 분리해서 봐야 하는데 현재는 전체 비용만 보입니다. Cost Allocation Tags로 팀별 비용을 분리하고 Cost Explorer에서 팀별 리포트를 만드세요.',
    steps: [
      { title: '사용자 정의 태그 활성화', desc: 'team 태그를 비용 할당 태그로 활성화하세요.',
        hint: 'aws ce create-cost-category-definition --name TeamCosts --rule-version CostCategoryExpression.v1 --rules file://cost-category-rules.json',
        answers: ['aws ce create-cost-category-definition --name teamcosts --rule-version costcategoryexpression.v1 --rules file://cost-category-rules.json'],
        successOutput: ['{"CostCategoryArn": "arn:aws:ce::123456789012:costcategory/abc123", "EffectiveStart": "2024-01-01T00:00:00Z"}'] },
      { title: 'EC2 인스턴스에 팀 태그 추가', desc: '운영팀 인스턴스에 team=ops 태그를 추가하세요.',
        hint: 'aws ec2 create-tags --resources i-0abc1234567890abc i-0def1234567890abc --tags Key=team,Value=ops Key=env,Value=prod',
        answers: ['aws ec2 create-tags --resources i-0abc1234567890abc i-0def1234567890abc --tags key=team,value=ops key=env,value=prod'],
        successOutput: [''] },
      { title: 'S3 버킷에 팀 태그 추가', desc: '데이터팀 버킷에 team=data 태그를 추가하세요.',
        hint: 'aws s3api put-bucket-tagging --bucket data-lake-bucket --tagging TagSet=[{Key=team,Value=data},{Key=env,Value=prod}]',
        answers: ['aws s3api put-bucket-tagging --bucket data-lake-bucket --tagging tagset=[{key=team,value=data},{key=env,value=prod}]'],
        successOutput: [''] },
      { title: '팀별 비용 조회', desc: 'team 태그로 그룹화해 팀별 비용을 확인하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --group-by Type=TAG,Key=team',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --group-by type=tag,key=team'],
        successOutput: ['{"ResultsByTime": [{"Groups": [{"Keys": ["team$ops"], "Metrics": {"BlendedCost": {"Amount": "312.50"}}}, {"Keys": ["team$data"], "Metrics": {"BlendedCost": {"Amount": "198.30"}}}, {"Keys": ["team$dev"], "Metrics": {"BlendedCost": {"Amount": "87.20"}}}]}]}'] },
    ],
    explanation: '비용 할당 태그는 활성화 후 최대 24시간이 지나야 Cost Explorer에 반영됩니다. AWS 생성 태그와 사용자 정의 태그 모두 사용 가능합니다. 태그 정책을 AWS Organizations에서 강제하면 누락된 태그로 인한 비용 미분류를 방지할 수 있습니다.',
  },
  15: {
    id: 'COST-15', title: 'COST-15 ECR 이미지 정리',
    scenario: 'ECR 리포지토리에 수백 개의 오래된 Docker 이미지가 쌓여 스토리지 비용이 증가하고 있습니다. 최근 5개 이미지만 남기고 나머지를 자동으로 삭제하는 Lifecycle 정책을 설정하세요.',
    steps: [
      { title: '현재 ECR 이미지 수 확인', desc: '리포지토리의 이미지 수와 총 크기를 확인하세요.',
        hint: 'aws ecr describe-images --repository-name my-api --query "imageDetails[*].{Tag:imageTags[0],Size:imageSizeInBytes,Pushed:imagePushedAt}" --output table',
        answers: ['aws ecr describe-images --repository-name my-api --query "imagedetails[*].{tag:imagetags[0],size:imagesizeinbytes,pushed:imagepushedat}" --output table'],
        successOutput: ['-------------------------------\n| DescribeImages             |\n+--------+----------+--------+\n| Tag    |   Size   | Pushed |\n+--------+----------+--------+\n| latest | 52428800 | recent |\n| v1.0   | 51200000 | old    |\n+--------+----------+--------+\n(and 342 more images...)'] },
      { title: 'ECR Lifecycle 정책 설정', desc: '태그 없는 이미지와 오래된 이미지를 자동 삭제하는 정책을 설정하세요.',
        hint: 'aws ecr put-lifecycle-policy --repository-name my-api --lifecycle-policy-text "{\"rules\":[{\"rulePriority\":1,\"description\":\"Keep last 5 tagged\",\"selection\":{\"tagStatus\":\"tagged\",\"tagPrefixList\":[\"v\"],\"countType\":\"imageCountMoreThan\",\"countNumber\":5},\"action\":{\"type\":\"expire\"}},{\"rulePriority\":2,\"description\":\"Delete untagged\",\"selection\":{\"tagStatus\":\"untagged\",\"countType\":\"sinceImagePushed\",\"countUnit\":\"days\",\"countNumber\":1},\"action\":{\"type\":\"expire\"}}]}"',
        answers: ['aws ecr put-lifecycle-policy --repository-name my-api --lifecycle-policy-text "{\"rules\":[{\"rulepriority\":1,\"description\":\"keep last 5 tagged\",\"selection\":{\"tagstatus\":\"tagged\",\"tagprefixlist\":[\"v\"],\"counttype\":\"imagecountmorethan\",\"countnumber\":5},\"action\":{\"type\":\"expire\"}},{\"rulepriority\":2,\"description\":\"delete untagged\",\"selection\":{\"tagstatus\":\"untagged\",\"counttype\":\"sinceimagepushed\",\"countunit\":\"days\",\"countnumber\":1},\"action\":{\"type\":\"expire\"}}]}"'],
        successOutput: ['{"registryId": "123456789012", "repositoryName": "my-api", "lifecyclePolicyText": "{...}"}'] },
      { title: 'Lifecycle 정책 미리보기', desc: '정책 적용 시 삭제될 이미지를 미리 확인하세요.',
        hint: 'aws ecr get-lifecycle-policy-preview --repository-name my-api --query "previewResults[*].{Tag:imageTags[0],Action:action.type}"',
        answers: ['aws ecr get-lifecycle-policy-preview --repository-name my-api --query "previewresults[*].{tag:imagetags[0],action:action.type}"'],
        successOutput: ['[{"Tag": "v0.1", "Action": "EXPIRE"}, {"Tag": "v0.2", "Action": "EXPIRE"}, {"Tag": null, "Action": "EXPIRE"}]'] },
      { title: 'ECR 스토리지 비용 확인', desc: 'ECR 스토리지 사용량 메트릭을 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/ECR --metric-name RepositorySize --dimensions Name=RepositoryName,Value=my-api --start-time 2024-01-01T00:00:00Z --end-time 2024-01-31T00:00:00Z --period 86400 --statistics Maximum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/ecr --metric-name repositorysize --dimensions name=repositoryname,value=my-api --start-time 2024-01-01t00:00:00z --end-time 2024-01-31t00:00:00z --period 86400 --statistics maximum'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-31T00:00:00Z", "Maximum": 524288000.0, "Unit": "Bytes"}], "Label": "RepositorySize"}'] },
    ],
    explanation: 'ECR 스토리지는 GB당 $0.10/월이 청구됩니다. Lifecycle 정책으로 오래된 이미지를 자동 정리하면 CI/CD 파이프라인에서 이미지가 매일 쌓여도 비용이 통제됩니다. 태그 없는 이미지는 항상 즉시 삭제하는 것이 좋습니다.',
  },
};

"""

TARGET = 'src/web-app.tsx'
ANCHOR = 'const CHALLENGE_SCENARIOS: Record<string, Record<number, ChalScenario>>'
OLD_COST = 'COST: {}'
NEW_COST = 'COST: COST_CHALLENGES'

with open(TARGET, 'r', encoding='utf-8') as f:
    src = f.read()

if 'COST_CHALLENGES' in src:
    print('COST_CHALLENGES already present - skipping')
else:
    idx = src.find(ANCHOR)
    if idx == -1:
        raise RuntimeError(f'Anchor not found: {ANCHOR}')
    src = src[:idx] + COST_BLOCK + src[idx:]
    print('Inserted COST_CHALLENGES block (1-15)')

if OLD_COST in src:
    src = src.replace(OLD_COST, NEW_COST, 1)
    print(f'Replaced "{OLD_COST}" → "{NEW_COST}"')

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(src)

print('Done.')
