# -*- coding: utf-8 -*-
"""Adds COST challenges 16-30 into existing COST_CHALLENGES object."""

NEW_ENTRIES = r"""  16: {
    id: 'COST-16', title: 'COST-16 Auto Scaling 스케줄 기반 절감',
    scenario: '개발/스테이징 환경의 EC2 Auto Scaling 그룹이 24시간 실행됩니다. 업무 시간(월-금 9-18시)에만 인스턴스를 유지하고 나머지 시간엔 0으로 줄여 비용을 60% 절감하세요.',
    steps: [
      { title: '현재 ASG 설정 확인', desc: '개발 환경 Auto Scaling 그룹의 현재 설정을 확인하세요.',
        hint: 'aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names dev-asg --query "AutoScalingGroups[0].{Min:MinSize,Max:MaxSize,Desired:DesiredCapacity}"',
        answers: ['aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names dev-asg --query "autoscalinggroups[0].{min:minsize,max:maxsize,desired:desiredcapacity}"'],
        successOutput: ['{"Min": 2, "Max": 6, "Desired": 2}'] },
      { title: '업무 시간 시작 스케줄 추가', desc: '월~금 오전 9시(UTC 0시)에 인스턴스 2개로 늘리는 스케줄을 추가하세요.',
        hint: 'aws autoscaling put-scheduled-update-group-action --auto-scaling-group-name dev-asg --scheduled-action-name scale-up-morning --recurrence "0 0 * * 1-5" --min-size 2 --max-size 6 --desired-capacity 2',
        answers: ['aws autoscaling put-scheduled-update-group-action --auto-scaling-group-name dev-asg --scheduled-action-name scale-up-morning --recurrence "0 0 * * 1-5" --min-size 2 --max-size 6 --desired-capacity 2'],
        successOutput: [''] },
      { title: '업무 시간 종료 스케줄 추가', desc: '월~금 오후 9시(UTC 12시)에 인스턴스 0개로 줄이는 스케줄을 추가하세요.',
        hint: 'aws autoscaling put-scheduled-update-group-action --auto-scaling-group-name dev-asg --scheduled-action-name scale-down-evening --recurrence "0 12 * * 1-5" --min-size 0 --max-size 0 --desired-capacity 0',
        answers: ['aws autoscaling put-scheduled-update-group-action --auto-scaling-group-name dev-asg --scheduled-action-name scale-down-evening --recurrence "0 12 * * 1-5" --min-size 0 --max-size 0 --desired-capacity 0'],
        successOutput: [''] },
      { title: '스케줄 목록 확인', desc: '등록된 스케줄 액션을 확인하세요.',
        hint: 'aws autoscaling describe-scheduled-actions --auto-scaling-group-name dev-asg --query "ScheduledUpdateGroupActions[*].{Name:ScheduledActionName,Recurrence:Recurrence,Desired:DesiredCapacity}"',
        answers: ['aws autoscaling describe-scheduled-actions --auto-scaling-group-name dev-asg --query "scheduledupdategroupactions[*].{name:scheduledactionname,recurrence:recurrence,desired:desiredcapacity}"'],
        successOutput: ['[{"Name": "scale-up-morning", "Recurrence": "0 0 * * 1-5", "Desired": 2}, {"Name": "scale-down-evening", "Recurrence": "0 12 * * 1-5", "Desired": 0}]'] },
    ],
    explanation: '개발/스테이징 환경은 업무 시간 외에 인스턴스가 불필요합니다. 스케줄 스케일링으로 주말 포함 약 76%의 시간 동안 비용을 절감할 수 있습니다. AWS Instance Scheduler 솔루션을 사용하면 더 복잡한 스케줄도 관리할 수 있습니다.',
  },
  17: {
    id: 'COST-17', title: 'COST-17 S3 버킷 퍼블릭 액세스 비용 분석',
    scenario: 'S3에서 외부로 나가는 데이터 전송 비용이 매월 수백 달러입니다. 어떤 버킷에서 얼마나 데이터가 나가는지 분석하고 CloudFront로 전환해 전송 비용을 줄이세요.',
    steps: [
      { title: 'S3 데이터 전송 비용 조회', desc: 'Cost Explorer로 S3 데이터 전송 비용을 조회하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --filter "{\"And\":[{\"Dimensions\":{\"Key\":\"SERVICE\",\"Values\":[\"Amazon Simple Storage Service\"]}},{\"Dimensions\":{\"Key\":\"USAGE_TYPE\",\"Values\":[\"USE1-DataTransfer-Out-Bytes\"]}}]}"',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --filter "{\"and\":[{\"dimensions\":{\"key\":\"service\",\"values\":[\"amazon simple storage service\"]}},{\"dimensions\":{\"key\":\"usage_type\",\"values\":[\"use1-datatransfer-out-bytes\"]}}]}"'],
        successOutput: ['{"ResultsByTime": [{"Total": {"BlendedCost": {"Amount": "487.50", "Unit": "USD"}}}]}'] },
      { title: 'S3 버킷 요청 메트릭 활성화', desc: '가장 많이 요청되는 버킷의 메트릭을 활성화하세요.',
        hint: 'aws s3api put-bucket-metrics-configuration --bucket public-assets-bucket --id all-requests --metrics-configuration Id=all-requests',
        answers: ['aws s3api put-bucket-metrics-configuration --bucket public-assets-bucket --id all-requests --metrics-configuration id=all-requests'],
        successOutput: [''] },
      { title: 'CloudFront 오리진을 S3로 설정', desc: 'S3 버킷 앞에 CloudFront를 배포해 전송 비용을 낮추세요.',
        hint: 'aws cloudfront create-distribution --distribution-config file://cf-s3-config.json',
        answers: ['aws cloudfront create-distribution --distribution-config file://cf-s3-config.json'],
        successOutput: ['{"Distribution": {"Id": "E3QWRTZXMP65OJ", "DomainName": "d2abc456def789.cloudfront.net", "Status": "InProgress"}}'] },
      { title: 'S3 버킷 직접 접근 차단', desc: 'CloudFront 외 직접 S3 접근을 차단하세요.',
        hint: 'aws s3api put-public-access-block --bucket public-assets-bucket --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true',
        answers: ['aws s3api put-public-access-block --bucket public-assets-bucket --public-access-block-configuration blockpublicacls=true,ignorepublicacls=true,blockpublicpolicy=true,restrictpublicbuckets=true'],
        successOutput: [''] },
    ],
    explanation: 'S3에서 인터넷으로 나가는 데이터 전송은 GB당 $0.09가 청구됩니다. CloudFront를 통하면 오리진에서 CloudFront로의 전송은 무료이고 CloudFront 엣지에서 사용자로의 전송은 S3보다 저렴합니다($0.0085/GB). 캐시 히트율이 높을수록 절감 효과가 큽니다.',
  },
  18: {
    id: 'COST-18', title: 'COST-18 DynamoDB 비용 최적화',
    scenario: 'DynamoDB 테이블에 스캔 쿼리가 많아 RCU 비용이 높습니다. Provisioned 모드로 전환하고 Auto Scaling을 설정해 예측 가능한 비용을 만드세요.',
    steps: [
      { title: 'DynamoDB 소비 비용 확인', desc: 'DynamoDB RCU/WCU 소비량을 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/DynamoDB --metric-name ConsumedReadCapacityUnits --dimensions Name=TableName,Value=UserSessions --start-time 2024-01-01T00:00:00Z --end-time 2024-01-31T00:00:00Z --period 86400 --statistics Sum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/dynamodb --metric-name consumedreadcapacityunits --dimensions name=tablename,value=usersessions --start-time 2024-01-01t00:00:00z --end-time 2024-01-31t00:00:00z --period 86400 --statistics sum'],
        successOutput: ['{"Datapoints": [{"Sum": 8640000.0, "Unit": "Count"}], "Label": "ConsumedReadCapacityUnits"}'] },
      { title: 'Provisioned 모드로 전환', desc: '테이블을 PROVISIONED 모드로 전환하세요.',
        hint: 'aws dynamodb update-table --table-name UserSessions --billing-mode PROVISIONED --provisioned-throughput ReadCapacityUnits=100,WriteCapacityUnits=50',
        answers: ['aws dynamodb update-table --table-name usersessions --billing-mode provisioned --provisioned-throughput readcapacityunits=100,writecapacityunits=50'],
        successOutput: ['{"TableDescription": {"TableName": "UserSessions", "BillingModeSummary": {"BillingMode": "PROVISIONED"}, "ProvisionedThroughput": {"ReadCapacityUnits": 100, "WriteCapacityUnits": 50}}}'] },
      { title: 'Auto Scaling 정책 등록 (읽기)', desc: 'DynamoDB 읽기 용량 Auto Scaling을 설정하세요.',
        hint: 'aws application-autoscaling register-scalable-target --service-namespace dynamodb --resource-id table/UserSessions --scalable-dimension dynamodb:table:ReadCapacityUnits --min-capacity 50 --max-capacity 300',
        answers: ['aws application-autoscaling register-scalable-target --service-namespace dynamodb --resource-id table/usersessions --scalable-dimension dynamodb:table:readcapacityunits --min-capacity 50 --max-capacity 300'],
        successOutput: [''] },
      { title: 'Target Tracking 정책 설정', desc: '목표 사용률 70%로 Auto Scaling 정책을 설정하세요.',
        hint: 'aws application-autoscaling put-scaling-policy --service-namespace dynamodb --resource-id table/UserSessions --scalable-dimension dynamodb:table:ReadCapacityUnits --policy-name ddb-read-scaling --policy-type TargetTrackingScaling --target-tracking-scaling-policy-configuration PredefinedMetricSpecification={PredefinedMetricType=DynamoDBReadCapacityUtilization},TargetValue=70',
        answers: ['aws application-autoscaling put-scaling-policy --service-namespace dynamodb --resource-id table/usersessions --scalable-dimension dynamodb:table:readcapacityunits --policy-name ddb-read-scaling --policy-type targettrackingscaling --target-tracking-scaling-policy-configuration predefinedmetricspecification={predefinedmetrictype=dynamodbreadcapacityutilization},targetvalue=70'],
        successOutput: ['{"PolicyARN": "arn:aws:autoscaling:us-east-1:123456789012:scalingPolicy:ddb-read-scaling"}'] },
    ],
    explanation: '트래픽 패턴이 예측 가능하다면 Provisioned + Auto Scaling이 On-Demand보다 저렴합니다. Auto Scaling은 소비 용량이 설정 용량의 70%를 넘으면 Scale Out, 낮으면 Scale In합니다. 스캔 대신 쿼리와 GSI를 사용해 소비 RCU를 줄이는 것도 중요합니다.',
  },
  19: {
    id: 'COST-19', title: 'COST-19 Trusted Advisor 비용 절감 권고 확인',
    scenario: 'AWS 환경 전반에 걸쳐 낭비되는 리소스가 있는지 Trusted Advisor로 점검하세요. 미사용 로드밸런서, 유휴 RDS, 저사용 EC2를 찾아 정리하세요.',
    steps: [
      { title: 'Trusted Advisor 비용 최적화 체크 조회', desc: '비용 최적화 카테고리 체크 목록을 확인하세요.',
        hint: 'aws support describe-trusted-advisor-checks --language en --query "checks[?category==`cost_optimizing`].{Id:id,Name:name}" --output table',
        answers: ['aws support describe-trusted-advisor-checks --language en --query "checks[?category==`cost_optimizing`].{id:id,name:name}" --output table'],
        successOutput: ['--------------------------------------------------\n|      DescribeTrustedAdvisorChecks              |\n+------------------+-----------------------------+\n|       Id         |           Name              |\n+------------------+-----------------------------+\n| Qch7DwouX1       | Low Utilization EC2         |\n| hjLMh88uM8       | Idle Load Balancers         |\n| TYyFMgift4       | Underutilized EBS           |\n+------------------+-----------------------------+'] },
      { title: '유휴 로드밸런서 확인', desc: 'Idle Load Balancers 체크 결과를 확인하세요.',
        hint: 'aws support describe-trusted-advisor-check-result --check-id hjLMh88uM8 --language en --query "result.flaggedResources[*].{Region:region,Resource:resourceId,Reason:metadata[1]}"',
        answers: ['aws support describe-trusted-advisor-check-result --check-id hjlmh88um8 --language en --query "result.flaggedresources[*].{region:region,resource:resourceid,reason:metadata[1]}"'],
        successOutput: ['[{"Region": "us-east-1", "Resource": "old-dev-alb", "Reason": "No healthy instances behind LB for 7+ days"}]'] },
      { title: '유휴 로드밸런서 삭제', desc: '유휴 로드밸런서를 삭제하세요.',
        hint: 'aws elbv2 delete-load-balancer --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/old-dev-alb/abc123',
        answers: ['aws elbv2 delete-load-balancer --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/old-dev-alb/abc123'],
        successOutput: [''] },
      { title: 'Trusted Advisor 결과 새로고침', desc: '체크 결과를 새로고침하세요.',
        hint: 'aws support refresh-trusted-advisor-check --check-id hjLMh88uM8 --query "status.{Status:status,Timestamp:millisUntilNextRefreshable}"',
        answers: ['aws support refresh-trusted-advisor-check --check-id hjlmh88um8 --query "status.{status:status,timestamp:millisuntilnextrefreshable}"'],
        successOutput: ['{"Status": "enqueued", "Timestamp": 3600000}'] },
    ],
    explanation: 'Trusted Advisor는 비용 최적화, 성능, 보안, 내결함성 등 5개 카테고리의 200+ 체크를 제공합니다. Business/Enterprise Support 플랜에서 전체 체크를 사용할 수 있습니다. 월 1회 정기 점검으로 낭비되는 리소스를 꾸준히 제거하세요.',
  },
  20: {
    id: 'COST-20', title: 'COST-20 RDS 스냅샷 오래된 것 정리',
    scenario: 'RDS 수동 스냅샷이 수십 개 쌓여 스토리지 비용이 발생합니다. 90일 이상 된 스냅샷을 정리하고 자동 스냅샷 보존 기간을 조정하세요.',
    steps: [
      { title: '오래된 스냅샷 목록 조회', desc: '90일 이상 된 RDS 스냅샷을 조회하세요.',
        hint: 'aws rds describe-db-snapshots --snapshot-type manual --query "DBSnapshots[?SnapshotCreateTime<`2024-01-01`].{Id:DBSnapshotIdentifier,Size:AllocatedStorage,Created:SnapshotCreateTime}" --output table',
        answers: ['aws rds describe-db-snapshots --snapshot-type manual --query "dbsnapshots[?snapshotcreatetime<`2024-01-01`].{id:dbsnapshotidentifier,size:allocatedstorage,created:snapshotcreatetime}" --output table'],
        successOutput: ['-----------------------------------------------------\n|           DescribeDBSnapshots                     |\n+----------------------------+------+------------+\n|            Id              | Size |  Created   |\n+----------------------------+------+------------+\n| prod-mysql-snapshot-2023-09|  100 | 2023-09-01 |\n| prod-mysql-snapshot-2023-10|  100 | 2023-10-01 |\n+----------------------------+------+------------+'] },
      { title: '오래된 스냅샷 삭제', desc: '90일 이상 된 스냅샷을 삭제하세요.',
        hint: 'aws rds delete-db-snapshot --db-snapshot-identifier prod-mysql-snapshot-2023-09',
        answers: ['aws rds delete-db-snapshot --db-snapshot-identifier prod-mysql-snapshot-2023-09'],
        successOutput: ['{"DBSnapshot": {"DBSnapshotIdentifier": "prod-mysql-snapshot-2023-09", "Status": "deleted"}}'] },
      { title: '자동 스냅샷 보존 기간 단축', desc: '자동 백업 보존 기간을 35일에서 7일로 줄이세요.',
        hint: 'aws rds modify-db-instance --db-instance-identifier prod-mysql --backup-retention-period 7 --apply-immediately',
        answers: ['aws rds modify-db-instance --db-instance-identifier prod-mysql --backup-retention-period 7 --apply-immediately'],
        successOutput: ['{"DBInstance": {"DBInstanceIdentifier": "prod-mysql", "BackupRetentionPeriod": 7, "DBInstanceStatus": "modifying"}}'] },
      { title: '스냅샷 총 크기 확인', desc: '현재 남아있는 스냅샷 총 스토리지를 확인하세요.',
        hint: 'aws rds describe-db-snapshots --snapshot-type manual --query "sum(DBSnapshots[].AllocatedStorage)"',
        answers: ['aws rds describe-db-snapshots --snapshot-type manual --query "sum(dbsnapshots[].allocatedstorage)"'],
        successOutput: ['200'] },
    ],
    explanation: 'RDS 자동 스냅샷은 최대 35일 보존할 수 있으며 무료 스토리지(DB 크기의 100%)를 초과하면 비용이 청구됩니다. 수동 스냅샷은 삭제하기 전까지 계속 저장됩니다. 규정 준수 요건이 없다면 7일 보존이 충분합니다.',
  },
  21: {
    id: 'COST-21', title: 'COST-21 CloudFront 비용 최적화 (Price Class)',
    scenario: 'CloudFront 배포에서 모든 엣지 로케이션이 활성화돼 있는데 사용자가 미국/유럽에만 있습니다. Price Class 100으로 제한해 비용을 줄이세요.',
    steps: [
      { title: '현재 CloudFront 배포 설정 확인', desc: '배포의 현재 Price Class를 확인하세요.',
        hint: 'aws cloudfront get-distribution-config --id E2QWRTZXMP65OJ --query "DistributionConfig.{PriceClass:PriceClass,Origins:Origins.Quantity}"',
        answers: ['aws cloudfront get-distribution-config --id e2qwrtzxmp65oj --query "distributionconfig.{priceclass:priceclass,origins:origins.quantity}"'],
        successOutput: ['{"PriceClass": "PriceClass_All", "Origins": 1}'] },
      { title: 'Price Class 100으로 변경', desc: '미국/유럽 엣지만 사용하는 Price Class 100으로 변경하세요.',
        hint: 'aws cloudfront update-distribution --id E2QWRTZXMP65OJ --distribution-config file://cf-priceclass100.json --if-match E1PA6795UKMFR9',
        answers: ['aws cloudfront update-distribution --id e2qwrtzxmp65oj --distribution-config file://cf-priceclass100.json --if-match e1pa6795ukmfr9'],
        successOutput: ['{"Distribution": {"Id": "E2QWRTZXMP65OJ", "Status": "InProgress", "DistributionConfig": {"PriceClass": "PriceClass_100"}}}'] },
      { title: '지역별 트래픽 확인', desc: 'CloudWatch로 지역별 요청 수를 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/CloudFront --metric-name Requests --dimensions Name=DistributionId,Value=E2QWRTZXMP65OJ Name=Region,Value=Global --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period 3600 --statistics Sum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/cloudfront --metric-name requests --dimensions name=distributionid,value=e2qwrtzxmp65oj name=region,value=global --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period 3600 --statistics sum'],
        successOutput: ['{"Datapoints": [{"Sum": 482350.0, "Unit": "None"}], "Label": "Requests"}'] },
      { title: '배포 완료 확인', desc: 'Price Class 변경이 모든 엣지에 적용됐는지 확인하세요.',
        hint: 'aws cloudfront get-distribution --id E2QWRTZXMP65OJ --query "Distribution.{Status:Status,PriceClass:DistributionConfig.PriceClass}"',
        answers: ['aws cloudfront get-distribution --id e2qwrtzxmp65oj --query "distribution.{status:status,priceclass:distributionconfig.priceclass}"'],
        successOutput: ['{"Status": "Deployed", "PriceClass": "PriceClass_100"}'] },
    ],
    explanation: 'CloudFront Price Class는 어느 엣지 로케이션을 사용할지 결정합니다. PriceClass_All(모든 리전), PriceClass_200(북미+유럽+아시아 일부), PriceClass_100(북미+유럽)으로 나뉩니다. 사용자가 특정 지역에 집중된 경우 불필요한 엣지 비용을 줄일 수 있습니다.',
  },
  22: {
    id: 'COST-22', title: 'COST-22 Lambda 동시 실행 제한으로 비용 제어',
    scenario: '개발 환경의 Lambda 함수가 버그로 무한 루프에 빠져 수천 번 호출되었습니다. 함수별 동시 실행 제한으로 비용 폭증을 방지하세요.',
    steps: [
      { title: '현재 Lambda 동시 실행 현황 확인', desc: '계정 전체 동시 실행 한도와 사용량을 확인하세요.',
        hint: 'aws lambda get-account-settings --query "{ConcurrentExecutions:AccountLimit.ConcurrentExecutions,UnreservedConcurrentExecutions:AccountLimit.UnreservedConcurrentExecutions}"',
        answers: ['aws lambda get-account-settings --query "{concurrentexecutions:accountlimit.concurrentexecutions,unreservedconcurrentexecutions:accountlimit.unreservedconcurrentexecutions}"'],
        successOutput: ['{"ConcurrentExecutions": 1000, "UnreservedConcurrentExecutions": 850}'] },
      { title: '개발 환경 함수에 동시 실행 제한', desc: '개발 환경 Lambda에 동시 실행 10개 제한을 설정하세요.',
        hint: 'aws lambda put-function-concurrency --function-name dev-api-handler --reserved-concurrent-executions 10',
        answers: ['aws lambda put-function-concurrency --function-name dev-api-handler --reserved-concurrent-executions 10'],
        successOutput: ['{"ReservedConcurrentExecutions": 10}'] },
      { title: '동시 실행 스로틀 알람 설정', desc: 'Lambda Throttles가 발생하면 알람이 울리도록 설정하세요.',
        hint: 'aws cloudwatch put-metric-alarm --alarm-name dev-lambda-throttle --metric-name Throttles --namespace AWS/Lambda --dimensions Name=FunctionName,Value=dev-api-handler --statistic Sum --period 60 --threshold 5 --comparison-operator GreaterThanOrEqualToThreshold --evaluation-periods 1 --alarm-actions arn:aws:sns:us-east-1:123456789012:dev-alerts',
        answers: ['aws cloudwatch put-metric-alarm --alarm-name dev-lambda-throttle --metric-name throttles --namespace aws/lambda --dimensions name=functionname,value=dev-api-handler --statistic sum --period 60 --threshold 5 --comparison-operator greaterthanorequaltothreshold --evaluation-periods 1 --alarm-actions arn:aws:sns:us-east-1:123456789012:dev-alerts'],
        successOutput: [''] },
      { title: 'Lambda 비용 조회', desc: '이번 달 Lambda 비용을 확인하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --filter "{\"Dimensions\":{\"Key\":\"SERVICE\",\"Values\":[\"AWS Lambda\"]}}"',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --filter "{\"dimensions\":{\"key\":\"service\",\"values\":[\"aws lambda\"]}}"'],
        successOutput: ['{"ResultsByTime": [{"Total": {"BlendedCost": {"Amount": "12.34", "Unit": "USD"}}}]}'] },
    ],
    explanation: 'Reserved Concurrency를 설정하면 함수가 해당 수 이상 동시 실행되지 않습니다. 버그로 인한 폭주나 예산 초과를 방지합니다. 단, 운영 환경 함수에 너무 낮게 설정하면 정상 트래픽도 스로틀링될 수 있습니다.',
  },
  23: {
    id: 'COST-23', title: 'COST-23 S3 Glacier 장기 보관',
    scenario: '감사 로그를 7년간 보관해야 하는 규정이 있습니다. 현재 S3 Standard에 저장 중인 오래된 로그를 S3 Glacier Deep Archive로 이전해 비용을 97% 절감하세요.',
    steps: [
      { title: '오래된 로그 객체 크기 확인', desc: '2023년 이전 로그 파일의 총 크기를 확인하세요.',
        hint: 'aws s3api list-objects-v2 --bucket audit-logs-bucket --prefix 2022/ --query "{Count:length(Contents),TotalGB:sum(Contents[].Size)}"',
        answers: ['aws s3api list-objects-v2 --bucket audit-logs-bucket --prefix 2022/ --query "{count:length(contents),totalgb:sum(contents[].size)}"'],
        successOutput: ['{"Count": 8760, "TotalGB": 107374182400}'] },
      { title: 'Glacier Deep Archive 전환 규칙 설정', desc: '생성 후 365일이 지나면 Glacier Deep Archive로 이전하는 규칙을 설정하세요.',
        hint: 'aws s3api put-bucket-lifecycle-configuration --bucket audit-logs-bucket --lifecycle-configuration "{\"Rules\":[{\"ID\":\"archive-old-logs\",\"Status\":\"Enabled\",\"Filter\":{\"Prefix\":\"20\"},\"Transitions\":[{\"Days\":365,\"StorageClass\":\"DEEP_ARCHIVE\"}]}]}"',
        answers: ['aws s3api put-bucket-lifecycle-configuration --bucket audit-logs-bucket --lifecycle-configuration "{\"rules\":[{\"id\":\"archive-old-logs\",\"status\":\"enabled\",\"filter\":{\"prefix\":\"20\"},\"transitions\":[{\"days\":365,\"storageclass\":\"deep_archive\"}]}]}"'],
        successOutput: [''] },
      { title: '기존 객체 즉시 Glacier 이전', desc: '이미 있는 2022년 로그를 즉시 Glacier Deep Archive로 복사하세요.',
        hint: 'aws s3 cp s3://audit-logs-bucket/2022/ s3://audit-logs-bucket/2022/ --recursive --storage-class DEEP_ARCHIVE',
        answers: ['aws s3 cp s3://audit-logs-bucket/2022/ s3://audit-logs-bucket/2022/ --recursive --storage-class deep_archive'],
        successOutput: ['copy: s3://audit-logs-bucket/2022/01/01.log.gz to s3://audit-logs-bucket/2022/01/01.log.gz', '(8760 files copied)'] },
      { title: '스토리지 클래스 변경 확인', desc: '변경된 스토리지 클래스를 확인하세요.',
        hint: 'aws s3api list-objects-v2 --bucket audit-logs-bucket --prefix 2022/01/ --query "Contents[0:3].{Key:Key,StorageClass:StorageClass}"',
        answers: ['aws s3api list-objects-v2 --bucket audit-logs-bucket --prefix 2022/01/ --query "contents[0:3].{key:key,storageclass:storageclass}"'],
        successOutput: ['[{"Key": "2022/01/01.log.gz", "StorageClass": "DEEP_ARCHIVE"}, {"Key": "2022/01/02.log.gz", "StorageClass": "DEEP_ARCHIVE"}]'] },
    ],
    explanation: 'S3 Glacier Deep Archive는 GB당 $0.00099/월로 Standard($0.023)보다 97% 저렴합니다. 단, 복원 시 표준 12시간, 대용량 복원 시 48시간이 걸립니다. 7년 규정 준수 로그처럼 거의 꺼낼 일 없는 데이터에 최적입니다.',
  },
  24: {
    id: 'COST-24', title: 'COST-24 Fargate Spot으로 배치 작업 비용 절감',
    scenario: '매일 새벽 실행하는 데이터 처리 ECS 태스크가 On-Demand Fargate를 사용합니다. 중단이 허용되는 배치 작업에 Fargate Spot을 사용해 최대 70% 절감하세요.',
    steps: [
      { title: '현재 ECS 서비스 시작 유형 확인', desc: '배치 처리 태스크의 현재 설정을 확인하세요.',
        hint: 'aws ecs describe-services --cluster batch-cluster --services data-batch-service --query "services[0].{LaunchType:launchType,DesiredCount:desiredCount,TaskDef:taskDefinition}"',
        answers: ['aws ecs describe-services --cluster batch-cluster --services data-batch-service --query "services[0].{launchtype:launchtype,desiredcount:desiredcount,taskdef:taskdefinition}"'],
        successOutput: ['{"LaunchType": "FARGATE", "DesiredCount": 1, "TaskDef": "arn:aws:ecs:us-east-1:123456789012:task-definition/batch-task:1"}'] },
      { title: 'Fargate Spot 용량 공급자 생성', desc: 'FARGATE_SPOT 용량 공급자를 클러스터에 추가하세요.',
        hint: 'aws ecs put-cluster-capacity-providers --cluster batch-cluster --capacity-providers FARGATE FARGATE_SPOT --default-capacity-provider-strategy capacityProvider=FARGATE_SPOT,weight=1 capacityProvider=FARGATE,weight=0,base=0',
        answers: ['aws ecs put-cluster-capacity-providers --cluster batch-cluster --capacity-providers fargate fargate_spot --default-capacity-provider-strategy capacityprovider=fargate_spot,weight=1 capacityprovider=fargate,weight=0,base=0'],
        successOutput: ['{"cluster": {"clusterName": "batch-cluster", "capacityProviders": ["FARGATE", "FARGATE_SPOT"]}}'] },
      { title: 'Spot 사용 서비스로 업데이트', desc: '배치 서비스를 Fargate Spot으로 실행하도록 업데이트하세요.',
        hint: 'aws ecs update-service --cluster batch-cluster --service data-batch-service --capacity-provider-strategy capacityProvider=FARGATE_SPOT,weight=1,base=1 --force-new-deployment',
        answers: ['aws ecs update-service --cluster batch-cluster --service data-batch-service --capacity-provider-strategy capacityprovider=fargate_spot,weight=1,base=1 --force-new-deployment'],
        successOutput: ['{"service": {"serviceName": "data-batch-service", "capacityProviderStrategy": [{"capacityProvider": "FARGATE_SPOT", "weight": 1, "base": 1}]}}'] },
      { title: 'Fargate 비용 확인', desc: 'Fargate 비용이 줄었는지 Cost Explorer로 확인하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --filter "{\"Dimensions\":{\"Key\":\"SERVICE\",\"Values\":[\"Amazon Elastic Container Service\"]}}"',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --filter "{\"dimensions\":{\"key\":\"service\",\"values\":[\"amazon elastic container service\"]}}"'],
        successOutput: ['{"ResultsByTime": [{"Total": {"BlendedCost": {"Amount": "23.45", "Unit": "USD"}}}]}'] },
    ],
    explanation: 'Fargate Spot은 AWS의 여유 Fargate 용량을 사용하며 On-Demand 대비 최대 70% 저렴합니다. 중단 2분 전 알림이 오므로 배치 작업은 체크포인트를 저장하거나 재시도 로직을 구현하세요. 24/7 서비스에는 Spot Fallback 전략으로 FARGATE_SPOT 실패 시 FARGATE로 전환하도록 설정하세요.',
  },
  25: {
    id: 'COST-25', title: 'COST-25 미사용 로드밸런서 정리',
    scenario: '테스트 후 삭제하지 않은 ALB가 트래픽 없이 시간당 과금되고 있습니다. 연결된 타겟이 없거나 요청이 없는 로드밸런서를 찾아 정리하세요.',
    steps: [
      { title: '모든 로드밸런서 목록 조회', desc: '현재 생성된 로드밸런서 목록을 확인하세요.',
        hint: 'aws elbv2 describe-load-balancers --query "LoadBalancers[*].{Name:LoadBalancerName,Type:Type,State:State.Code,Created:CreatedTime}" --output table',
        answers: ['aws elbv2 describe-load-balancers --query "loadbalancers[*].{name:loadbalancername,type:type,state:state.code,created:createdtime}" --output table'],
        successOutput: ['----------------------------------------------------\n| DescribeLoadBalancers                           |\n+------------+--------+--------+-----------+\n|    Name    |  Type  | State  |  Created  |\n+------------+--------+--------+-----------+\n| prod-alb   | app    | active | 2024-01-01|\n| test-alb   | app    | active | 2023-11-01|\n| old-nlb    | net    | active | 2023-09-01|\n+------------+--------+--------+-----------+'] },
      { title: '유휴 LB 요청 수 확인', desc: 'test-alb의 최근 요청 수를 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/ApplicationELB --metric-name RequestCount --dimensions Name=LoadBalancer,Value=app/test-alb/abc123 --start-time 2024-01-01T00:00:00Z --end-time 2024-01-31T00:00:00Z --period 86400 --statistics Sum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/applicationelb --metric-name requestcount --dimensions name=loadbalancer,value=app/test-alb/abc123 --start-time 2024-01-01t00:00:00z --end-time 2024-01-31t00:00:00z --period 86400 --statistics sum'],
        successOutput: ['{"Datapoints": [], "Label": "RequestCount"}'] },
      { title: '로드밸런서 리스너 확인', desc: 'test-alb의 리스너와 타겟 그룹을 확인하세요.',
        hint: 'aws elbv2 describe-listeners --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/test-alb/abc123 --query "Listeners[*].{Port:Port,TargetGroup:DefaultActions[0].TargetGroupArn}"',
        answers: ['aws elbv2 describe-listeners --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/test-alb/abc123 --query "listeners[*].{port:port,targetgroup:defaultactions[0].targetgrouparn}"'],
        successOutput: ['[{"Port": 80, "TargetGroup": "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/empty-tg/abc123"}]'] },
      { title: '유휴 로드밸런서 삭제', desc: '유휴 상태의 test-alb를 삭제하세요.',
        hint: 'aws elbv2 delete-load-balancer --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/test-alb/abc123',
        answers: ['aws elbv2 delete-load-balancer --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/test-alb/abc123'],
        successOutput: [''] },
    ],
    explanation: 'ALB는 시간당 $0.008 + LCU(Load Balancer Capacity Unit) 과금이 있습니다. 타겟이 없거나 요청이 없어도 기본 시간 요금이 청구됩니다. 월 약 $6-$16이 낭비됩니다. 태그와 비용 할당으로 각 LB의 소유자를 명확히 하고 정기적으로 감사하세요.',
  },
  26: {
    id: 'COST-26', title: 'COST-26 데이터 전송 비용 분석 및 최적화',
    scenario: 'AZ 간 데이터 전송으로 인한 숨겨진 비용이 크게 발생하고 있습니다. 같은 AZ 내 통신으로 전환하거나 VPC Peering을 최적화해 전송 비용을 줄이세요.',
    steps: [
      { title: 'AZ 간 데이터 전송 비용 확인', desc: 'DataTransfer-Regional 비용을 조회하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --group-by Type=DIMENSION,Key=USAGE_TYPE --filter "{\"Dimensions\":{\"Key\":\"USAGE_TYPE\",\"Values\":[\"USE1-DataTransfer-Regional-Bytes\"]}}"',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --group-by type=dimension,key=usage_type --filter "{\"dimensions\":{\"key\":\"usage_type\",\"values\":[\"use1-datatransfer-regional-bytes\"]}}"'],
        successOutput: ['{"ResultsByTime": [{"Groups": [{"Keys": ["USE1-DataTransfer-Regional-Bytes"], "Metrics": {"BlendedCost": {"Amount": "234.50"}}}]}]}'] },
      { title: '인스턴스 AZ 분포 확인', desc: '현재 인스턴스들의 AZ 분포를 확인하세요.',
        hint: 'aws ec2 describe-instances --filters Name=instance-state-name,Values=running --query "Reservations[*].Instances[*].{Id:InstanceId,AZ:Placement.AvailabilityZone,Type:InstanceType}" --output table',
        answers: ['aws ec2 describe-instances --filters name=instance-state-name,values=running --query "reservations[*].instances[*].{id:instanceid,az:placement.availabilityzone,type:instancetype}" --output table'],
        successOutput: ['------------------------------------------\n| DescribeInstances                      |\n+-----------+-----------+-----------+\n|    Id     |    AZ     |   Type    |\n+-----------+-----------+-----------+\n| i-web-001 | us-east-1a| t3.medium |\n| i-app-001 | us-east-1b| c5.large  |\n| i-db-001  | us-east-1a| r5.large  |\n+-----------+-----------+-----------+'] },
      { title: 'VPC Flow Logs 활성화', desc: 'AZ 간 트래픽 패턴 분석을 위해 VPC Flow Logs를 활성화하세요.',
        hint: 'aws ec2 create-flow-logs --resource-type VPC --resource-ids vpc-0abc123def456789 --traffic-type ALL --log-destination-type s3 --log-destination arn:aws:s3:::flow-logs-bucket/vpc-flows/',
        answers: ['aws ec2 create-flow-logs --resource-type vpc --resource-ids vpc-0abc123def456789 --traffic-type all --log-destination-type s3 --log-destination arn:aws:s3:::flow-logs-bucket/vpc-flows/'],
        successOutput: ['{"FlowLogIds": ["fl-0abc123def456789"], "Unsuccessful": []}'] },
      { title: 'Flow Logs 분석 Athena 쿼리 실행', desc: 'S3에 저장된 Flow Logs를 Athena로 분석하세요.',
        hint: 'aws athena start-query-execution --query-string "SELECT srcaddr, dstaddr, SUM(bytes) as total_bytes FROM vpc_flow_logs WHERE srcaddr LIKE \"10.0.1.%\" AND dstaddr LIKE \"10.0.2.%\" GROUP BY 1,2 ORDER BY 3 DESC LIMIT 10" --result-configuration OutputLocation=s3://athena-results-bucket/',
        answers: ['aws athena start-query-execution --query-string "select srcaddr, dstaddr, sum(bytes) as total_bytes from vpc_flow_logs where srcaddr like \"10.0.1.%\" and dstaddr like \"10.0.2.%\" group by 1,2 order by 3 desc limit 10" --result-configuration outputlocation=s3://athena-results-bucket/'],
        successOutput: ['{"QueryExecutionId": "qe-abc123def456789"}'] },
    ],
    explanation: 'AZ 간 데이터 전송은 $0.01/GB, 리전 간 전송은 $0.02/GB가 청구됩니다. 웹-앱-DB 레이어를 같은 AZ에 배치하면 전송 비용이 0이 됩니다. VPC Flow Logs + Athena로 어떤 서버 쌍이 가장 많은 AZ 간 트래픽을 유발하는지 파악하세요.',
  },
  27: {
    id: 'COST-27', title: 'COST-27 AWS Organizations 비용 통합 결제',
    scenario: '개발/스테이징/운영 계정이 별도로 있어 할인 혜택을 받지 못하고 있습니다. AWS Organizations 통합 결제로 전체 사용량을 합산해 볼륨 할인을 받으세요.',
    steps: [
      { title: 'Organizations 현재 구성 확인', desc: '현재 조직 구조를 확인하세요.',
        hint: 'aws organizations describe-organization --query "Organization.{Id:Id,MasterAccount:MasterAccountId,FeatureSet:FeatureSet}"',
        answers: ['aws organizations describe-organization --query "organization.{id:id,masteraccount:masteraccountid,featureset:featureset}"'],
        successOutput: ['{"Id": "o-abc123def456", "MasterAccount": "123456789012", "FeatureSet": "ALL"}'] },
      { title: '계정 목록 조회', desc: '조직 내 모든 계정을 확인하세요.',
        hint: 'aws organizations list-accounts --query "Accounts[*].{Id:Id,Name:Name,Status:Status}" --output table',
        answers: ['aws organizations list-accounts --query "accounts[*].{id:id,name:name,status:status}" --output table'],
        successOutput: ['------------------------------------------\n|         ListAccounts                   |\n+----------------+-----------+--------+\n|       Id       |   Name    | Status |\n+----------------+-----------+--------+\n| 123456789012   | master    | ACTIVE |\n| 234567890123   | dev       | ACTIVE |\n| 345678901234   | staging   | ACTIVE |\n| 456789012345   | prod      | ACTIVE |\n+----------------+-----------+--------+'] },
      { title: '통합 비용 조회', desc: '모든 계정을 합산한 이번 달 총 비용을 확인하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost UnblendedCost --group-by Type=DIMENSION,Key=LINKED_ACCOUNT',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost unblendedcost --group-by type=dimension,key=linked_account'],
        successOutput: ['{"ResultsByTime": [{"Groups": [{"Keys": ["123456789012"], "Metrics": {"BlendedCost": {"Amount": "312.50"}}}, {"Keys": ["234567890123"], "Metrics": {"BlendedCost": {"Amount": "145.20"}}}, {"Keys": ["345678901234"], "Metrics": {"BlendedCost": {"Amount": "98.40"}}}, {"Keys": ["456789012345"], "Metrics": {"BlendedCost": {"Amount": "876.30"}}}]}]}'] },
      { title: 'SCP로 비용 제어 정책 적용', desc: '개발 계정에서 고비용 인스턴스 타입 생성을 금지하는 SCP를 적용하세요.',
        hint: 'aws organizations create-policy --name deny-large-instances --type SERVICE_CONTROL_POLICY --description "Deny expensive instance types in dev" --content file://scp-deny-large.json',
        answers: ['aws organizations create-policy --name deny-large-instances --type service_control_policy --description "deny expensive instance types in dev" --content file://scp-deny-large.json'],
        successOutput: ['{"Policy": {"PolicySummary": {"Id": "p-abc123def456", "Name": "deny-large-instances", "Type": "SERVICE_CONTROL_POLICY"}, "Content": "{...}"}}'] },
    ],
    explanation: 'AWS Organizations 통합 결제는 모든 계정의 S3, EC2 등 서비스 사용량을 합산해 볼륨 할인을 적용합니다. RI/Savings Plans도 조직 내 계정에 자동 공유됩니다. SCP로 개발 계정에서 비용이 높은 리소스 생성을 차단할 수 있습니다.',
  },
  28: {
    id: 'COST-28', title: 'COST-28 EC2 비용 태그 기반 자동화',
    scenario: '태그 없이 생성된 EC2 인스턴스 때문에 비용 추적이 불가능합니다. AWS Config 규칙으로 태그 없는 인스턴스를 감지하고 자동 알림을 보내세요.',
    steps: [
      { title: 'AWS Config 활성화 확인', desc: 'AWS Config 레코더 상태를 확인하세요.',
        hint: 'aws configservice describe-configuration-recorders --query "ConfigurationRecorders[0].{Name:name,RecordAll:recordingGroup.allSupported}"',
        answers: ['aws configservice describe-configuration-recorders --query "configurationrecorders[0].{name:name,recordall:recordinggroup.allsupported}"'],
        successOutput: ['{"Name": "default", "RecordAll": true}'] },
      { title: '필수 태그 Config 규칙 생성', desc: 'Name과 team 태그가 없는 EC2를 감지하는 규칙을 만드세요.',
        hint: 'aws configservice put-config-rule --config-rule ConfigRuleName=required-tags-ec2,Source={Owner=AWS,SourceIdentifier=REQUIRED_TAGS},Scope={ComplianceResourceTypes=[AWS::EC2::Instance]},InputParameters="{\"tag1Key\":\"Name\",\"tag2Key\":\"team\"}"',
        answers: ['aws configservice put-config-rule --config-rule configrulename=required-tags-ec2,source={owner=aws,sourceidentifier=required_tags},scope={complianceresourcetypes=[aws::ec2::instance]},inputparameters="{\"tag1key\":\"name\",\"tag2key\":\"team\"}"'],
        successOutput: [''] },
      { title: '비준수 리소스 확인', desc: 'required-tags 규칙을 위반하는 EC2 인스턴스를 조회하세요.',
        hint: 'aws configservice get-compliance-details-by-config-rule --config-rule-name required-tags-ec2 --compliance-types NON_COMPLIANT --query "EvaluationResults[*].EvaluationResultIdentifier.EvaluationResultQualifier.ResourceId"',
        answers: ['aws configservice get-compliance-details-by-config-rule --config-rule-name required-tags-ec2 --compliance-types non_compliant --query "evaluationresults[*].evaluationresultidentifier.evaluationresultqualifier.resourceid"'],
        successOutput: ['["i-0abc1234567890abc", "i-0def1234567890def", "i-0ghi1234567890ghi"]'] },
      { title: '자동 태그 추가 SSM 실행', desc: '비준수 인스턴스에 기본 태그를 자동으로 추가하세요.',
        hint: 'aws ec2 create-tags --resources i-0abc1234567890abc i-0def1234567890def --tags Key=team,Value=untagged Key=Name,Value=needs-tagging',
        answers: ['aws ec2 create-tags --resources i-0abc1234567890abc i-0def1234567890def --tags key=team,value=untagged key=name,value=needs-tagging'],
        successOutput: [''] },
    ],
    explanation: 'AWS Config REQUIRED_TAGS 규칙은 지정한 태그가 없는 리소스를 NON_COMPLIANT로 표시합니다. Config Rules + Lambda Auto Remediation으로 태그 누락 시 자동으로 소유자에게 이메일을 보내거나 일정 기간 후 자동 중지할 수 있습니다.',
  },
  29: {
    id: 'COST-29', title: 'COST-29 CloudWatch 메트릭 비용 최적화',
    scenario: 'CloudWatch 커스텀 메트릭과 API 호출 비용이 예상보다 높습니다. 불필요한 고해상도 메트릭을 표준 해상도로 낮추고 보존 기간을 조정해 비용을 줄이세요.',
    steps: [
      { title: 'CloudWatch 비용 확인', desc: 'CloudWatch 관련 비용을 분석하세요.',
        hint: 'aws ce get-cost-and-usage --time-period Start=2024-01-01,End=2024-01-31 --granularity MONTHLY --metrics BlendedCost --filter "{\"Dimensions\":{\"Key\":\"SERVICE\",\"Values\":[\"Amazon CloudWatch\"]}}" --group-by Type=DIMENSION,Key=USAGE_TYPE',
        answers: ['aws ce get-cost-and-usage --time-period start=2024-01-01,end=2024-01-31 --granularity monthly --metrics blendedcost --filter "{\"dimensions\":{\"key\":\"service\",\"values\":[\"amazon cloudwatch\"]}}" --group-by type=dimension,key=usage_type'],
        successOutput: ['{"ResultsByTime": [{"Groups": [{"Keys": ["USE1-MetricMonitorUsage"], "Metrics": {"BlendedCost": {"Amount": "45.80"}}}, {"Keys": ["USE1-High-Resolution-Metrics"], "Metrics": {"BlendedCost": {"Amount": "123.20"}}}]}]}'] },
      { title: '커스텀 메트릭 목록 확인', desc: '현재 등록된 커스텀 메트릭 수를 확인하세요.',
        hint: 'aws cloudwatch list-metrics --namespace CustomMetrics --query "length(Metrics)"',
        answers: ['aws cloudwatch list-metrics --namespace custommetrics --query "length(metrics)"'],
        successOutput: ['2840'] },
      { title: '불필요한 알람 목록 확인', desc: 'INSUFFICIENT_DATA 상태의 알람을 확인하세요.',
        hint: 'aws cloudwatch describe-alarms --state-value INSUFFICIENT_DATA --query "MetricAlarms[*].{Name:AlarmName,Metric:MetricName,LastUpdated:StateUpdatedTimestamp}" --output table',
        answers: ['aws cloudwatch describe-alarms --state-value insufficient_data --query "metricalarms[*].{name:alarmname,metric:metricname,lastupdated:stateupdatedtimestamp}" --output table'],
        successOutput: ['---------------------------------------------\n| DescribeAlarms                           |\n+---------------------+---------+----------+\n|        Name         | Metric  | Updated  |\n+---------------------+---------+----------+\n| old-test-alarm-001  | CPUUtil | 90 days  |\n| old-test-alarm-002  | Memory  | 120 days |\n+---------------------+---------+----------+'] },
      { title: '오래된 알람 삭제', desc: '90일 이상 INSUFFICIENT_DATA인 알람을 삭제하세요.',
        hint: 'aws cloudwatch delete-alarms --alarm-names old-test-alarm-001 old-test-alarm-002',
        answers: ['aws cloudwatch delete-alarms --alarm-names old-test-alarm-001 old-test-alarm-002'],
        successOutput: [''] },
    ],
    explanation: 'CloudWatch 고해상도 메트릭(1초)은 표준(1분)보다 비쌉니다. 필요하지 않은 고해상도 메트릭은 표준으로 낮추세요. INSUFFICIENT_DATA 알람은 연결된 리소스가 삭제됐음을 의미합니다. 미사용 대시보드, 로그 인사이트 쿼리 등도 비용을 유발합니다.',
  },
  30: {
    id: 'COST-30', title: 'COST-30 월별 비용 리포트 자동화',
    scenario: '매월 AWS 비용 리포트를 수동으로 만들고 있습니다. Cost and Usage Report(CUR)를 S3에 자동 저장하고 Athena로 쿼리해 팀별, 서비스별 월간 비용 분석을 자동화하세요.',
    steps: [
      { title: 'Cost and Usage Report 생성', desc: 'S3에 자동 저장되는 CUR 리포트를 설정하세요.',
        hint: 'aws cur put-report-definition --report-definition ReportName=monthly-cost-report,TimeUnit=MONTHLY,Format=Parquet,Compression=Parquet,AdditionalSchemaElements=RESOURCES,S3Bucket=cost-reports-bucket,S3Prefix=cur/,S3Region=us-east-1,ReportVersioning=OVERWRITE_REPORT,RefreshClosedReports=true --region us-east-1',
        answers: ['aws cur put-report-definition --report-definition reportname=monthly-cost-report,timeunit=monthly,format=parquet,compression=parquet,additionalschemaelements=resources,s3bucket=cost-reports-bucket,s3prefix=cur/,s3region=us-east-1,reportversioning=overwrite_report,refreshclosedreports=true --region us-east-1'],
        successOutput: [''] },
      { title: 'CUR 리포트 확인', desc: '생성된 CUR 리포트 정의를 확인하세요.',
        hint: 'aws cur describe-report-definitions --region us-east-1 --query "ReportDefinitions[?ReportName==`monthly-cost-report`].{Name:ReportName,S3Bucket:S3Bucket,TimeUnit:TimeUnit}"',
        answers: ['aws cur describe-report-definitions --region us-east-1 --query "reportdefinitions[?reportname==`monthly-cost-report`].{name:reportname,s3bucket:s3bucket,timeunit:timeunit}"'],
        successOutput: ['[{"Name": "monthly-cost-report", "S3Bucket": "cost-reports-bucket", "TimeUnit": "MONTHLY"}]'] },
      { title: 'Athena 테이블 생성', desc: 'CUR 데이터 분석을 위한 Athena 테이블을 생성하세요.',
        hint: 'aws athena start-query-execution --query-string "CREATE EXTERNAL TABLE IF NOT EXISTS cur_monthly (line_item_product_code STRING, line_item_unblended_cost DOUBLE, resource_tags_user_team STRING) STORED AS PARQUET LOCATION s3://cost-reports-bucket/cur/monthly-cost-report/monthly-cost-report/" --result-configuration OutputLocation=s3://athena-results-bucket/',
        answers: ['aws athena start-query-execution --query-string "create external table if not exists cur_monthly (line_item_product_code string, line_item_unblended_cost double, resource_tags_user_team string) stored as parquet location s3://cost-reports-bucket/cur/monthly-cost-report/monthly-cost-report/" --result-configuration outputlocation=s3://athena-results-bucket/'],
        successOutput: ['{"QueryExecutionId": "qe-table-create-001"}'] },
      { title: '팀별 비용 쿼리 실행', desc: 'Athena로 팀별 월간 비용을 집계하세요.',
        hint: 'aws athena start-query-execution --query-string "SELECT resource_tags_user_team as team, line_item_product_code as service, ROUND(SUM(line_item_unblended_cost),2) as total_cost FROM cur_monthly GROUP BY 1,2 ORDER BY 3 DESC" --result-configuration OutputLocation=s3://athena-results-bucket/monthly-reports/',
        answers: ['aws athena start-query-execution --query-string "select resource_tags_user_team as team, line_item_product_code as service, round(sum(line_item_unblended_cost),2) as total_cost from cur_monthly group by 1,2 order by 3 desc" --result-configuration outputlocation=s3://athena-results-bucket/monthly-reports/'],
        successOutput: ['{"QueryExecutionId": "qe-team-cost-001"}'] },
    ],
    explanation: 'Cost and Usage Report(CUR)는 가장 상세한 AWS 비용 데이터입니다. Parquet 포맷으로 저장하면 Athena 쿼리 비용도 줄어듭니다. Lambda + EventBridge로 매월 1일 자동 리포트 생성 → SNS 이메일 발송 파이프라인을 구축할 수 있습니다. QuickSight와 연결하면 시각적 대시보드도 만들 수 있습니다.',
  },
"""

TARGET = 'src/web-app.tsx'

ANCHOR = "    explanation: 'ECR 스토리지는 GB당 $0.10/월이 청구됩니다. Lifecycle 정책으로 오래된 이미지를 자동 정리하면 CI/CD 파이프라인에서 이미지가 매일 쌓여도 비용이 통제됩니다. 태그 없는 이미지는 항상 즉시 삭제하는 것이 좋습니다.',\n  },\n};"

REPLACEMENT = "    explanation: 'ECR 스토리지는 GB당 $0.10/월이 청구됩니다. Lifecycle 정책으로 오래된 이미지를 자동 정리하면 CI/CD 파이프라인에서 이미지가 매일 쌓여도 비용이 통제됩니다. 태그 없는 이미지는 항상 즉시 삭제하는 것이 좋습니다.',\n  },\n" + NEW_ENTRIES + "};"

with open(TARGET, 'r', encoding='utf-8') as f:
    src = f.read()

if "id: 'COST-16'" in src:
    print('COST-16 already present - skipping')
else:
    if ANCHOR not in src:
        raise RuntimeError('Anchor not found')
    src = src.replace(ANCHOR, REPLACEMENT, 1)
    with open(TARGET, 'w', encoding='utf-8') as f:
        f.write(src)
    print('Inserted COST 16-30.')

print('Done.')
