# -*- coding: utf-8 -*-
"""Adds PERF challenges 11-30 into existing PERF_CHALLENGES object."""

NEW_ENTRIES = r"""  11: {
    id: 'PERF-11', title: 'PERF-11 Global Accelerator 설정',
    scenario: '서울 리전에 있는 API 서버에 미국/유럽 사용자가 접근할 때 레이턴시가 200ms를 넘습니다. Global Accelerator를 통해 AWS 글로벌 네트워크를 활용해 레이턴시를 50ms 이하로 줄이세요.',
    steps: [
      { title: 'Global Accelerator 생성', desc: 'Accelerator를 생성하세요.',
        hint: 'aws globalaccelerator create-accelerator --name api-accelerator --ip-address-type IPV4 --enabled --region us-west-2',
        answers: ['aws globalaccelerator create-accelerator --name api-accelerator --ip-address-type ipv4 --enabled --region us-west-2'],
        successOutput: ['{"Accelerator": {"AcceleratorArn": "arn:aws:globalaccelerator::123456789012:accelerator/abc123", "Name": "api-accelerator", "IpAddressType": "IPV4", "Enabled": true, "IpSets": [{"IpFamily": "IPv4", "IpAddresses": ["75.2.112.1", "99.83.149.1"]}], "Status": "IN_PROGRESS"}}'] },
      { title: '리스너 생성', desc: 'TCP 443 포트 리스너를 추가하세요.',
        hint: 'aws globalaccelerator create-listener --accelerator-arn arn:aws:globalaccelerator::123456789012:accelerator/abc123 --protocol TCP --port-ranges FromPort=443,ToPort=443 --region us-west-2',
        answers: ['aws globalaccelerator create-listener --accelerator-arn arn:aws:globalaccelerator::123456789012:accelerator/abc123 --protocol tcp --port-ranges fromport=443,toport=443 --region us-west-2'],
        successOutput: ['{"Listener": {"ListenerArn": "arn:aws:globalaccelerator::123456789012:accelerator/abc123/listener/def456", "PortRanges": [{"FromPort": 443, "ToPort": 443}], "Protocol": "TCP"}}'] },
      { title: 'Endpoint Group 추가', desc: 'ap-northeast-2 리전의 ALB를 엔드포인트 그룹으로 추가하세요.',
        hint: 'aws globalaccelerator create-endpoint-group --listener-arn arn:aws:globalaccelerator::123456789012:accelerator/abc123/listener/def456 --endpoint-group-region ap-northeast-2 --endpoint-configurations EndpointId=arn:aws:elasticloadbalancing:ap-northeast-2:123456789012:loadbalancer/app/prod-alb/abc123,Weight=128 --region us-west-2',
        answers: ['aws globalaccelerator create-endpoint-group --listener-arn arn:aws:globalaccelerator::123456789012:accelerator/abc123/listener/def456 --endpoint-group-region ap-northeast-2 --endpoint-configurations endpointid=arn:aws:elasticloadbalancing:ap-northeast-2:123456789012:loadbalancer/app/prod-alb/abc123,weight=128 --region us-west-2'],
        successOutput: ['{"EndpointGroup": {"EndpointGroupArn": "arn:aws:globalaccelerator::123456789012:accelerator/abc123/listener/def456/endpoint-group/ghi789", "EndpointGroupRegion": "ap-northeast-2", "EndpointDescriptions": [{"EndpointId": "arn:aws:elasticloadbalancing:ap-northeast-2:123456789012:loadbalancer/app/prod-alb/abc123", "Weight": 128, "HealthState": "HEALTHY"}]}}'] },
      { title: '레이턴시 개선 확인', desc: 'Global Accelerator 엔드포인트로 레이턴시를 비교하세요.',
        hint: 'aws globalaccelerator describe-accelerator --accelerator-arn arn:aws:globalaccelerator::123456789012:accelerator/abc123 --query "Accelerator.{Status:Status,IpSets:IpSets}" --region us-west-2',
        answers: ['aws globalaccelerator describe-accelerator --accelerator-arn arn:aws:globalaccelerator::123456789012:accelerator/abc123 --query "accelerator.{status:status,ipsets:ipsets}" --region us-west-2'],
        successOutput: ['{"Status": "DEPLOYED", "IpSets": [{"IpFamily": "IPv4", "IpAddresses": ["75.2.112.1", "99.83.149.1"]}]}'] },
    ],
    explanation: 'Global Accelerator는 사용자의 트래픽을 가장 가까운 AWS 엣지 로케이션에서 받아 AWS 글로벌 네트워크로 전달합니다. 퍼블릭 인터넷 경로를 줄여 레이턴시와 패킷 손실을 줄입니다. Anycast IP로 DDoS 공격에도 강합니다.',
  },
  12: {
    id: 'PERF-12', title: 'PERF-12 DynamoDB GSI 생성 및 쿼리 최적화',
    scenario: 'DynamoDB 테이블을 userId(PK)로 조회하는데, email로도 사용자를 찾아야 하는 요구가 생겼습니다. 풀 테이블 스캔 없이 email로 빠르게 조회할 GSI를 추가하세요.',
    steps: [
      { title: '현재 테이블 키 구조 확인', desc: '기존 테이블의 키 스키마와 인덱스를 확인하세요.',
        hint: 'aws dynamodb describe-table --table-name Users --query "Table.{KeySchema:KeySchema,GlobalSecondaryIndexes:GlobalSecondaryIndexes,BillingMode:BillingModeSummary.BillingMode}"',
        answers: ['aws dynamodb describe-table --table-name users --query "table.{keyschema:keyschema,globalsecondaryindexes:globalsecondaryindexes,billingmode:billingmodesummary.billingmode}"'],
        successOutput: ['{"KeySchema": [{"AttributeName": "userId", "KeyType": "HASH"}], "GlobalSecondaryIndexes": null, "BillingMode": "PAY_PER_REQUEST"}'] },
      { title: 'GSI 추가 (email-index)', desc: 'email 속성을 파티션키로 하는 GSI를 추가하세요.',
        hint: 'aws dynamodb update-table --table-name Users --attribute-definitions AttributeName=email,AttributeType=S --global-secondary-index-updates "[{\"Create\":{\"IndexName\":\"email-index\",\"KeySchema\":[{\"AttributeName\":\"email\",\"KeyType\":\"HASH\"}],\"Projection\":{\"ProjectionType\":\"ALL\"}}}]"',
        answers: ['aws dynamodb update-table --table-name users --attribute-definitions attributename=email,attributetype=s --global-secondary-index-updates "[{\"create\":{\"indexname\":\"email-index\",\"keyschema\":[{\"attributename\":\"email\",\"keytype\":\"hash\"}],\"projection\":{\"projectiontype\":\"all\"}}}]"'],
        successOutput: ['{"TableDescription": {"TableName": "Users", "TableStatus": "UPDATING", "GlobalSecondaryIndexes": [{"IndexName": "email-index", "IndexStatus": "CREATING", "KeySchema": [{"AttributeName": "email", "KeyType": "HASH"}]}]}}'] },
      { title: 'GSI 빌드 완료 확인', desc: 'GSI 상태가 ACTIVE로 바뀔 때까지 확인하세요.',
        hint: 'aws dynamodb describe-table --table-name Users --query "Table.GlobalSecondaryIndexes[?IndexName==`email-index`].{Status:IndexStatus,Count:ItemCount}"',
        answers: ['aws dynamodb describe-table --table-name users --query "table.globalsecondaryindexes[?indexname==`email-index`].{status:indexstatus,count:itemcount}"'],
        successOutput: ['[{"Status": "ACTIVE", "Count": 58420}]'] },
      { title: 'GSI로 email 쿼리', desc: 'GSI를 사용해 email로 사용자를 조회하세요.',
        hint: 'aws dynamodb query --table-name Users --index-name email-index --key-condition-expression "email = :e" --expression-attribute-values "{\":e\":{\"S\":\"john@example.com\"}}"',
        answers: ['aws dynamodb query --table-name users --index-name email-index --key-condition-expression "email = :e" --expression-attribute-values "{\":e\":{\"s\":\"john@example.com\"}}"'],
        successOutput: ['{"Items": [{"userId": {"S": "u-001"}, "email": {"S": "john@example.com"}, "name": {"S": "John Doe"}}], "Count": 1, "ScannedCount": 1, "ConsumedCapacity": null}'] },
    ],
    explanation: 'DynamoDB GSI는 원래 테이블과 다른 파티션키/정렬키로 쿼리할 수 있게 해줍니다. Scan 대신 Query + GSI를 사용하면 비용과 성능이 크게 개선됩니다. GSI 생성 후 데이터 복제가 완료되기까지 시간이 걸립니다. ProjectionType은 쿼리 시 필요한 속성만 포함해 RCU를 줄이세요.',
  },
  13: {
    id: 'PERF-13', title: 'PERF-13 SQS + Lambda 배치 처리 최적화',
    scenario: 'SQS 메시지를 Lambda가 1건씩 처리하다보니 Lambda 호출 수가 너무 많고 처리 속도도 느립니다. 배치 크기를 늘리고 SQS 트리거 최적화로 처리량을 높이세요.',
    steps: [
      { title: '현재 이벤트 소스 매핑 확인', desc: 'Lambda의 SQS 이벤트 소스 매핑을 확인하세요.',
        hint: 'aws lambda list-event-source-mappings --function-name order-processor --query "EventSourceMappings[?contains(EventSourceArn,`sqs`)].{UUID:UUID,BatchSize:BatchSize,Queue:EventSourceArn}"',
        answers: ['aws lambda list-event-source-mappings --function-name order-processor --query "eventsourcemappings[?contains(eventsourcearn,`sqs`)].{uuid:uuid,batchsize:batchsize,queue:eventsourcearn}"'],
        successOutput: ['[{"UUID": "abc123-def4-5678-90ab-cdef12345678", "BatchSize": 1, "Queue": "arn:aws:sqs:us-east-1:123456789012:order-queue"}]'] },
      { title: '배치 크기 10으로 증가', desc: '한 번에 10개 메시지를 처리하도록 배치 크기를 수정하세요.',
        hint: 'aws lambda update-event-source-mapping --uuid abc123-def4-5678-90ab-cdef12345678 --batch-size 10 --maximum-batching-window-in-seconds 5',
        answers: ['aws lambda update-event-source-mapping --uuid abc123-def4-5678-90ab-cdef12345678 --batch-size 10 --maximum-batching-window-in-seconds 5'],
        successOutput: ['{"UUID": "abc123-def4-5678-90ab-cdef12345678", "BatchSize": 10, "MaximumBatchingWindowInSeconds": 5, "State": "Updating"}'] },
      { title: 'SQS 큐 속성 확인', desc: '큐의 가시성 타임아웃과 메시지 수를 확인하세요.',
        hint: 'aws sqs get-queue-attributes --queue-url https://sqs.us-east-1.amazonaws.com/123456789012/order-queue --attribute-names VisibilityTimeout ApproximateNumberOfMessages',
        answers: ['aws sqs get-queue-attributes --queue-url https://sqs.us-east-1.amazonaws.com/123456789012/order-queue --attribute-names visibilitytimeout approximatenumberofmessages'],
        successOutput: ['{"Attributes": {"VisibilityTimeout": "30", "ApproximateNumberOfMessages": "1250"}}'] },
      { title: '가시성 타임아웃 조정', desc: 'Lambda 처리 시간보다 6배 긴 180초로 가시성 타임아웃을 설정하세요.',
        hint: 'aws sqs set-queue-attributes --queue-url https://sqs.us-east-1.amazonaws.com/123456789012/order-queue --attributes VisibilityTimeout=180',
        answers: ['aws sqs set-queue-attributes --queue-url https://sqs.us-east-1.amazonaws.com/123456789012/order-queue --attributes visibilitytimeout=180'],
        successOutput: [''] },
      { title: 'Lambda 호출 수 감소 확인', desc: 'Invocations 메트릭으로 Lambda 호출 수가 줄었는지 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/Lambda --metric-name Invocations --dimensions Name=FunctionName,Value=order-processor --start-time 2024-01-01T02:00:00Z --end-time 2024-01-01T03:00:00Z --period 300 --statistics Sum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/lambda --metric-name invocations --dimensions name=functionname,value=order-processor --start-time 2024-01-01t02:00:00z --end-time 2024-01-01t03:00:00z --period 300 --statistics sum'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T02:05:00Z", "Sum": 125.0, "Unit": "Count"}], "Label": "Invocations"}'] },
    ],
    explanation: 'SQS + Lambda 배치 처리 시 BatchSize를 늘리면 Lambda 호출 수가 줄어 비용이 감소합니다. MaximumBatchingWindowInSeconds로 메시지를 모아 더 큰 배치를 만들 수 있습니다. 가시성 타임아웃은 Lambda 최대 실행 시간의 6배로 설정하는 것이 AWS 권장 사항입니다.',
  },
  14: {
    id: 'PERF-14', title: 'PERF-14 Kinesis Data Streams 샤드 확장',
    scenario: '실시간 로그 수집에 Kinesis Data Streams를 사용 중인데 WriteProvisionedThroughputExceeded 오류가 발생합니다. 현재 샤드 2개를 4개로 늘려 처리량을 확보하세요.',
    steps: [
      { title: '현재 스트림 상태 확인', desc: '스트림의 샤드 수와 상태를 확인하세요.',
        hint: 'aws kinesis describe-stream-summary --stream-name app-logs --query "StreamDescriptionSummary.{Shards:OpenShardCount,Status:StreamStatus,RetentionHours:RetentionPeriodHours}"',
        answers: ['aws kinesis describe-stream-summary --stream-name app-logs --query "streamdescriptionsummary.{shards:openshardcount,status:streamstatus,retentionhours:retentionperiodhours}"'],
        successOutput: ['{"Shards": 2, "Status": "ACTIVE", "RetentionHours": 24}'] },
      { title: '스트림 샤드 수 증가', desc: '샤드를 2개에서 4개로 확장하세요.',
        hint: 'aws kinesis update-shard-count --stream-name app-logs --target-shard-count 4 --scaling-type UNIFORM_SCALING',
        answers: ['aws kinesis update-shard-count --stream-name app-logs --target-shard-count 4 --scaling-type uniform_scaling'],
        successOutput: ['{"StreamName": "app-logs", "CurrentShardCount": 2, "TargetShardCount": 4}'] },
      { title: '확장 완료 확인', desc: '샤드가 4개로 늘어났는지 확인하세요.',
        hint: 'aws kinesis describe-stream-summary --stream-name app-logs --query "StreamDescriptionSummary.{Shards:OpenShardCount,Status:StreamStatus}"',
        answers: ['aws kinesis describe-stream-summary --stream-name app-logs --query "streamdescriptionsummary.{shards:openshardcount,status:streamstatus}"'],
        successOutput: ['{"Shards": 4, "Status": "ACTIVE"}'] },
      { title: 'WriteProvisionedThroughputExceeded 알람', desc: '쓰기 병목 재발 감지 알람을 생성하세요.',
        hint: 'aws cloudwatch put-metric-alarm --alarm-name kinesis-write-throttle --metric-name WriteProvisionedThroughputExceeded --namespace AWS/Kinesis --dimensions Name=StreamName,Value=app-logs --statistic Sum --period 60 --threshold 100 --comparison-operator GreaterThanThreshold --evaluation-periods 3 --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-alert',
        answers: ['aws cloudwatch put-metric-alarm --alarm-name kinesis-write-throttle --metric-name writeprovisionedthroughputexceeded --namespace aws/kinesis --dimensions name=streamname,value=app-logs --statistic sum --period 60 --threshold 100 --comparison-operator greaterthanthreshold --evaluation-periods 3 --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-alert'],
        successOutput: [''] },
    ],
    explanation: 'Kinesis 샤드 하나는 쓰기 1MB/s(1000 records/s), 읽기 2MB/s를 지원합니다. 샤드 확장은 UNIFORM_SCALING으로 2배 단위로만 가능합니다. 파티션 키를 다양하게 설계하면 샤드 간 균등 분산이 보장됩니다.',
  },
  15: {
    id: 'PERF-15', title: 'PERF-15 AWS X-Ray 분산 추적 활성화',
    scenario: 'MSA 환경에서 특정 API가 느린데 어느 서비스에서 병목이 생기는지 알 수 없습니다. X-Ray를 활성화해 요청 흐름과 각 구간별 레이턴시를 추적하세요.',
    steps: [
      { title: 'Lambda X-Ray 활성 추적 활성화', desc: 'Lambda 함수에 X-Ray 액티브 추적을 켜세요.',
        hint: 'aws lambda update-function-configuration --function-name api-handler --tracing-config Mode=Active',
        answers: ['aws lambda update-function-configuration --function-name api-handler --tracing-config mode=active'],
        successOutput: ['{"FunctionName": "api-handler", "TracingConfig": {"Mode": "Active"}, "LastUpdateStatus": "Successful"}'] },
      { title: 'API Gateway X-Ray 추적 활성화', desc: 'API Gateway 스테이지에 X-Ray 추적을 활성화하세요.',
        hint: 'aws apigateway update-stage --rest-api-id abc123def4 --stage-name prod --patch-operations op=replace,path=/tracingEnabled,value=true',
        answers: ['aws apigateway update-stage --rest-api-id abc123def4 --stage-name prod --patch-operations op=replace,path=/tracingenabled,value=true'],
        successOutput: ['{"stageName": "prod", "tracingEnabled": true}'] },
      { title: 'X-Ray 서비스 맵 확인', desc: 'X-Ray 서비스 그래프를 조회해 서비스 간 호출 관계를 확인하세요.',
        hint: 'aws xray get-service-graph --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z',
        answers: ['aws xray get-service-graph --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z'],
        successOutput: ['{"Services": [{"Name": "api-handler", "Type": "AWS::Lambda::Function", "ResponseTimeHistogram": [{"Value": 0.5, "Count": 120}]}, {"Name": "prod-mysql", "Type": "AWS::RDS::DBInstance", "ResponseTimeHistogram": [{"Value": 0.3, "Count": 120}]}]}'] },
      { title: '느린 트레이스 조회', desc: '응답 시간 상위 5개 느린 트레이스를 조회하세요.',
        hint: 'aws xray get-traces --trace-ids $(aws xray get-trace-summaries --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --filter-expression "responsetime > 2" --query "TraceSummaries[0:5].Id" --output text)',
        answers: ['aws xray get-traces --trace-ids $(aws xray get-trace-summaries --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --filter-expression "responsetime > 2" --query "tracesummaries[0:5].id" --output text)'],
        successOutput: ['{"Traces": [{"Id": "1-abc12345-def6789012345678", "Duration": 3.42, "Segments": [{"Id": "seg-001", "Document": "{\"name\":\"api-handler\",\"end_time\":3.42}"}]}]}'] },
    ],
    explanation: 'X-Ray는 분산 요청을 추적해 서비스 간 레이턴시와 오류를 시각화합니다. Lambda와 API Gateway 모두 활성화해야 end-to-end 트레이스가 됩니다. filter-expression으로 느린 요청만 필터링해 병목을 빠르게 찾을 수 있습니다.',
  },
  16: {
    id: 'PERF-16', title: 'PERF-16 RDS Performance Insights 활성화',
    scenario: 'RDS 인스턴스의 CPU가 지속적으로 높은데 어떤 쿼리가 원인인지 모릅니다. Performance Insights를 활성화해 상위 SQL 쿼리를 찾고 DB 부하를 분석하세요.',
    steps: [
      { title: 'Performance Insights 활성화', desc: '운영 RDS 인스턴스에 Performance Insights를 켜세요.',
        hint: 'aws rds modify-db-instance --db-instance-identifier prod-mysql --enable-performance-insights --performance-insights-retention-period 7 --apply-immediately',
        answers: ['aws rds modify-db-instance --db-instance-identifier prod-mysql --enable-performance-insights --performance-insights-retention-period 7 --apply-immediately'],
        successOutput: ['{"DBInstance": {"DBInstanceIdentifier": "prod-mysql", "PerformanceInsightsEnabled": true, "PerformanceInsightsRetentionPeriod": 7, "DBInstanceStatus": "modifying"}}'] },
      { title: '상위 SQL 쿼리 조회', desc: 'db.sql.statement 차원으로 가장 부하가 높은 쿼리를 조회하세요.',
        hint: 'aws pi get-resource-metrics --service-type RDS --identifier db-ABCDEFGHIJKLMNOP --metric-queries MetricName=db.load.avg,GroupBy={Group=db.sql,Limit=5} --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period-in-seconds 300',
        answers: ['aws pi get-resource-metrics --service-type rds --identifier db-abcdefghijklmnop --metric-queries metricname=db.load.avg,groupby={group=db.sql,limit=5} --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period-in-seconds 300'],
        successOutput: ['{"MetricList": [{"Key": {"Metric": "db.load.avg", "Dimensions": {"db.sql.statement": "SELECT * FROM orders WHERE created_at > ?"}}, "DataPoints": [{"Timestamp": "2024-01-01T00:05:00Z", "Value": 8.5}]}]}'] },
      { title: 'DB 로드 메트릭 확인', desc: 'DBLoad 메트릭으로 DB 부하 추이를 확인하세요.',
        hint: 'aws pi get-resource-metrics --service-type RDS --identifier db-ABCDEFGHIJKLMNOP --metric-queries MetricName=db.load.avg --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period-in-seconds 60',
        answers: ['aws pi get-resource-metrics --service-type rds --identifier db-abcdefghijklmnop --metric-queries metricname=db.load.avg --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period-in-seconds 60'],
        successOutput: ['{"MetricList": [{"Key": {"Metric": "db.load.avg"}, "DataPoints": [{"Timestamp": "2024-01-01T00:01:00Z", "Value": 12.3}, {"Timestamp": "2024-01-01T00:02:00Z", "Value": 14.1}]}]}'] },
      { title: 'RDS Enhanced Monitoring 활성화', desc: '1초 간격 OS 레벨 모니터링을 활성화하세요.',
        hint: 'aws rds modify-db-instance --db-instance-identifier prod-mysql --monitoring-interval 1 --monitoring-role-arn arn:aws:iam::123456789012:role/rds-monitoring-role --apply-immediately',
        answers: ['aws rds modify-db-instance --db-instance-identifier prod-mysql --monitoring-interval 1 --monitoring-role-arn arn:aws:iam::123456789012:role/rds-monitoring-role --apply-immediately'],
        successOutput: ['{"DBInstance": {"DBInstanceIdentifier": "prod-mysql", "MonitoringInterval": 1, "MonitoringRoleArn": "arn:aws:iam::123456789012:role/rds-monitoring-role"}}'] },
    ],
    explanation: 'Performance Insights는 DB 엔진 레벨의 Wait 이벤트와 상위 SQL을 시각화합니다. db.load.avg가 vCPU 수를 초과하면 병목입니다. Enhanced Monitoring은 OS 레벨(CPU, 메모리, I/O)을 1초 단위로 측정해 Performance Insights와 함께 사용하면 완전한 DB 성능 분석이 가능합니다.',
  },
  17: {
    id: 'PERF-17', title: 'PERF-17 Lambda Provisioned Concurrency',
    scenario: 'Lambda 함수가 콜드 스타트로 인해 첫 요청 응답이 2~3초 걸립니다. 결제 API처럼 응답이 항상 빨라야 하는 함수에 Provisioned Concurrency를 설정해 콜드 스타트를 제거하세요.',
    steps: [
      { title: '현재 콜드 스타트 빈도 확인', desc: 'InitDuration 메트릭으로 콜드 스타트 횟수를 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/Lambda --metric-name InitDuration --dimensions Name=FunctionName,Value=payment-api --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period 300 --statistics SampleCount',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/lambda --metric-name initduration --dimensions name=functionname,value=payment-api --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period 300 --statistics samplecount'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T00:05:00Z", "SampleCount": 45.0, "Unit": "Milliseconds"}], "Label": "InitDuration"}'] },
      { title: '함수 버전 게시', desc: 'Provisioned Concurrency 적용을 위해 함수 버전을 게시하세요.',
        hint: 'aws lambda publish-version --function-name payment-api --description "v1-stable"',
        answers: ['aws lambda publish-version --function-name payment-api --description "v1-stable"'],
        successOutput: ['{"FunctionName": "payment-api", "FunctionArn": "arn:aws:lambda:us-east-1:123456789012:function:payment-api:5", "Version": "5", "Description": "v1-stable"}'] },
      { title: 'Provisioned Concurrency 10개 설정', desc: '버전 5에 10개의 예약 동시성을 설정하세요.',
        hint: 'aws lambda put-provisioned-concurrency-config --function-name payment-api --qualifier 5 --provisioned-concurrent-executions 10',
        answers: ['aws lambda put-provisioned-concurrency-config --function-name payment-api --qualifier 5 --provisioned-concurrent-executions 10'],
        successOutput: ['{"RequestedProvisionedConcurrentExecutions": 10, "AvailableProvisionedConcurrentExecutions": 0, "AllocatedProvisionedConcurrentExecutions": 0, "Status": "IN_PROGRESS"}'] },
      { title: 'Provisioned Concurrency 준비 완료 확인', desc: '설정이 준비됐는지 확인하세요.',
        hint: 'aws lambda get-provisioned-concurrency-config --function-name payment-api --qualifier 5',
        answers: ['aws lambda get-provisioned-concurrency-config --function-name payment-api --qualifier 5'],
        successOutput: ['{"RequestedProvisionedConcurrentExecutions": 10, "AvailableProvisionedConcurrentExecutions": 10, "AllocatedProvisionedConcurrentExecutions": 10, "Status": "READY"}'] },
      { title: '콜드 스타트 제거 확인', desc: 'InitDuration 메트릭이 0에 가까워졌는지 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/Lambda --metric-name InitDuration --dimensions Name=FunctionName,Value=payment-api --start-time 2024-01-01T02:00:00Z --end-time 2024-01-01T03:00:00Z --period 300 --statistics SampleCount',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/lambda --metric-name initduration --dimensions name=functionname,value=payment-api --start-time 2024-01-01t02:00:00z --end-time 2024-01-01t03:00:00z --period 300 --statistics samplecount'],
        successOutput: ['{"Datapoints": [], "Label": "InitDuration"}'] },
    ],
    explanation: 'Provisioned Concurrency는 지정한 수만큼 Lambda 인스턴스를 항상 초기화된 상태로 유지합니다. 버전 또는 Alias에만 설정 가능하며 $LATEST에는 적용되지 않습니다. Application Auto Scaling으로 시간대별 프로비저닝 수를 자동 조정할 수 있습니다.',
  },
  18: {
    id: 'PERF-18', title: 'PERF-18 S3 멀티파트 업로드 최적화',
    scenario: '10GB 이상의 대용량 파일을 S3에 단일 PUT으로 올리다가 네트워크 오류가 나면 처음부터 다시 시작해야 합니다. 멀티파트 업로드를 활용해 병렬 전송과 재시도 효율을 높이세요.',
    steps: [
      { title: '멀티파트 업로드 시작', desc: '멀티파트 업로드를 초기화해 UploadId를 받으세요.',
        hint: 'aws s3api create-multipart-upload --bucket data-lake-bucket --key backups/2024-01-01/dump.tar.gz --storage-class STANDARD',
        answers: ['aws s3api create-multipart-upload --bucket data-lake-bucket --key backups/2024-01-01/dump.tar.gz --storage-class standard'],
        successOutput: ['{"Bucket": "data-lake-bucket", "Key": "backups/2024-01-01/dump.tar.gz", "UploadId": "VXBsb2FkIElEIGZvciA2aWWpbmcncyBteS1tb3ZpZS5tMnRzIHVwbG9hZA"}'] },
      { title: 'Part 업로드', desc: '첫 번째 파트(100MB)를 업로드하세요.',
        hint: 'aws s3api upload-part --bucket data-lake-bucket --key backups/2024-01-01/dump.tar.gz --part-number 1 --body part-001.bin --upload-id VXBsb2FkIElEIGZvciA2aWWpbmcncyBteS1tb3ZpZS5tMnRzIHVwbG9hZA',
        answers: ['aws s3api upload-part --bucket data-lake-bucket --key backups/2024-01-01/dump.tar.gz --part-number 1 --body part-001.bin --upload-id vxbsb2fkieljigzvcia2awwpbmcncybtes1tb3zpzs5tmnrzihvwbg9hza'],
        successOutput: ['{"ETag": "\\"abc123def456789012345678901234ab\\""}'] },
      { title: '멀티파트 업로드 완료', desc: '모든 파트 업로드 후 멀티파트를 완료하세요.',
        hint: 'aws s3api complete-multipart-upload --bucket data-lake-bucket --key backups/2024-01-01/dump.tar.gz --upload-id VXBsb2FkIElEIGZvciA2aWWpbmcncyBteS1tb3ZpZS5tMnRzIHVwbG9hZA --multipart-upload file://parts.json',
        answers: ['aws s3api complete-multipart-upload --bucket data-lake-bucket --key backups/2024-01-01/dump.tar.gz --upload-id vxbsb2fkieljigzvcla2awwpbmcncybtes1tb3zpzs5tmnrzihvwbg9hza --multipart-upload file://parts.json'],
        successOutput: ['{"Location": "https://data-lake-bucket.s3.amazonaws.com/backups/2024-01-01/dump.tar.gz", "Bucket": "data-lake-bucket", "Key": "backups/2024-01-01/dump.tar.gz", "ETag": "\\"def456abc789-100\\""}'] },
      { title: '불완전 멀티파트 정리 규칙', desc: '중단된 업로드가 쌓이지 않도록 7일 후 자동 삭제 규칙을 설정하세요.',
        hint: 'aws s3api put-bucket-lifecycle-configuration --bucket data-lake-bucket --lifecycle-configuration file://lifecycle.json',
        answers: ['aws s3api put-bucket-lifecycle-configuration --bucket data-lake-bucket --lifecycle-configuration file://lifecycle.json'],
        successOutput: [''] },
    ],
    explanation: '멀티파트 업로드는 파일을 여러 파트로 나눠 병렬로 전송합니다. 5MB 이상 파트에 적용되며 최대 10,000 파트까지 가능합니다. 중단 시 해당 파트부터 재시작할 수 있어 대용량 파일에 필수입니다. AbortIncompleteMultipartUpload 라이프사이클 규칙으로 미완성 업로드의 과금을 방지하세요.',
  },
  19: {
    id: 'PERF-19', title: 'PERF-19 EC2 Enhanced Networking (ENA) 확인',
    scenario: '대용량 데이터를 처리하는 EC2 인스턴스 간 네트워크 처리량이 느립니다. ENA(Elastic Network Adapter)가 활성화됐는지 확인하고 인스턴스 타입이 네트워크 최적화를 지원하는지 점검하세요.',
    steps: [
      { title: 'ENA 지원 여부 확인', desc: '현재 인스턴스의 ENA 속성을 확인하세요.',
        hint: 'aws ec2 describe-instances --instance-ids i-0abc1234567890abc --query "Reservations[0].Instances[0].{EnaSupport:EnaSupport,InstanceType:InstanceType,NetworkInterfaces:NetworkInterfaces[0].NetworkInterfaceId}"',
        answers: ['aws ec2 describe-instances --instance-ids i-0abc1234567890abc --query "reservations[0].instances[0].{enasupport:enasupport,instancetype:instancetype,networkinterfaces:networkinterfaces[0].networkinterfaceid}"'],
        successOutput: ['{"EnaSupport": true, "InstanceType": "c5n.2xlarge", "NetworkInterfaces": "eni-0abc123def456789"}'] },
      { title: '네트워크 인터페이스 상세 확인', desc: 'ENI의 네트워크 성능 설정을 확인하세요.',
        hint: 'aws ec2 describe-network-interfaces --network-interface-ids eni-0abc123def456789 --query "NetworkInterfaces[0].{Status:Status,Description:Description,InterfaceType:InterfaceType}"',
        answers: ['aws ec2 describe-network-interfaces --network-interface-ids eni-0abc123def456789 --query "networkinterfaces[0].{status:status,description:description,interfacetype:interfacetype}"'],
        successOutput: ['{"Status": "in-use", "Description": "Primary network interface", "InterfaceType": "interface"}'] },
      { title: '인스턴스 네트워크 처리량 메트릭', desc: 'NetworkIn/NetworkOut 처리량을 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name NetworkOut --dimensions Name=InstanceId,Value=i-0abc1234567890abc --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period 300 --statistics Average',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/ec2 --metric-name networkout --dimensions name=instanceid,value=i-0abc1234567890abc --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period 300 --statistics average'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T00:05:00Z", "Average": 1258291456.0, "Unit": "Bytes"}], "Label": "NetworkOut"}'] },
      { title: '네트워크 최적화 인스턴스로 변경', desc: '인스턴스를 중지하고 c5n.4xlarge(25Gbps)로 변경하세요.',
        hint: 'aws ec2 modify-instance-attribute --instance-id i-0abc1234567890abc --instance-type Value=c5n.4xlarge',
        answers: ['aws ec2 modify-instance-attribute --instance-id i-0abc1234567890abc --instance-type value=c5n.4xlarge'],
        successOutput: [''] },
    ],
    explanation: 'ENA는 고성능 네트워킹을 위한 네트워크 인터페이스로 최대 100Gbps를 지원합니다. c5n, m5n, r5n 같은 네트워크 최적화 인스턴스 패밀리는 더 높은 네트워크 대역폭을 제공합니다. 인스턴스 간 대용량 데이터 전송에는 Placement Group(Cluster)과 함께 사용하면 더욱 효과적입니다.',
  },
  20: {
    id: 'PERF-20', title: 'PERF-20 ECS Fargate CPU/메모리 튜닝',
    scenario: 'Fargate 태스크가 512CPU / 1GB 메모리로 실행되는데 처리 지연이 발생합니다. CloudWatch 메트릭으로 리소스 사용량을 분석하고 태스크 정의를 최적화하세요.',
    steps: [
      { title: '현재 태스크 정의 확인', desc: '현재 태스크 정의의 CPU/메모리 설정을 확인하세요.',
        hint: 'aws ecs describe-task-definition --task-definition api-task --query "taskDefinition.{CPU:cpu,Memory:memory,Containers:containerDefinitions[0].{Name:name,CPU:cpu,Memory:memory}}"',
        answers: ['aws ecs describe-task-definition --task-definition api-task --query "taskdefinition.{cpu:cpu,memory:memory,containers:containerdefinitions[0].{name:name,cpu:cpu,memory:memory}}"'],
        successOutput: ['{"CPU": "512", "Memory": "1024", "Containers": {"Name": "api-container", "CPU": 512, "Memory": 1024}}'] },
      { title: 'Fargate 리소스 사용률 확인', desc: 'ECS 서비스의 CPU/메모리 사용률을 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/ECS --metric-name CPUUtilization --dimensions Name=ServiceName,Value=api-service Name=ClusterName,Value=prod-cluster --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period 300 --statistics Average Maximum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/ecs --metric-name cpuutilization --dimensions name=servicename,value=api-service name=clustername,value=prod-cluster --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period 300 --statistics average maximum'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T00:05:00Z", "Average": 92.5, "Maximum": 98.1, "Unit": "Percent"}], "Label": "CPUUtilization"}'] },
      { title: '새 태스크 정의 등록 (CPU 2배)', desc: 'CPU 1024, 메모리 2048로 업그레이드된 태스크 정의를 등록하세요.',
        hint: 'aws ecs register-task-definition --family api-task --cpu 1024 --memory 2048 --network-mode awsvpc --requires-compatibilities FARGATE --container-definitions "[{\"name\":\"api-container\",\"image\":\"123456789012.dkr.ecr.us-east-1.amazonaws.com/api:latest\",\"cpu\":1024,\"memory\":2048,\"portMappings\":[{\"containerPort\":8080}]}]" --execution-role-arn arn:aws:iam::123456789012:role/ecsTaskExecutionRole',
        answers: ['aws ecs register-task-definition --family api-task --cpu 1024 --memory 2048 --network-mode awsvpc --requires-compatibilities fargate --container-definitions "[{\"name\":\"api-container\",\"image\":\"123456789012.dkr.ecr.us-east-1.amazonaws.com/api:latest\",\"cpu\":1024,\"memory\":2048,\"portmappings\":[{\"containerport\":8080}]}]" --execution-role-arn arn:aws:iam::123456789012:role/ecstaskexecutionrole'],
        successOutput: ['{"taskDefinition": {"family": "api-task", "revision": 3, "cpu": "1024", "memory": "2048", "status": "ACTIVE"}}'] },
      { title: 'ECS 서비스 업데이트', desc: '새 태스크 정의로 서비스를 업데이트하세요.',
        hint: 'aws ecs update-service --cluster prod-cluster --service api-service --task-definition api-task:3 --force-new-deployment',
        answers: ['aws ecs update-service --cluster prod-cluster --service api-service --task-definition api-task:3 --force-new-deployment'],
        successOutput: ['{"service": {"serviceName": "api-service", "taskDefinition": "arn:aws:ecs:us-east-1:123456789012:task-definition/api-task:3", "desiredCount": 2, "runningCount": 2, "status": "ACTIVE"}}'] },
    ],
    explanation: 'Fargate CPU는 256~16384vCPU 단위로 설정하며 메모리와 유효한 조합이 있습니다. CPUUtilization이 지속적으로 80% 이상이면 CPU 병목입니다. ECS Service Auto Scaling을 함께 설정해 부하에 따라 태스크 수를 자동으로 조정하세요.',
  },
  21: {
    id: 'PERF-21', title: 'PERF-21 CloudFront 경로별 캐시 동작 설정',
    scenario: 'CloudFront 배포에서 정적 파일(/static/*)은 TTL을 24시간, API 응답(/api/*)은 캐싱하지 않도록 경로별로 다른 캐시 동작을 설정하세요.',
    steps: [
      { title: '현재 배포 캐시 동작 확인', desc: '기존 CloudFront 배포의 캐시 동작을 확인하세요.',
        hint: 'aws cloudfront get-distribution-config --id E2QWRTZXMP65OJ --query "DistributionConfig.{DefaultBehavior:DefaultCacheBehavior.ViewerProtocolPolicy,CacheBehaviors:CacheBehaviors.Quantity}"',
        answers: ['aws cloudfront get-distribution-config --id e2qwrtzxmp65oj --query "distributionconfig.{defaultbehavior:defaultcachebehavior.viewerprotocolpolicy,cachebehaviors:cachebehaviors.quantity}"'],
        successOutput: ['{"DefaultBehavior": "redirect-to-https", "CacheBehaviors": 0}'] },
      { title: 'API 비캐시 정책 생성', desc: '/api/* 경로에 사용할 캐시 비활성화 정책을 생성하세요.',
        hint: 'aws cloudfront create-cache-policy --cache-policy-config Name=no-cache-api,DefaultTTL=0,MaxTTL=0,MinTTL=0,ParametersInCacheKeyAndForwardedToOrigin={EnableAcceptEncodingGzip=false,HeadersConfig={HeaderBehavior=none},CookiesConfig={CookieBehavior=none},QueryStringsConfig={QueryStringBehavior=all}}',
        answers: ['aws cloudfront create-cache-policy --cache-policy-config name=no-cache-api,defaultttl=0,maxttl=0,minttl=0,parametersincachekeyandforwardedtoorigin={enableacceptencodinggzip=false,headersconfig={headerbehavior=none},cookiesconfig={cookiebehavior=none},querystringsconfig={querystringbehavior=all}}'],
        successOutput: ['{"CachePolicy": {"Id": "no-cache-policy-id-001", "CachePolicyConfig": {"Name": "no-cache-api", "DefaultTTL": 0, "MaxTTL": 0}}}'] },
      { title: '배포에 경로별 동작 추가', desc: '/api/* 경로에 비캐시, /static/* 경로에 장기 캐시를 설정하세요.',
        hint: 'aws cloudfront update-distribution --id E2QWRTZXMP65OJ --distribution-config file://cf-updated-config.json --if-match E1PA6795UKMFR9',
        answers: ['aws cloudfront update-distribution --id e2qwrtzxmp65oj --distribution-config file://cf-updated-config.json --if-match e1pa6795ukmfr9'],
        successOutput: ['{"Distribution": {"Id": "E2QWRTZXMP65OJ", "Status": "InProgress", "DistributionConfig": {"CacheBehaviors": {"Quantity": 2}}}}'] },
      { title: '캐시 동작 적용 확인', desc: '배포가 완료됐는지 확인하세요.',
        hint: 'aws cloudfront wait distribution-deployed --id E2QWRTZXMP65OJ',
        answers: ['aws cloudfront wait distribution-deployed --id e2qwrtzxmp65oj'],
        successOutput: ['(no output - wait completes when deployed)'] },
    ],
    explanation: 'CloudFront 경로 패턴 우선순위는 특정 경로(/api/*)가 기본 동작(*)보다 먼저 평가됩니다. API 응답은 TTL=0으로 설정해 항상 오리진에서 가져오고 정적 자산은 긴 TTL로 캐싱합니다. CacheBehaviors 순서가 중요합니다: 더 구체적인 경로를 먼저 배치하세요.',
  },
  22: {
    id: 'PERF-22', title: 'PERF-22 ElastiCache Redis 클러스터 모드 활성화',
    scenario: '단일 Redis 노드가 메모리 부족과 단일 장애점 문제를 가집니다. Redis 클러스터 모드를 활성화해 데이터를 여러 샤드로 분산하고 고가용성을 확보하세요.',
    steps: [
      { title: '클러스터 모드 활성화 복제 그룹 생성', desc: '3개 샤드, 각 1개 복제본으로 Redis 클러스터를 생성하세요.',
        hint: 'aws elasticache create-replication-group --replication-group-id prod-redis-cluster --replication-group-description "Production Redis Cluster" --num-node-groups 3 --replicas-per-node-group 1 --cache-node-type cache.r6g.large --engine redis --engine-version 7.0 --cache-subnet-group-name redis-subnet-group --security-group-ids sg-0abc123def456789 --automatic-failover-enabled',
        answers: ['aws elasticache create-replication-group --replication-group-id prod-redis-cluster --replication-group-description "production redis cluster" --num-node-groups 3 --replicas-per-node-group 1 --cache-node-type cache.r6g.large --engine redis --engine-version 7.0 --cache-subnet-group-name redis-subnet-group --security-group-ids sg-0abc123def456789 --automatic-failover-enabled'],
        successOutput: ['{"ReplicationGroup": {"ReplicationGroupId": "prod-redis-cluster", "Status": "creating", "NodeGroups": [{"NodeGroupId": "0001", "Status": "creating"}, {"NodeGroupId": "0002", "Status": "creating"}, {"NodeGroupId": "0003", "Status": "creating"}], "AutomaticFailover": "enabled"}}'] },
      { title: '클러스터 상태 확인', desc: '복제 그룹이 available 상태인지 확인하세요.',
        hint: 'aws elasticache describe-replication-groups --replication-group-id prod-redis-cluster --query "ReplicationGroups[0].{Status:Status,NodeGroups:NodeGroups[*].Status}"',
        answers: ['aws elasticache describe-replication-groups --replication-group-id prod-redis-cluster --query "replicationgroups[0].{status:status,nodegroups:nodegroups[*].status}"'],
        successOutput: ['{"Status": "available", "NodeGroups": ["available", "available", "available"]}'] },
      { title: '클러스터 구성 엔드포인트 확인', desc: '클러스터 모드에서는 Configuration Endpoint를 사용해야 합니다.',
        hint: 'aws elasticache describe-replication-groups --replication-group-id prod-redis-cluster --query "ReplicationGroups[0].ConfigurationEndpoint"',
        answers: ['aws elasticache describe-replication-groups --replication-group-id prod-redis-cluster --query "replicationgroups[0].configurationendpoint"'],
        successOutput: ['{"Address": "prod-redis-cluster.abc123.clustercfg.use1.cache.amazonaws.com", "Port": 6379}'] },
      { title: '메모리 사용률 모니터링', desc: '각 샤드의 DatabaseMemoryUsagePercentage를 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/ElastiCache --metric-name DatabaseMemoryUsagePercentage --dimensions Name=ReplicationGroupId,Value=prod-redis-cluster --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period 300 --statistics Maximum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/elasticache --metric-name databasememoryusagepercentage --dimensions name=replicationgroupid,value=prod-redis-cluster --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period 300 --statistics maximum'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T00:05:00Z", "Maximum": 31.2, "Unit": "Percent"}], "Label": "DatabaseMemoryUsagePercentage"}'] },
    ],
    explanation: 'Redis 클러스터 모드는 데이터를 최대 500개 샤드에 분산합니다. 클라이언트는 Configuration Endpoint를 사용해야 합니다. automatic-failover-enabled를 설정하면 프라이머리 노드 장애 시 레플리카가 자동으로 프라이머리로 승격됩니다.',
  },
  23: {
    id: 'PERF-23', title: 'PERF-23 Aurora Read Replica Auto Scaling',
    scenario: 'Aurora 클러스터의 읽기 부하가 낮과 밤의 차이가 큽니다. 낮에는 Read Replica가 5개 필요하고 밤에는 1개면 됩니다. Aurora Auto Scaling을 설정해 자동으로 Replica 수를 조정하세요.',
    steps: [
      { title: '현재 Aurora 클러스터 확인', desc: '클러스터의 현재 멤버와 상태를 확인하세요.',
        hint: 'aws rds describe-db-clusters --db-cluster-identifier prod-aurora --query "DBClusters[0].{Members:DBClusterMembers[*].{Id:DBInstanceIdentifier,Writer:IsClusterWriter},Engine:Engine}"',
        answers: ['aws rds describe-db-clusters --db-cluster-identifier prod-aurora --query "dbclusters[0].{members:dbclustermembers[*].{id:dbinstanceidentifier,writer:isclusterwriter},engine:engine}"'],
        successOutput: ['{"Members": [{"Id": "prod-aurora-instance-1", "Writer": true}], "Engine": "aurora-mysql"}'] },
      { title: 'Aurora Auto Scaling 정책 등록', desc: 'Aurora 클러스터에 Auto Scaling 정책을 등록하세요.',
        hint: 'aws application-autoscaling register-scalable-target --service-namespace rds --resource-id cluster:prod-aurora --scalable-dimension rds:cluster:ReadReplicaCount --min-capacity 1 --max-capacity 5',
        answers: ['aws application-autoscaling register-scalable-target --service-namespace rds --resource-id cluster:prod-aurora --scalable-dimension rds:cluster:readreplicacount --min-capacity 1 --max-capacity 5'],
        successOutput: [''] },
      { title: 'CPU 기반 스케일링 정책 생성', desc: 'CPU 70% 기준으로 Replica를 자동 조정하는 정책을 만드세요.',
        hint: 'aws application-autoscaling put-scaling-policy --service-namespace rds --resource-id cluster:prod-aurora --scalable-dimension rds:cluster:ReadReplicaCount --policy-name aurora-cpu-policy --policy-type TargetTrackingScaling --target-tracking-scaling-policy-configuration PredefinedMetricSpecification={PredefinedMetricType=RDSReaderAverageCPUUtilization},TargetValue=70.0,ScaleInCooldown=300,ScaleOutCooldown=300',
        answers: ['aws application-autoscaling put-scaling-policy --service-namespace rds --resource-id cluster:prod-aurora --scalable-dimension rds:cluster:readreplicacount --policy-name aurora-cpu-policy --policy-type targettrackingscaling --target-tracking-scaling-policy-configuration predefinedmetricspecification={predefinedmetrictype=rdsreaderaveragecpuutilization},targetvalue=70.0,scaleincooldown=300,scaleoutcooldown=300'],
        successOutput: ['{"PolicyARN": "arn:aws:autoscaling:us-east-1:123456789012:scalingPolicy:aurora-cpu-policy", "Alarms": [{"AlarmName": "TargetTracking-prod-aurora-AlarmHigh"}]}'] },
      { title: 'Auto Scaling 정책 확인', desc: '등록된 정책을 확인하세요.',
        hint: 'aws application-autoscaling describe-scaling-policies --service-namespace rds --resource-id cluster:prod-aurora',
        answers: ['aws application-autoscaling describe-scaling-policies --service-namespace rds --resource-id cluster:prod-aurora'],
        successOutput: ['{"ScalingPolicies": [{"PolicyName": "aurora-cpu-policy", "PolicyType": "TargetTrackingScaling", "TargetTrackingScalingPolicyConfiguration": {"TargetValue": 70.0, "PredefinedMetricSpecification": {"PredefinedMetricType": "RDSReaderAverageCPUUtilization"}}}]}'] },
    ],
    explanation: 'Aurora Auto Scaling은 Application Auto Scaling을 통해 Reader 인스턴스 수를 자동 조정합니다. ScaleIn/ScaleOut 쿨다운을 설정해 잦은 스케일링을 방지하세요. Aurora Serverless v2를 사용하면 개별 인스턴스 스케일링 대신 ACU(Aurora Capacity Unit) 단위로 더 세밀하게 자동 조정됩니다.',
  },
  24: {
    id: 'PERF-24', title: 'PERF-24 DynamoDB 용량 모드 전환 (On-Demand)',
    scenario: '이벤트 기간에만 DynamoDB 트래픽이 폭발적으로 증가합니다. 평소에는 Provisioned 모드가 저렴하지만 이벤트 때는 항상 ProvisionedThroughputExceeded 오류가 납니다. On-Demand 모드로 전환해 자동 스케일링을 활용하세요.',
    steps: [
      { title: '현재 용량 모드 및 설정 확인', desc: '테이블의 현재 처리 용량 설정을 확인하세요.',
        hint: 'aws dynamodb describe-table --table-name flash-sale --query "Table.{BillingMode:BillingModeSummary.BillingMode,ReadCapacity:ProvisionedThroughput.ReadCapacityUnits,WriteCapacity:ProvisionedThroughput.WriteCapacityUnits}"',
        answers: ['aws dynamodb describe-table --table-name flash-sale --query "table.{billingmode:billingmodesummary.billingmode,readcapacity:provisionedthroughput.readcapacityunits,writecapacity:provisionedthroughput.writecapacityunits}"'],
        successOutput: ['{"BillingMode": "PROVISIONED", "ReadCapacity": 100, "WriteCapacity": 50}'] },
      { title: 'On-Demand 모드로 전환', desc: '테이블을 PAY_PER_REQUEST 모드로 변경하세요.',
        hint: 'aws dynamodb update-table --table-name flash-sale --billing-mode PAY_PER_REQUEST',
        answers: ['aws dynamodb update-table --table-name flash-sale --billing-mode pay_per_request'],
        successOutput: ['{"TableDescription": {"TableName": "flash-sale", "BillingModeSummary": {"BillingMode": "PAY_PER_REQUEST"}, "TableStatus": "UPDATING"}}'] },
      { title: '전환 완료 확인', desc: '테이블 상태가 ACTIVE로 돌아왔는지 확인하세요.',
        hint: 'aws dynamodb describe-table --table-name flash-sale --query "Table.{Status:TableStatus,BillingMode:BillingModeSummary.BillingMode}"',
        answers: ['aws dynamodb describe-table --table-name flash-sale --query "table.{status:tablestatus,billingmode:billingmodesummary.billingmode}"'],
        successOutput: ['{"Status": "ACTIVE", "BillingMode": "PAY_PER_REQUEST"}'] },
      { title: 'ConsumedReadCapacityUnits 모니터링', desc: '이벤트 중 실제 소비된 RCU/WCU를 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/DynamoDB --metric-name ConsumedWriteCapacityUnits --dimensions Name=TableName,Value=flash-sale --start-time 2024-01-01T12:00:00Z --end-time 2024-01-01T13:00:00Z --period 60 --statistics Sum',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/dynamodb --metric-name consumedwritecapacityunits --dimensions name=tablename,value=flash-sale --start-time 2024-01-01t12:00:00z --end-time 2024-01-01t13:00:00z --period 60 --statistics sum'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T12:01:00Z", "Sum": 45200.0, "Unit": "Count"}], "Label": "ConsumedWriteCapacityUnits"}'] },
    ],
    explanation: 'On-Demand 모드는 트래픽에 맞게 자동 스케일링되어 ProvisionedThroughputExceeded 오류가 없습니다. 단, 비용은 요청당 과금이라 예측 가능한 안정적 트래픽에는 Provisioned + Auto Scaling이 더 저렴합니다. 모드 전환은 24시간에 한 번만 가능합니다.',
  },
  25: {
    id: 'PERF-25', title: 'PERF-25 EventBridge + Lambda 비동기 처리',
    scenario: '사용자 주문 완료 후 재고 업데이트, 이메일 발송, 통계 기록을 동기로 처리하다 보니 API 응답이 3초 이상 걸립니다. EventBridge로 이벤트를 발행하고 각 처리를 비동기로 분리하세요.',
    steps: [
      { title: 'EventBridge 이벤트 버스 생성', desc: '커스텀 이벤트 버스를 생성하세요.',
        hint: 'aws events create-event-bus --name order-events',
        answers: ['aws events create-event-bus --name order-events'],
        successOutput: ['{"EventBusArn": "arn:aws:events:us-east-1:123456789012:event-bus/order-events"}'] },
      { title: '이벤트 규칙 생성', desc: 'OrderCompleted 이벤트를 처리할 규칙을 만드세요.',
        hint: 'aws events put-rule --name order-completed-rule --event-bus-name order-events --event-pattern "{\"source\":[\"com.myapp.orders\"],\"detail-type\":[\"OrderCompleted\"]}" --state ENABLED',
        answers: ['aws events put-rule --name order-completed-rule --event-bus-name order-events --event-pattern "{\"source\":[\"com.myapp.orders\"],\"detail-type\":[\"ordercompleted\"]}" --state enabled'],
        successOutput: ['{"RuleArn": "arn:aws:events:us-east-1:123456789012:rule/order-events/order-completed-rule"}'] },
      { title: 'Lambda 타겟 등록', desc: '재고 업데이트, 이메일 발송 Lambda를 타겟으로 등록하세요.',
        hint: 'aws events put-targets --rule order-completed-rule --event-bus-name order-events --targets Id=inventory-lambda,Arn=arn:aws:lambda:us-east-1:123456789012:function:update-inventory Id=email-lambda,Arn=arn:aws:lambda:us-east-1:123456789012:function:send-email',
        answers: ['aws events put-targets --rule order-completed-rule --event-bus-name order-events --targets id=inventory-lambda,arn=arn:aws:lambda:us-east-1:123456789012:function:update-inventory id=email-lambda,arn=arn:aws:lambda:us-east-1:123456789012:function:send-email'],
        successOutput: ['{"FailedEntryCount": 0, "FailedEntries": []}'] },
      { title: '테스트 이벤트 발행', desc: '테스트 주문 완료 이벤트를 발행하세요.',
        hint: 'aws events put-events --entries Source=com.myapp.orders,DetailType=OrderCompleted,Detail="{\"orderId\":\"ORD-12345\",\"userId\":\"u-001\",\"amount\":59900}",EventBusName=order-events',
        answers: ['aws events put-events --entries source=com.myapp.orders,detailtype=ordercompleted,detail="{\"orderid\":\"ord-12345\",\"userid\":\"u-001\",\"amount\":59900}",eventbusname=order-events'],
        successOutput: ['{"FailedEntryCount": 0, "Entries": [{"EventId": "abc123de-f456-7890-abcd-ef1234567890"}]}'] },
    ],
    explanation: 'EventBridge를 통한 이벤트 기반 아키텍처는 서비스 간 결합도를 낮춥니다. 주문 API는 EventBridge에 이벤트만 발행하고 즉시 응답하므로 API 응답 시간이 50ms 이하로 줄어듭니다. 각 소비자(Lambda)는 독립적으로 실패하고 DLQ(Dead Letter Queue)로 실패 이벤트를 관리하세요.',
  },
  26: {
    id: 'PERF-26', title: 'PERF-26 SQS 메시지 우선순위 처리',
    scenario: '하나의 SQS 큐에서 VIP 주문과 일반 주문이 섞여 처리됩니다. VIP 주문이 더 빨리 처리되어야 하는데 현재 구조로는 불가능합니다. 별도 큐 전략으로 우선순위 처리를 구현하세요.',
    steps: [
      { title: 'VIP 전용 SQS 큐 생성', desc: 'VIP 주문 전용 큐를 생성하세요.',
        hint: 'aws sqs create-queue --queue-name vip-orders.fifo --attributes FifoQueue=true,ContentBasedDeduplication=true,VisibilityTimeout=60,MessageRetentionPeriod=86400',
        answers: ['aws sqs create-queue --queue-name vip-orders.fifo --attributes fifoqueue=true,contentbaseddeduplication=true,visibilitytimeout=60,messageretentionperiod=86400'],
        successOutput: ['{"QueueUrl": "https://sqs.us-east-1.amazonaws.com/123456789012/vip-orders.fifo"}'] },
      { title: '일반 주문 큐 생성', desc: '일반 주문용 큐를 생성하세요.',
        hint: 'aws sqs create-queue --queue-name standard-orders.fifo --attributes FifoQueue=true,ContentBasedDeduplication=true,VisibilityTimeout=60',
        answers: ['aws sqs create-queue --queue-name standard-orders.fifo --attributes fifoqueue=true,contentbaseddeduplication=true,visibilitytimeout=60'],
        successOutput: ['{"QueueUrl": "https://sqs.us-east-1.amazonaws.com/123456789012/standard-orders.fifo"}'] },
      { title: 'Lambda에 VIP 큐 이벤트 소스 연결', desc: 'VIP 큐 처리 Lambda를 배치 크기 1로 설정하세요.',
        hint: 'aws lambda create-event-source-mapping --function-name order-processor --event-source-arn arn:aws:sqs:us-east-1:123456789012:vip-orders.fifo --batch-size 1 --enabled',
        answers: ['aws lambda create-event-source-mapping --function-name order-processor --event-source-arn arn:aws:sqs:us-east-1:123456789012:vip-orders.fifo --batch-size 1 --enabled'],
        successOutput: ['{"UUID": "vip-uuid-001", "BatchSize": 1, "EventSourceArn": "arn:aws:sqs:us-east-1:123456789012:vip-orders.fifo", "State": "Creating"}'] },
      { title: 'VIP 큐 메시지 수 확인', desc: 'VIP 큐의 메시지 수와 처리 상태를 확인하세요.',
        hint: 'aws sqs get-queue-attributes --queue-url https://sqs.us-east-1.amazonaws.com/123456789012/vip-orders.fifo --attribute-names ApproximateNumberOfMessages ApproximateNumberOfMessagesNotVisible',
        answers: ['aws sqs get-queue-attributes --queue-url https://sqs.us-east-1.amazonaws.com/123456789012/vip-orders.fifo --attribute-names approximatenumberofmessages approximatenumberofmessagesnotvisible'],
        successOutput: ['{"Attributes": {"ApproximateNumberOfMessages": "0", "ApproximateNumberOfMessagesNotVisible": "3"}}'] },
    ],
    explanation: 'SQS는 기본적으로 우선순위 큐를 지원하지 않습니다. 별도 큐를 만들고 VIP 처리 Lambda에 더 많은 동시성을 부여하거나 먼저 폴링하도록 구현합니다. FIFO 큐는 메시지 순서를 보장하며 중복 방지 기능도 제공합니다.',
  },
  27: {
    id: 'PERF-27', title: 'PERF-27 Kinesis Enhanced Fan-Out 소비자',
    scenario: 'Kinesis 스트림 소비자가 여러 개인데 모든 소비자가 초당 2MB 공유 읽기 처리량을 나눠 쓰다 보니 지연이 발생합니다. Enhanced Fan-Out으로 각 소비자에게 전용 2MB/s 대역폭을 제공하세요.',
    steps: [
      { title: '현재 스트림 소비자 확인', desc: '스트림에 등록된 소비자 목록을 확인하세요.',
        hint: 'aws kinesis list-stream-consumers --stream-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events',
        answers: ['aws kinesis list-stream-consumers --stream-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events'],
        successOutput: ['{"Consumers": [{"ConsumerName": "analytics-consumer", "ConsumerARN": "arn:aws:kinesis:us-east-1:123456789012:stream/app-events/consumer/analytics-consumer:1234567890", "ConsumerStatus": "ACTIVE"}]}'] },
      { title: 'Enhanced Fan-Out 소비자 등록', desc: '알림 서비스용 소비자를 Enhanced Fan-Out으로 등록하세요.',
        hint: 'aws kinesis register-stream-consumer --stream-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events --consumer-name notification-consumer',
        answers: ['aws kinesis register-stream-consumer --stream-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events --consumer-name notification-consumer'],
        successOutput: ['{"Consumer": {"ConsumerName": "notification-consumer", "ConsumerARN": "arn:aws:kinesis:us-east-1:123456789012:stream/app-events/consumer/notification-consumer:1234567891", "ConsumerStatus": "CREATING", "ConsumerCreationTimestamp": "2024-01-01T00:00:00Z"}}'] },
      { title: '소비자 활성화 확인', desc: '소비자 상태가 ACTIVE가 됐는지 확인하세요.',
        hint: 'aws kinesis describe-stream-consumer --stream-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events --consumer-name notification-consumer',
        answers: ['aws kinesis describe-stream-consumer --stream-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events --consumer-name notification-consumer'],
        successOutput: ['{"ConsumerDescription": {"ConsumerName": "notification-consumer", "ConsumerStatus": "ACTIVE", "ConsumerARN": "arn:aws:kinesis:us-east-1:123456789012:stream/app-events/consumer/notification-consumer:1234567891"}}'] },
      { title: 'Lambda Kinesis 트리거에 소비자 ARN 연결', desc: 'Lambda 이벤트 소스를 Enhanced Fan-Out 소비자로 설정하세요.',
        hint: 'aws lambda create-event-source-mapping --function-name notification-processor --event-source-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events/consumer/notification-consumer:1234567891 --batch-size 100 --starting-position LATEST',
        answers: ['aws lambda create-event-source-mapping --function-name notification-processor --event-source-arn arn:aws:kinesis:us-east-1:123456789012:stream/app-events/consumer/notification-consumer:1234567891 --batch-size 100 --starting-position latest'],
        successOutput: ['{"UUID": "efo-uuid-001", "BatchSize": 100, "EventSourceArn": "arn:aws:kinesis:us-east-1:123456789012:stream/app-events/consumer/notification-consumer:1234567891", "State": "Creating"}'] },
    ],
    explanation: 'Enhanced Fan-Out은 각 소비자에게 샤드당 2MB/s의 전용 읽기 처리량을 제공합니다. 기본 GetRecords 방식은 모든 소비자가 처리량을 공유하지만 Enhanced Fan-Out은 서버 측 Push 방식으로 레이턴시도 200ms에서 70ms로 줄어듭니다. 단, 소비자당 추가 비용이 발생합니다.',
  },
  28: {
    id: 'PERF-28', title: 'PERF-28 EC2 Cluster Placement Group',
    scenario: 'HPC(고성능 컴퓨팅) 워크로드에서 EC2 인스턴스 간 네트워크 지연이 문제입니다. Cluster Placement Group으로 인스턴스를 물리적으로 가까이 배치해 최저 레이턴시를 달성하세요.',
    steps: [
      { title: 'Cluster Placement Group 생성', desc: 'cluster 전략으로 Placement Group을 생성하세요.',
        hint: 'aws ec2 create-placement-group --group-name hpc-cluster --strategy cluster',
        answers: ['aws ec2 create-placement-group --group-name hpc-cluster --strategy cluster'],
        successOutput: ['{"PlacementGroup": {"GroupName": "hpc-cluster", "State": "available", "Strategy": "cluster", "GroupId": "pg-0abc1234567890abc"}}'] },
      { title: 'Placement Group에 인스턴스 시작', desc: 'c5n.xlarge 인스턴스 4대를 Placement Group 내에 시작하세요.',
        hint: 'aws ec2 run-instances --image-id ami-0abc123def456789 --instance-type c5n.xlarge --count 4 --placement GroupName=hpc-cluster --subnet-id subnet-0abc123 --key-name my-keypair',
        answers: ['aws ec2 run-instances --image-id ami-0abc123def456789 --instance-type c5n.xlarge --count 4 --placement groupname=hpc-cluster --subnet-id subnet-0abc123 --key-name my-keypair'],
        successOutput: ['{"Instances": [{"InstanceId": "i-0pg1", "Placement": {"GroupName": "hpc-cluster"}}, {"InstanceId": "i-0pg2", "Placement": {"GroupName": "hpc-cluster"}}, {"InstanceId": "i-0pg3", "Placement": {"GroupName": "hpc-cluster"}}, {"InstanceId": "i-0pg4", "Placement": {"GroupName": "hpc-cluster"}}]}'] },
      { title: '인스턴스 Placement 확인', desc: 'Placement Group에 속한 인스턴스를 확인하세요.',
        hint: 'aws ec2 describe-instances --filters Name=placement-group-name,Values=hpc-cluster --query "Reservations[*].Instances[*].{Id:InstanceId,State:State.Name,AZ:Placement.AvailabilityZone}"',
        answers: ['aws ec2 describe-instances --filters name=placement-group-name,values=hpc-cluster --query "reservations[*].instances[*].{id:instanceid,state:state.name,az:placement.availabilityzone}"'],
        successOutput: ['[[{"Id": "i-0pg1", "State": "running", "AZ": "us-east-1a"}, {"Id": "i-0pg2", "State": "running", "AZ": "us-east-1a"}, {"Id": "i-0pg3", "State": "running", "AZ": "us-east-1a"}, {"Id": "i-0pg4", "State": "running", "AZ": "us-east-1a"}]]'] },
      { title: '네트워크 레이턴시 확인', desc: 'Placement Group 내 인스턴스 간 NetworkIn 메트릭을 비교하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name NetworkIn --dimensions Name=InstanceId,Value=i-0pg1 --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period 300 --statistics Average',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/ec2 --metric-name networkin --dimensions name=instanceid,value=i-0pg1 --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period 300 --statistics average'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T00:05:00Z", "Average": 9875000000.0, "Unit": "Bytes"}], "Label": "NetworkIn"}'] },
    ],
    explanation: 'Cluster Placement Group은 인스턴스를 같은 AZ의 물리 서버 근처에 배치해 10Gbps 이상의 낮은 레이턴시 네트워크를 제공합니다. HPC, 빅데이터, ML 학습에 적합합니다. 단, 단일 AZ에 제한되므로 가용성이 낮고 인스턴스 시작 실패 가능성이 높습니다(insufficient capacity).',
  },
  29: {
    id: 'PERF-29', title: 'PERF-29 Network Load Balancer 고처리량 설정',
    scenario: 'TCP 연결이 초당 수만 개 발생하는 게임 서버에 ALB가 레이턴시를 유발합니다. NLB로 교체해 레이어 4 처리와 고정 IP를 제공하고 레이턴시를 최소화하세요.',
    steps: [
      { title: 'NLB 생성', desc: 'TCP 처리를 위한 Network Load Balancer를 생성하세요.',
        hint: 'aws elbv2 create-load-balancer --name game-nlb --type network --subnets subnet-0abc123 subnet-0def456 --scheme internet-facing',
        answers: ['aws elbv2 create-load-balancer --name game-nlb --type network --subnets subnet-0abc123 subnet-0def456 --scheme internet-facing'],
        successOutput: ['{"LoadBalancers": [{"LoadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/net/game-nlb/abc123", "DNSName": "game-nlb-abc123.elb.us-east-1.amazonaws.com", "Type": "network", "State": {"Code": "provisioning"}}]}'] },
      { title: 'TCP Target Group 생성', desc: 'TCP 7777 포트 Target Group을 생성하세요.',
        hint: 'aws elbv2 create-target-group --name game-tg --protocol TCP --port 7777 --vpc-id vpc-0abc123def456789 --health-check-protocol TCP --health-check-port 7777',
        answers: ['aws elbv2 create-target-group --name game-tg --protocol tcp --port 7777 --vpc-id vpc-0abc123def456789 --health-check-protocol tcp --health-check-port 7777'],
        successOutput: ['{"TargetGroups": [{"TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/game-tg/abc123", "Protocol": "TCP", "Port": 7777, "HealthCheckProtocol": "TCP"}]}'] },
      { title: 'NLB 리스너 생성', desc: 'TCP 7777 리스너를 추가하세요.',
        hint: 'aws elbv2 create-listener --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/net/game-nlb/abc123 --protocol TCP --port 7777 --default-actions Type=forward,TargetGroupArn=arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/game-tg/abc123',
        answers: ['aws elbv2 create-listener --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/net/game-nlb/abc123 --protocol tcp --port 7777 --default-actions type=forward,targetgrouparn=arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/game-tg/abc123'],
        successOutput: ['{"Listeners": [{"ListenerArn": "arn:aws:elasticloadbalancing:us-east-1:123456789012:listener/net/game-nlb/abc123/def456", "Port": 7777, "Protocol": "TCP"}]}'] },
      { title: 'NLB 처리량 메트릭 확인', desc: 'ActiveFlowCount와 ProcessedBytes 메트릭을 확인하세요.',
        hint: 'aws cloudwatch get-metric-statistics --namespace AWS/NetworkELB --metric-name ActiveFlowCount --dimensions Name=LoadBalancer,Value=net/game-nlb/abc123 --start-time 2024-01-01T00:00:00Z --end-time 2024-01-01T01:00:00Z --period 60 --statistics Average',
        answers: ['aws cloudwatch get-metric-statistics --namespace aws/networkelb --metric-name activeflowcount --dimensions name=loadbalancer,value=net/game-nlb/abc123 --start-time 2024-01-01t00:00:00z --end-time 2024-01-01t01:00:00z --period 60 --statistics average'],
        successOutput: ['{"Datapoints": [{"Timestamp": "2024-01-01T00:01:00Z", "Average": 48250.0, "Unit": "Count"}], "Label": "ActiveFlowCount"}'] },
    ],
    explanation: 'NLB는 Layer 4(TCP/UDP) 로드밸런서로 ALB보다 훨씬 낮은 레이턴시(100마이크로초 수준)를 제공합니다. 정적 IP와 Elastic IP를 지원하며 초당 수백만 요청을 처리합니다. 게임 서버, IoT, 금융 거래처럼 레이턴시가 중요하고 HTTP 헤더 처리가 불필요한 경우에 적합합니다.',
  },
  30: {
    id: 'PERF-30', title: 'PERF-30 CloudWatch 성능 대시보드 구성',
    scenario: '여러 서비스의 성능 지표를 한눈에 볼 수 있는 대시보드가 없어 장애 시 원인 파악이 늦습니다. CloudWatch 대시보드를 만들어 ALB 지연, Lambda 오류, RDS CPU, ElastiCache 히트율을 한 화면에 표시하세요.',
    steps: [
      { title: '대시보드 생성', desc: 'production-performance 대시보드를 생성하세요.',
        hint: 'aws cloudwatch put-dashboard --dashboard-name production-performance --dashboard-body file://dashboard.json',
        answers: ['aws cloudwatch put-dashboard --dashboard-name production-performance --dashboard-body file://dashboard.json'],
        successOutput: ['{"DashboardValidationMessages": []}'] },
      { title: 'ALB 지연 알람 생성', desc: 'ALB TargetResponseTime이 1초를 초과하면 알람이 울리도록 설정하세요.',
        hint: 'aws cloudwatch put-metric-alarm --alarm-name alb-latency-high --metric-name TargetResponseTime --namespace AWS/ApplicationELB --dimensions Name=LoadBalancer,Value=app/prod-alb/abc123 --statistic Average --period 60 --threshold 1.0 --comparison-operator GreaterThanThreshold --evaluation-periods 3 --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-alert',
        answers: ['aws cloudwatch put-metric-alarm --alarm-name alb-latency-high --metric-name targetresponsetime --namespace aws/applicationelb --dimensions name=loadbalancer,value=app/prod-alb/abc123 --statistic average --period 60 --threshold 1.0 --comparison-operator greaterthanthreshold --evaluation-periods 3 --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-alert'],
        successOutput: [''] },
      { title: 'Lambda 오류율 알람 생성', desc: 'Lambda Errors가 10을 초과하면 알람 설정하세요.',
        hint: 'aws cloudwatch put-metric-alarm --alarm-name lambda-error-high --metric-name Errors --namespace AWS/Lambda --dimensions Name=FunctionName,Value=api-handler --statistic Sum --period 60 --threshold 10 --comparison-operator GreaterThanThreshold --evaluation-periods 2 --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-alert',
        answers: ['aws cloudwatch put-metric-alarm --alarm-name lambda-error-high --metric-name errors --namespace aws/lambda --dimensions name=functionname,value=api-handler --statistic sum --period 60 --threshold 10 --comparison-operator greaterthanthreshold --evaluation-periods 2 --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-alert'],
        successOutput: [''] },
      { title: 'Composite Alarm 생성', desc: 'ALB 지연 OR Lambda 오류가 모두 알람 상태일 때만 울리는 복합 알람을 만드세요.',
        hint: 'aws cloudwatch put-composite-alarm --alarm-name prod-critical-composite --alarm-rule "ALARM(alb-latency-high) OR ALARM(lambda-error-high)" --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-pagerduty',
        answers: ['aws cloudwatch put-composite-alarm --alarm-name prod-critical-composite --alarm-rule "alarm(alb-latency-high) or alarm(lambda-error-high)" --alarm-actions arn:aws:sns:us-east-1:123456789012:ops-pagerduty'],
        successOutput: [''] },
      { title: '대시보드 조회', desc: '생성된 대시보드를 조회하세요.',
        hint: 'aws cloudwatch get-dashboard --dashboard-name production-performance --query "DashboardBody"',
        answers: ['aws cloudwatch get-dashboard --dashboard-name production-performance --query "dashboardbody"'],
        successOutput: ['"{\"widgets\":[{\"type\":\"metric\",\"properties\":{\"title\":\"ALB Response Time\",\"metrics\":[[\"AWS/ApplicationELB\",\"TargetResponseTime\"]]}},{\"type\":\"metric\",\"properties\":{\"title\":\"Lambda Errors\",\"metrics\":[[\"AWS/Lambda\",\"Errors\"]]}}]}"'] },
    ],
    explanation: 'CloudWatch 대시보드는 여러 서비스 지표를 하나의 화면에서 모니터링합니다. Composite Alarm은 여러 알람을 조합해 알람 노이즈를 줄입니다. put-dashboard의 dashboard-body JSON에 metric 위젯, alarm 위젯, 텍스트 위젯 등을 포함할 수 있습니다. CloudWatch Container Insights, Lambda Insights도 함께 활용하세요.',
  },
"""

TARGET = 'src/web-app.tsx'

# Anchor: the closing line of PERF-10 explanation
ANCHOR = "    explanation: 'T 계열(t2, t3, t4g)은 버스트 가능 인스턴스로 크레딧이 소진되면 기준 성능(CPU의 20-40%)으로 제한됩니다. CPU 집약적 워크로드는 C 계열(c5, c6i, c6g), 메모리 집약적은 R 계열, 범용은 M 계열이 적합합니다. c5.xlarge는 4vCPU / 8GB 메모리로 t3.medium 대비 4배 많은 vCPU를 제공합니다.',\n  },\n};"

REPLACEMENT = "    explanation: 'T 계열(t2, t3, t4g)은 버스트 가능 인스턴스로 크레딧이 소진되면 기준 성능(CPU의 20-40%)으로 제한됩니다. CPU 집약적 워크로드는 C 계열(c5, c6i, c6g), 메모리 집약적은 R 계열, 범용은 M 계열이 적합합니다. c5.xlarge는 4vCPU / 8GB 메모리로 t3.medium 대비 4배 많은 vCPU를 제공합니다.',\n  },\n" + NEW_ENTRIES + "};"

with open(TARGET, 'r', encoding='utf-8') as f:
    src = f.read()

if '11: {' in src and "id: 'PERF-11'" in src:
    print('PERF-11 already present - skipping')
else:
    if ANCHOR not in src:
        raise RuntimeError('Anchor not found - check PERF-10 explanation text')
    src = src.replace(ANCHOR, REPLACEMENT, 1)
    with open(TARGET, 'w', encoding='utf-8') as f:
        f.write(src)
    print('Inserted PERF 11-30 entries.')

print('Done.')
