# -*- coding: utf-8 -*-
"""Replaces SEC-11 to SEC-30 with expanded 4-5 step versions."""

NEW_BLOCK = r"""  11: {
    id: 'SEC-11', title: 'SEC-11 퇴사자 계정 즉시 비활성화',
    scenario: '오늘 마케팅팀 직원이 갑자기 퇴사했습니다. HR에서 "이 사람 AWS 접근을 지금 당장 막아달라"고 긴급 요청했습니다. 계정을 완전히 정리하세요.',
    steps: [
      { title: '액세스 키 목록 확인', desc: 'lee-marketing 사용자의 현재 액세스 키를 확인하세요.',
        hint: 'aws iam list-access-keys --user-name lee-marketing',
        answers: ['aws iam list-access-keys --user-name lee-marketing'],
        successOutput: ['{"AccessKeyMetadata": [{"UserName": "lee-marketing", "AccessKeyId": "AKIAIOSFODNN7EXAMPLE", "Status": "Active", "CreateDate": "2026-01-10T09:00:00Z"}]}'] },
      { title: '액세스 키 비활성화', desc: 'lee-marketing의 액세스 키를 즉시 비활성화하세요.',
        hint: 'aws iam update-access-key --user-name lee-marketing --access-key-id AKIAIOSFODNN7EXAMPLE --status Inactive',
        answers: ['aws iam update-access-key --user-name lee-marketing --access-key-id akiaiosfodnn7example --status inactive'],
        successOutput: [''] },
      { title: '콘솔 로그인 비밀번호 삭제', desc: 'lee-marketing의 콘솔 로그인 프로필을 삭제하세요.',
        hint: 'aws iam delete-login-profile --user-name lee-marketing',
        answers: ['aws iam delete-login-profile --user-name lee-marketing'],
        successOutput: [''] },
      { title: '그룹에서 제거', desc: 'lee-marketing을 marketing-team 그룹에서 제거하세요.',
        hint: 'aws iam remove-user-from-group --group-name marketing-team --user-name lee-marketing',
        answers: ['aws iam remove-user-from-group --group-name marketing-team --user-name lee-marketing'],
        successOutput: [''] },
      { title: '사용자 삭제', desc: '모든 접근이 차단된 후 IAM 사용자를 완전히 삭제하세요.',
        hint: 'aws iam delete-user --user-name lee-marketing',
        answers: ['aws iam delete-user --user-name lee-marketing'],
        successOutput: [''] },
    ],
    explanation: '퇴사자 처리 순서: 키 확인 → 비활성화 → 콘솔 로그인 삭제 → 그룹 제거 → 사용자 삭제. 바로 삭제하지 않고 비활성화를 먼저 하는 이유는 감사 로그 보존과 실수 복구를 위해서입니다.',
  },
  12: {
    id: 'SEC-12', title: 'SEC-12 IAM 계정 보안 강화',
    scenario: '보안 감사팀이 "루트 계정에 MFA가 없고, 비밀번호 정책도 너무 약하다"는 Critical 취약점을 발견했습니다. 자격증명 보고서를 확인하고 비밀번호 정책을 강화하세요.',
    steps: [
      { title: '자격증명 보고서 생성', desc: 'IAM 자격증명 보고서를 생성하세요.',
        hint: 'aws iam generate-credential-report',
        answers: ['aws iam generate-credential-report'],
        successOutput: ['{"State": "COMPLETE", "Description": "No report exists. Starting a new report generation task"}'] },
      { title: '보고서 조회', desc: '생성된 자격증명 보고서를 조회하세요.',
        hint: 'aws iam get-credential-report',
        answers: ['aws iam get-credential-report'],
        successOutput: ['{"Content": "user,arn,user_creation_time,password_enabled,password_last_used,mfa_active\\nroot,arn:aws:iam::123456789012:root,2023-01-01,not_supported,2026-04-12,false\\ndev-user,arn:aws:iam::123456789012:user/dev-user,2024-06-01,true,2026-04-10,false", "ReportFormat": "text/csv", "GeneratedTime": "2026-04-13T09:00:00Z"}'] },
      { title: '가상 MFA 디바이스 생성', desc: '루트 계정용 가상 MFA 디바이스를 생성하세요.',
        hint: 'aws iam create-virtual-mfa-device --virtual-mfa-device-name root-mfa --outfile /tmp/qr.png --bootstrap-method QRCodePNG',
        answers: ['aws iam create-virtual-mfa-device --virtual-mfa-device-name root-mfa --outfile /tmp/qr.png --bootstrap-method qrcodepng'],
        successOutput: ['{"VirtualMFADevice": {"SerialNumber": "arn:aws:iam::123456789012:mfa/root-mfa"}}'] },
      { title: '계정 비밀번호 정책 강화', desc: '최소 14자, 대소문자+숫자+특수문자 필수, 90일 만료 정책을 설정하세요.',
        hint: 'aws iam update-account-password-policy --minimum-password-length 14 --require-uppercase-characters --require-lowercase-characters --require-numbers --require-symbols --max-password-age 90 --password-reuse-prevention 12',
        answers: ['aws iam update-account-password-policy --minimum-password-length 14 --require-uppercase-characters --require-lowercase-characters --require-numbers --require-symbols --max-password-age 90 --password-reuse-prevention 12'],
        successOutput: [''] },
    ],
    explanation: 'IAM 자격증명 보고서(CSV)는 모든 사용자의 MFA 활성화 여부, 비밀번호 마지막 사용일, 액세스 키 상태를 한 번에 확인할 수 있습니다. CIS Benchmark는 최소 14자, 90일 교체, MFA 필수를 권장합니다.',
  },
  13: {
    id: 'SEC-13', title: 'SEC-13 실수로 삭제된 파일 복구',
    scenario: '배포 스크립트 버그로 S3 프로덕션 버킷의 설정 파일이 실수로 삭제됐습니다. 버전 관리 상태를 확인하고 파일을 복구한 뒤, 앞으로 이런 일이 없도록 MFA Delete를 활성화하세요.',
    steps: [
      { title: '버전 관리 상태 확인', desc: 'config-bucket의 버전 관리 상태를 확인하세요.',
        hint: 'aws s3api get-bucket-versioning --bucket config-bucket',
        answers: ['aws s3api get-bucket-versioning --bucket config-bucket'],
        successOutput: ['{"Status": "Enabled", "MFADelete": "Disabled"}'] },
      { title: '삭제된 파일의 버전 목록 조회', desc: 'app-config.json의 모든 버전과 삭제 마커를 조회하세요.',
        hint: 'aws s3api list-object-versions --bucket config-bucket --prefix app-config.json',
        answers: ['aws s3api list-object-versions --bucket config-bucket --prefix app-config.json'],
        successOutput: ['{"Versions": [{"Key": "app-config.json", "VersionId": "abc123", "LastModified": "2026-04-12T09:00:00Z", "Size": 1024}], "DeleteMarkers": [{"Key": "app-config.json", "VersionId": "del456", "LastModified": "2026-04-13T08:00:00Z"}]}'] },
      { title: '삭제 마커 제거하여 복구', desc: 'DeleteMarker를 삭제해 파일을 복구하세요.',
        hint: 'aws s3api delete-object --bucket config-bucket --key app-config.json --version-id del456',
        answers: ['aws s3api delete-object --bucket config-bucket --key app-config.json --version-id del456'],
        successOutput: ['{"DeleteMarker": true, "VersionId": "del456"}'] },
      { title: '복구 확인', desc: '파일이 정상적으로 복구됐는지 확인하세요.',
        hint: 'aws s3api head-object --bucket config-bucket --key app-config.json',
        answers: ['aws s3api head-object --bucket config-bucket --key app-config.json'],
        successOutput: ['{"ContentLength": 1024, "LastModified": "2026-04-12T09:00:00Z", "VersionId": "abc123", "ContentType": "application/json"}'] },
    ],
    explanation: 'S3 버전 관리 삭제는 실제로 "삭제 마커"를 추가합니다. 마커의 VersionId로 delete-object를 실행하면 복구됩니다. MFA Delete를 활성화하면 삭제 마커 추가 자체에 MFA가 필요해 실수 삭제를 방지합니다.',
  },
  14: {
    id: 'SEC-14', title: 'SEC-14 GuardDuty 침해 탐지 및 알림',
    scenario: '"AWS 계정에서 이상한 리전에서 EC2가 갑자기 생성됐다"는 알림을 사후에야 받았습니다. GuardDuty를 활성화하고 탐지 결과를 SNS로 실시간 알림 받도록 설정하세요.',
    steps: [
      { title: 'GuardDuty 활성화', desc: '현재 리전에서 GuardDuty를 활성화하세요.',
        hint: 'aws guardduty create-detector --enable --finding-publishing-frequency FIFTEEN_MINUTES',
        answers: ['aws guardduty create-detector --enable --finding-publishing-frequency fifteen_minutes', 'aws guardduty create-detector --enable'],
        successOutput: ['{"DetectorId": "abc123def456abc123def456abc123de"}'] },
      { title: '알림용 SNS 토픽 생성', desc: '보안 탐지 알림을 받을 SNS 토픽을 생성하세요.',
        hint: 'aws sns create-topic --name guardduty-alerts',
        answers: ['aws sns create-topic --name guardduty-alerts'],
        successOutput: ['{"TopicArn": "arn:aws:sns:us-east-1:123456789012:guardduty-alerts"}'] },
      { title: '탐지 결과 목록 조회', desc: 'GuardDuty에서 탐지된 결과 목록을 조회하세요.',
        hint: 'aws guardduty list-findings --detector-id abc123def456abc123def456abc123de',
        answers: ['aws guardduty list-findings --detector-id abc123def456abc123def456abc123de'],
        successOutput: ['{"FindingIds": ["d1abc12345def678901234567890abcd"]}'] },
      { title: '탐지 결과 상세 조회', desc: '탐지된 결과의 상세 정보를 확인하세요.',
        hint: 'aws guardduty get-findings --detector-id abc123def456abc123def456abc123de --finding-ids d1abc12345def678901234567890abcd',
        answers: ['aws guardduty get-findings --detector-id abc123def456abc123def456abc123de --finding-ids d1abc12345def678901234567890abcd'],
        successOutput: ['{"Findings": [{"Type": "UnauthorizedAccess:IAMUser/ConsoleLoginSuccess.B", "Severity": 5, "Title": "Unusual console login detected from IP 1.2.3.4 (TOR exit node)", "Region": "ap-southeast-1", "AccountId": "123456789012"}]}'] },
    ],
    explanation: 'GuardDuty는 CloudTrail, VPC Flow Logs, DNS 쿼리를 ML로 분석해 TOR 접근, 비정상 리전 활동, 크리덴셜 유출 징후 등을 자동 탐지합니다. EventBridge + SNS를 연결하면 탐지 즉시 이메일/Slack 알림이 가능합니다.',
  },
  15: {
    id: 'SEC-15', title: 'SEC-15 Lambda 최소 권한으로 좁히기',
    scenario: 'S3 파일을 읽어 DynamoDB에 저장하는 Lambda 함수의 실행 Role이 AdministratorAccess입니다. 실제 필요한 권한(S3 읽기 + DynamoDB 쓰기)만 허용하는 커스텀 정책으로 교체하세요.',
    steps: [
      { title: 'Lambda 현재 Role 확인', desc: 'data-processor Lambda의 현재 실행 Role을 확인하세요.',
        hint: 'aws lambda get-function-configuration --function-name data-processor --query "Role"',
        answers: ['aws lambda get-function-configuration --function-name data-processor --query "role"', 'aws lambda get-function-configuration --function-name data-processor'],
        successOutput: ['"arn:aws:iam::123456789012:role/lambda-admin-role"'] },
      { title: '커스텀 IAM 정책 생성', desc: 'S3 읽기와 DynamoDB 쓰기만 허용하는 커스텀 정책을 생성하세요.',
        hint: 'aws iam create-policy --policy-name lambda-s3-dynamo-policy --policy-document file://lambda-policy.json',
        answers: ['aws iam create-policy --policy-name lambda-s3-dynamo-policy --policy-document file://lambda-policy.json'],
        successOutput: ['{"Policy": {"PolicyName": "lambda-s3-dynamo-policy", "Arn": "arn:aws:iam::123456789012:policy/lambda-s3-dynamo-policy", "CreateDate": "2026-04-13T09:00:00Z"}}'] },
      { title: '최소 권한 Role 생성', desc: 'Lambda 전용 최소 권한 Role을 생성하세요.',
        hint: 'aws iam create-role --role-name lambda-minimal-role --assume-role-policy-document file://lambda-trust.json',
        answers: ['aws iam create-role --role-name lambda-minimal-role --assume-role-policy-document file://lambda-trust.json'],
        successOutput: ['{"Role": {"RoleName": "lambda-minimal-role", "Arn": "arn:aws:iam::123456789012:role/lambda-minimal-role"}}'] },
      { title: '커스텀 정책 Role에 연결', desc: '새 Role에 커스텀 정책을 연결하세요.',
        hint: 'aws iam attach-role-policy --role-name lambda-minimal-role --policy-arn arn:aws:iam::123456789012:policy/lambda-s3-dynamo-policy',
        answers: ['aws iam attach-role-policy --role-name lambda-minimal-role --policy-arn arn:aws:iam::123456789012:policy/lambda-s3-dynamo-policy'],
        successOutput: [''] },
      { title: 'Lambda Role 교체', desc: 'data-processor Lambda의 Role을 최소 권한 Role로 교체하세요.',
        hint: 'aws lambda update-function-configuration --function-name data-processor --role arn:aws:iam::123456789012:role/lambda-minimal-role',
        answers: ['aws lambda update-function-configuration --function-name data-processor --role arn:aws:iam::123456789012:role/lambda-minimal-role'],
        successOutput: ['{"FunctionName": "data-processor", "Role": "arn:aws:iam::123456789012:role/lambda-minimal-role", "LastModified": "2026-04-13T09:00:00Z"}'] },
    ],
    explanation: 'Lambda에 AdministratorAccess는 절대 금지입니다. 커스텀 정책에 S3:GetObject, DynamoDB:PutItem 등 실제 사용 API만 지정하고, 리소스도 특정 버킷/테이블 ARN으로 좁혀야 진정한 최소 권한입니다.',
  },
  16: {
    id: 'SEC-16', title: 'SEC-16 액세스 키 교체 — 90일 초과 키',
    scenario: '보안 정책상 IAM 액세스 키는 90일마다 교체해야 합니다. dev-user 계정 키가 생성된 지 120일이 지났습니다. 안전하게 키를 교체하고 기존 키를 정리하세요.',
    steps: [
      { title: '기존 키 목록 확인', desc: 'dev-user의 현재 액세스 키와 생성일을 확인하세요.',
        hint: 'aws iam list-access-keys --user-name dev-user',
        answers: ['aws iam list-access-keys --user-name dev-user'],
        successOutput: ['{"AccessKeyMetadata": [{"UserName": "dev-user", "AccessKeyId": "AKIAOLDKEY1234567890", "Status": "Active", "CreateDate": "2025-12-13T09:00:00Z"}]}'] },
      { title: '새 액세스 키 생성', desc: 'dev-user의 새 액세스 키를 생성하세요.',
        hint: 'aws iam create-access-key --user-name dev-user',
        answers: ['aws iam create-access-key --user-name dev-user'],
        successOutput: ['{"AccessKey": {"UserName": "dev-user", "AccessKeyId": "AKIANEWKEY9876543210", "SecretAccessKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYNEWKEY", "Status": "Active", "CreateDate": "2026-04-13T09:00:00Z"}}'] },
      { title: '기존 키 비활성화', desc: '새 키로 교체 완료 후 기존 키를 비활성화하세요.',
        hint: 'aws iam update-access-key --user-name dev-user --access-key-id AKIAOLDKEY1234567890 --status Inactive',
        answers: ['aws iam update-access-key --user-name dev-user --access-key-id akiaoldkey1234567890 --status inactive'],
        successOutput: [''] },
      { title: '기존 키 완전 삭제', desc: '비활성화 확인 후 기존 키를 삭제하세요.',
        hint: 'aws iam delete-access-key --user-name dev-user --access-key-id AKIAOLDKEY1234567890',
        answers: ['aws iam delete-access-key --user-name dev-user --access-key-id akiaoldkey1234567890'],
        successOutput: [''] },
    ],
    explanation: '키 교체 순서: 새 키 생성 → 새 키로 테스트 → 기존 키 비활성화(Inactive) → 정상 작동 확인(며칠간) → 삭제. 바로 삭제하면 실수 복구가 불가능하므로, Inactive로 유지하다가 문제 없으면 삭제합니다.',
  },
  17: {
    id: 'SEC-17', title: 'SEC-17 루트 계정 로그인 실시간 알람',
    scenario: '보안 팀에서 "루트 계정이 언제 로그인하는지 실시간으로 알고 싶다"고 했습니다. CloudTrail → CloudWatch Logs → SNS 알림 체인을 구성하세요.',
    steps: [
      { title: 'SNS 토픽 생성', desc: '보안 알림을 보낼 SNS 토픽을 생성하세요.',
        hint: 'aws sns create-topic --name security-alerts',
        answers: ['aws sns create-topic --name security-alerts'],
        successOutput: ['{"TopicArn": "arn:aws:sns:us-east-1:123456789012:security-alerts"}'] },
      { title: '이메일 구독 추가', desc: 'security-alerts 토픽에 이메일 구독을 추가하세요.',
        hint: 'aws sns subscribe --topic-arn arn:aws:sns:us-east-1:123456789012:security-alerts --protocol email --notification-endpoint security@company.com',
        answers: ['aws sns subscribe --topic-arn arn:aws:sns:us-east-1:123456789012:security-alerts --protocol email --notification-endpoint security@company.com'],
        successOutput: ['{"SubscriptionArn": "pending confirmation"}'] },
      { title: 'CloudWatch 지표 필터 생성', desc: 'CloudTrail 로그에서 루트 로그인 이벤트를 감지하는 지표 필터를 만드세요.',
        hint: 'aws logs put-metric-filter --log-group-name CloudTrail/DefaultLogGroup --filter-name RootLoginFilter --filter-pattern "{$.userIdentity.type = Root}" --metric-transformations metricName=RootLoginCount,metricNamespace=SecurityMetrics,metricValue=1',
        answers: ['aws logs put-metric-filter --log-group-name cloudtrail/defaultloggroup --filter-name rootloginfilter --filter-pattern "{$.useridentity.type = root}" --metric-transformations metricname=rootlogincount,metricnamespace=securitymetrics,metricvalue=1'],
        successOutput: [''] },
      { title: 'CloudWatch 알람 생성', desc: '루트 로그인 시 SNS 알림을 보내는 알람을 생성하세요.',
        hint: 'aws cloudwatch put-metric-alarm --alarm-name RootLoginAlarm --metric-name RootLoginCount --namespace SecurityMetrics --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --evaluation-periods 1 --period 60 --statistic Sum --alarm-actions arn:aws:sns:us-east-1:123456789012:security-alerts',
        answers: ['aws cloudwatch put-metric-alarm --alarm-name rootloginalarm --metric-name rootlogincount --namespace securitymetrics --threshold 1 --comparison-operator greaterthanorequaltothreshold --evaluation-periods 1 --period 60 --statistic sum --alarm-actions arn:aws:sns:us-east-1:123456789012:security-alerts'],
        successOutput: [''] },
    ],
    explanation: 'CloudTrail → CloudWatch Logs → 지표 필터 → CloudWatch 알람 → SNS 알림 체인으로 실시간 보안 모니터링을 구성합니다. 루트 로그인은 CIS AWS Foundations Benchmark에서도 모니터링 필수 항목입니다.',
  },
  18: {
    id: 'SEC-18', title: 'SEC-18 S3 버킷 접근 로그 활성화',
    scenario: '개인정보보호법 감사에서 "S3 버킷에 누가 언제 어떤 파일을 읽었는지 기록이 없다"는 지적을 받았습니다. 로그 버킷을 생성하고 접근 기록을 남기세요.',
    steps: [
      { title: '로그 저장용 버킷 생성', desc: '접근 로그를 저장할 별도 버킷을 생성하세요.',
        hint: 'aws s3api create-bucket --bucket customer-data-access-logs --region us-east-1',
        answers: ['aws s3api create-bucket --bucket customer-data-access-logs --region us-east-1', 'aws s3 mb s3://customer-data-access-logs'],
        successOutput: ['{"Location": "/customer-data-access-logs"}'] },
      { title: '서버 액세스 로깅 활성화', desc: 'customer-data 버킷의 접근 로그를 로그 버킷에 저장하도록 설정하세요.',
        hint: 'aws s3api put-bucket-logging --bucket customer-data --bucket-logging-status file://logging.json',
        answers: ['aws s3api put-bucket-logging --bucket customer-data --bucket-logging-status file://logging.json'],
        successOutput: [''] },
      { title: '로깅 설정 확인', desc: '로깅 설정이 올바르게 적용됐는지 확인하세요.',
        hint: 'aws s3api get-bucket-logging --bucket customer-data',
        answers: ['aws s3api get-bucket-logging --bucket customer-data'],
        successOutput: ['{"LoggingEnabled": {"TargetBucket": "customer-data-access-logs", "TargetPrefix": "logs/"}}'] },
      { title: '로그 버킷에 로그 파일 존재 확인', desc: '로그 파일이 저장되고 있는지 확인하세요.',
        hint: 'aws s3 ls s3://customer-data-access-logs/logs/',
        answers: ['aws s3 ls s3://customer-data-access-logs/logs/'],
        successOutput: ['2026-04-13 09:15:32        842 logs/2026-04-13-09-15-00-ABCDEF1234567890\n2026-04-13 09:20:11        1204 logs/2026-04-13-09-20-00-FEDCBA0987654321'] },
    ],
    explanation: 'S3 서버 액세스 로깅은 버킷에 대한 모든 요청을 기록합니다. 로그 버킷과 원본 버킷은 같은 리전에 있어야 하며, 로그 전달에 약간의 지연(수 분)이 있습니다. 로그는 Athena로 쿼리할 수 있습니다.',
  },
  19: {
    id: 'SEC-19', title: 'SEC-19 환경변수 대신 Parameter Store 사용',
    scenario: 'Lambda 함수의 환경변수에 API 키, DB 연결문자열이 평문으로 저장되어 있습니다. SSM Parameter Store로 이전하고 Lambda 환경변수에서 제거하세요.',
    steps: [
      { title: 'DB URL SecureString 저장', desc: 'DB 연결 문자열을 암호화된 파라미터로 저장하세요.',
        hint: 'aws ssm put-parameter --name /prod/lambda/db-url --value "mysql://admin:pass@rds.internal:3306/app" --type SecureString',
        answers: ['aws ssm put-parameter --name /prod/lambda/db-url --value "mysql://admin:pass@rds.internal:3306/app" --type securestring'],
        successOutput: ['{"Version": 1, "Tier": "Standard"}'] },
      { title: 'API 키 SecureString 저장', desc: '외부 API 키도 SecureString으로 저장하세요.',
        hint: 'aws ssm put-parameter --name /prod/lambda/api-key --value "sk-abc123xyz456" --type SecureString',
        answers: ['aws ssm put-parameter --name /prod/lambda/api-key --value "sk-abc123xyz456" --type securestring'],
        successOutput: ['{"Version": 1, "Tier": "Standard"}'] },
      { title: '파라미터 복호화 조회 확인', desc: '런타임에 파라미터를 복호화해서 가져올 수 있는지 확인하세요.',
        hint: 'aws ssm get-parameter --name /prod/lambda/db-url --with-decryption',
        answers: ['aws ssm get-parameter --name /prod/lambda/db-url --with-decryption'],
        successOutput: ['{"Parameter": {"Name": "/prod/lambda/db-url", "Type": "SecureString", "Value": "mysql://admin:pass@rds.internal:3306/app", "Version": 1}}'] },
      { title: 'Lambda 환경변수 제거', desc: 'Lambda 함수의 환경변수에서 민감정보를 제거하세요.',
        hint: 'aws lambda update-function-configuration --function-name data-processor --environment "Variables={LOG_LEVEL=INFO}"',
        answers: ['aws lambda update-function-configuration --function-name data-processor --environment "variables={log_level=info}"'],
        successOutput: ['{"FunctionName": "data-processor", "Environment": {"Variables": {"LOG_LEVEL": "INFO"}}, "LastModified": "2026-04-13T09:00:00Z"}'] },
    ],
    explanation: 'SSM Parameter Store SecureString은 KMS로 암호화되어 저장됩니다. Lambda에서 SDK로 런타임에 조회하며, 환경변수 평문 저장보다 훨씬 안전합니다. --with-decryption 플래그 없이 조회하면 암호화된 값이 반환됩니다.',
  },
  20: {
    id: 'SEC-20', title: 'SEC-20 IMDSv2 강제로 SSRF 차단',
    scenario: 'EC2 웹앱에서 SSRF 취약점이 발견됐습니다. 공격자가 인스턴스 메타데이터(IMDS)에 접근해 IAM 자격증명을 탈취할 수 있습니다. IMDSv2를 강제 적용하고 신규 인스턴스도 기본값으로 설정하세요.',
    steps: [
      { title: 'IMDSv1 사용 현황 확인', desc: 'EC2 인스턴스의 현재 메타데이터 옵션을 확인하세요.',
        hint: 'aws ec2 describe-instances --instance-ids i-0abcdef1234567890 --query "Reservations[0].Instances[0].MetadataOptions"',
        answers: ['aws ec2 describe-instances --instance-ids i-0abcdef1234567890 --query "reservations[0].instances[0].metadataoptions"', 'aws ec2 describe-instances --instance-ids i-0abcdef1234567890'],
        successOutput: ['{"HttpEndpoint": "enabled", "HttpTokens": "optional", "HttpPutResponseHopLimit": 1, "State": "applied"}'] },
      { title: 'IMDSv2 강제 적용', desc: 'HttpTokens를 required로 변경해 IMDSv2만 허용하세요.',
        hint: 'aws ec2 modify-instance-metadata-options --instance-id i-0abcdef1234567890 --http-tokens required --http-endpoint enabled',
        answers: ['aws ec2 modify-instance-metadata-options --instance-id i-0abcdef1234567890 --http-tokens required --http-endpoint enabled'],
        successOutput: ['{"InstanceId": "i-0abcdef1234567890", "InstanceMetadataOptions": {"HttpEndpoint": "enabled", "HttpTokens": "required", "HttpPutResponseHopLimit": 1, "State": "pending"}}'] },
      { title: '설정 반영 확인', desc: 'IMDSv2 강제 적용이 완료됐는지 확인하세요.',
        hint: 'aws ec2 describe-instances --instance-ids i-0abcdef1234567890 --query "Reservations[0].Instances[0].MetadataOptions.HttpTokens"',
        answers: ['aws ec2 describe-instances --instance-ids i-0abcdef1234567890 --query "reservations[0].instances[0].metadataoptions.httptokens"'],
        successOutput: ['"required"'] },
      { title: '신규 인스턴스 IMDSv2 기본값 설정', desc: '계정의 모든 신규 인스턴스에도 IMDSv2가 기본 적용되도록 설정하세요.',
        hint: 'aws ec2 modify-instance-metadata-defaults --http-tokens required --region us-east-1',
        answers: ['aws ec2 modify-instance-metadata-defaults --http-tokens required --region us-east-1'],
        successOutput: [''] },
    ],
    explanation: 'IMDSv1은 단순 HTTP GET으로 자격증명 조회가 가능해 SSRF에 취약합니다. IMDSv2는 PUT으로 세션 토큰을 먼저 받아야 하므로 단순 SSRF로는 접근 불가합니다. 계정 기본값도 함께 설정해야 신규 인스턴스도 보호됩니다.',
  },
  21: {
    id: 'SEC-21', title: 'SEC-21 VPC Flow Logs로 트래픽 감사',
    scenario: '"특정 EC2 인스턴스가 외부 IP와 통신하는 것 같다"는 보고가 왔는데 VPC 트래픽 로그가 없어 확인이 불가능했습니다. Flow Logs를 활성화하고 의심 트래픽을 조회하세요.',
    steps: [
      { title: '로그 그룹 생성', desc: 'VPC Flow Logs를 저장할 CloudWatch 로그 그룹을 생성하세요.',
        hint: 'aws logs create-log-group --log-group-name /vpc/flow-logs',
        answers: ['aws logs create-log-group --log-group-name /vpc/flow-logs'],
        successOutput: [''] },
      { title: 'VPC Flow Logs 활성화', desc: 'VPC에 Flow Logs를 활성화해 모든 트래픽을 기록하세요.',
        hint: 'aws ec2 create-flow-logs --resource-type VPC --resource-ids vpc-0abc123def456789 --traffic-type ALL --log-destination-type cloud-watch-logs --log-group-name /vpc/flow-logs --deliver-logs-permission-arn arn:aws:iam::123456789012:role/flowlogs-role',
        answers: ['aws ec2 create-flow-logs --resource-type vpc --resource-ids vpc-0abc123def456789 --traffic-type all --log-destination-type cloud-watch-logs --log-group-name /vpc/flow-logs --deliver-logs-permission-arn arn:aws:iam::123456789012:role/flowlogs-role'],
        successOutput: ['{"FlowLogIds": ["fl-0abc123def456789"], "Unsuccessful": []}'] },
      { title: 'Flow Logs 상태 확인', desc: '생성된 Flow Logs가 ACTIVE 상태인지 확인하세요.',
        hint: 'aws ec2 describe-flow-logs --filter Name=resource-id,Values=vpc-0abc123def456789',
        answers: ['aws ec2 describe-flow-logs --filter name=resource-id,values=vpc-0abc123def456789'],
        successOutput: ['{"FlowLogs": [{"FlowLogId": "fl-0abc123def456789", "FlowLogStatus": "ACTIVE", "ResourceId": "vpc-0abc123def456789", "TrafficType": "ALL", "LogGroupName": "/vpc/flow-logs"}]}'] },
      { title: '로그 스트림 조회', desc: '로그 그룹에서 생성된 스트림 목록을 확인하세요.',
        hint: 'aws logs describe-log-streams --log-group-name /vpc/flow-logs',
        answers: ['aws logs describe-log-streams --log-group-name /vpc/flow-logs'],
        successOutput: ['{"logStreams": [{"logStreamName": "eni-0abc123-all", "firstEventTimestamp": 1744538400000, "lastEventTimestamp": 1744538700000, "storedBytes": 4096}]}'] },
    ],
    explanation: 'VPC Flow Logs는 ENI의 IP 트래픽을 캡처합니다. ACCEPT/REJECT 여부, 소스/목적지 IP·포트를 기록하므로 보안 사고 조사에 필수입니다. CloudWatch Logs Insights로 특정 IP나 포트를 쿼리할 수 있습니다.',
  },
  22: {
    id: 'SEC-22', title: 'SEC-22 S3 모든 업로드에 암호화 강제',
    scenario: '팀원이 실수로 암호화 헤더 없이 S3에 고객 개인정보를 업로드했습니다. 기본 암호화를 설정하고, 버킷 정책으로 비암호화 업로드와 HTTP 접근을 모두 차단하세요.',
    steps: [
      { title: '현재 암호화 설정 확인', desc: 'secure-uploads 버킷의 현재 암호화 설정을 확인하세요.',
        hint: 'aws s3api get-bucket-encryption --bucket secure-uploads',
        answers: ['aws s3api get-bucket-encryption --bucket secure-uploads'],
        successOutput: ['An error occurred (ServerSideEncryptionConfigurationNotFoundError) when calling the GetBucketEncryption operation: The server side encryption configuration was not found'] },
      { title: '기본 SSE-S3 암호화 설정', desc: 'SSE-S3로 기본 암호화를 설정하세요.',
        hint: 'aws s3api put-bucket-encryption --bucket secure-uploads --server-side-encryption-configuration file://sse-config.json',
        answers: ['aws s3api put-bucket-encryption --bucket secure-uploads --server-side-encryption-configuration file://sse-config.json'],
        successOutput: [''] },
      { title: '암호화 설정 확인', desc: '기본 암호화가 적용됐는지 확인하세요.',
        hint: 'aws s3api get-bucket-encryption --bucket secure-uploads',
        answers: ['aws s3api get-bucket-encryption --bucket secure-uploads'],
        successOutput: ['{"ServerSideEncryptionConfiguration": {"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}}'] },
      { title: 'HTTPS 전용 + 암호화 강제 정책 적용', desc: '비암호화 업로드와 HTTP 접근을 거부하는 버킷 정책을 적용하세요.',
        hint: 'aws s3api put-bucket-policy --bucket secure-uploads --policy file://deny-unencrypted.json',
        answers: ['aws s3api put-bucket-policy --bucket secure-uploads --policy file://deny-unencrypted.json'],
        successOutput: [''] },
    ],
    explanation: '기본 암호화 설정은 헤더 없이 업로드할 때 자동 암호화하지만, 명시적으로 "암호화 안 함"으로 요청하면 막지 못합니다. 버킷 정책에서 aws:SecureTransport: false(HTTP) 요청과 암호화 조건 없는 요청을 Deny해야 완전히 강제됩니다.',
  },
  23: {
    id: 'SEC-23', title: 'SEC-23 보안 그룹 SSH 개방 자동 감지',
    scenario: '개발자가 디버깅 목적으로 SSH(22번 포트)를 0.0.0.0/0으로 열었습니다. AWS Config로 이런 실수를 자동 감지하고, 규칙 위반 시 자동 수정(Auto Remediation)까지 설정하세요.',
    steps: [
      { title: 'AWS Config 레코더 활성화', desc: 'AWS Config로 보안 그룹 변경사항을 기록하기 시작하세요.',
        hint: 'aws configservice put-configuration-recorder --configuration-recorder name=default,roleARN=arn:aws:iam::123456789012:role/config-role',
        answers: ['aws configservice put-configuration-recorder --configuration-recorder name=default,rolearn=arn:aws:iam::123456789012:role/config-role'],
        successOutput: [''] },
      { title: '배포 채널 설정', desc: 'Config 결과를 S3에 저장하는 배포 채널을 설정하세요.',
        hint: 'aws configservice put-delivery-channel --delivery-channel name=default,s3BucketName=config-bucket',
        answers: ['aws configservice put-delivery-channel --delivery-channel name=default,s3bucketname=config-bucket'],
        successOutput: [''] },
      { title: 'restricted-ssh Config 규칙 추가', desc: 'SSH 전체 개방을 감지하는 관리형 Config 규칙을 추가하세요.',
        hint: 'aws configservice put-config-rule --config-rule file://restricted-ssh-rule.json',
        answers: ['aws configservice put-config-rule --config-rule file://restricted-ssh-rule.json'],
        successOutput: [''] },
      { title: '컴플라이언스 상태 확인', desc: 'restricted-ssh 규칙의 컴플라이언스 상태를 확인하세요.',
        hint: 'aws configservice describe-compliance-by-config-rule --config-rule-names restricted-ssh',
        answers: ['aws configservice describe-compliance-by-config-rule --config-rule-names restricted-ssh'],
        successOutput: ['{"ComplianceByConfigRules": [{"ConfigRuleName": "restricted-ssh", "Compliance": {"ComplianceType": "NON_COMPLIANT", "ComplianceContributorCount": {"CappedCount": 1, "CapExceeded": false}}}]}'] },
    ],
    explanation: 'AWS Config는 리소스 구성 변경을 지속적으로 기록하고 관리형 규칙으로 컴플라이언스를 자동 평가합니다. restricted-ssh 규칙은 0.0.0.0/0 22번 포트 개방 시 NON_COMPLIANT 표시 후 Systems Manager Automation으로 자동 교정도 가능합니다.',
  },
  24: {
    id: 'SEC-24', title: 'SEC-24 IAM Access Analyzer — 외부 공개 리소스 탐지',
    scenario: '"우리 계정에서 외부에 접근 가능한 리소스가 있는지 모두 찾아라"고 했습니다. Access Analyzer로 자동 탐지하고, 발견된 취약점을 처리하세요.',
    steps: [
      { title: 'IAM Access Analyzer 생성', desc: '계정 전체를 스캔하는 Analyzer를 생성하세요.',
        hint: 'aws accessanalyzer create-analyzer --analyzer-name account-analyzer --type ACCOUNT',
        answers: ['aws accessanalyzer create-analyzer --analyzer-name account-analyzer --type account'],
        successOutput: ['{"arn": "arn:aws:access-analyzer:us-east-1:123456789012:analyzer/account-analyzer"}'] },
      { title: '외부 접근 가능 리소스 목록 조회', desc: 'Analyzer가 찾아낸 외부 접근 가능 리소스를 조회하세요.',
        hint: 'aws accessanalyzer list-findings --analyzer-arn arn:aws:access-analyzer:us-east-1:123456789012:analyzer/account-analyzer',
        answers: ['aws accessanalyzer list-findings --analyzer-arn arn:aws:access-analyzer:us-east-1:123456789012:analyzer/account-analyzer'],
        successOutput: ['{"findings": [{"id": "abc123", "resourceType": "AWS::S3::Bucket", "resource": "arn:aws:s3:::old-backup-bucket", "status": "ACTIVE", "isPublic": true}]}'] },
      { title: '취약점 상세 조회', desc: '발견된 취약점의 상세 정보를 확인하세요.',
        hint: 'aws accessanalyzer get-finding --analyzer-arn arn:aws:access-analyzer:us-east-1:123456789012:analyzer/account-analyzer --id abc123',
        answers: ['aws accessanalyzer get-finding --analyzer-arn arn:aws:access-analyzer:us-east-1:123456789012:analyzer/account-analyzer --id abc123'],
        successOutput: ['{"finding": {"id": "abc123", "resourceType": "AWS::S3::Bucket", "resource": "arn:aws:s3:::old-backup-bucket", "isPublic": true, "principal": {"AWS": "*"}, "action": ["s3:GetObject", "s3:ListBucket"]}}'] },
      { title: '취약점 아카이브 처리', desc: '조치 완료 후 finding을 아카이브하세요.',
        hint: 'aws accessanalyzer update-findings --analyzer-arn arn:aws:access-analyzer:us-east-1:123456789012:analyzer/account-analyzer --ids abc123 --status ARCHIVED',
        answers: ['aws accessanalyzer update-findings --analyzer-arn arn:aws:access-analyzer:us-east-1:123456789012:analyzer/account-analyzer --ids abc123 --status archived'],
        successOutput: [''] },
    ],
    explanation: 'IAM Access Analyzer는 S3 버킷 정책, IAM Role Trust Policy, KMS 키 정책 등을 분석해 외부 접근 가능한 리소스를 자동으로 찾아냅니다. 조치 완료 후 ARCHIVED로 표시하면 해당 finding은 더 이상 표시되지 않습니다.',
  },
  25: {
    id: 'SEC-25', title: 'SEC-25 S3 버킷 퍼블릭 ACL 일괄 점검',
    scenario: '"레거시 버킷 중 퍼블릭 ACL로 된 게 있을 수 있다"는 우려가 나왔습니다. 버킷 ACL을 점검하고, 문제 버킷을 수정한 뒤 계정 수준으로 퍼블릭 액세스를 차단하세요.',
    steps: [
      { title: '계정 전체 버킷 목록 조회', desc: '현재 계정의 모든 S3 버킷을 조회하세요.',
        hint: 'aws s3api list-buckets --query "Buckets[].Name"',
        answers: ['aws s3api list-buckets --query "buckets[].name"', 'aws s3api list-buckets'],
        successOutput: ['["prod-data-bucket", "dev-assets", "old-backup-2023", "static-web-content", "log-archive"]'] },
      { title: '문제 버킷 ACL 확인', desc: 'old-backup-2023 버킷의 ACL을 확인하세요.',
        hint: 'aws s3api get-bucket-acl --bucket old-backup-2023',
        answers: ['aws s3api get-bucket-acl --bucket old-backup-2023'],
        successOutput: ['{"Owner": {"DisplayName": "admin"}, "Grants": [{"Grantee": {"Type": "Group", "URI": "http://acs.amazonaws.com/groups/global/AllUsers"}, "Permission": "READ"}]}'] },
      { title: '버킷 ACL을 private으로 변경', desc: 'old-backup-2023 버킷 ACL을 private으로 변경하세요.',
        hint: 'aws s3api put-bucket-acl --bucket old-backup-2023 --acl private',
        answers: ['aws s3api put-bucket-acl --bucket old-backup-2023 --acl private'],
        successOutput: [''] },
      { title: '계정 수준 퍼블릭 액세스 차단', desc: '계정 전체에 S3 퍼블릭 액세스 차단을 적용하세요.',
        hint: 'aws s3control put-public-access-block --account-id 123456789012 --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true',
        answers: ['aws s3control put-public-access-block --account-id 123456789012 --public-access-block-configuration blockpublicacls=true,ignorepublicacls=true,blockpublicpolicy=true,restrictpublicbuckets=true'],
        successOutput: [''] },
    ],
    explanation: '계정 레벨 S3 Block Public Access는 모든 버킷에 일괄 적용됩니다. IgnorePublicAcls=true는 기존 퍼블릭 ACL도 무력화합니다. 새 계정에서는 기본 활성화가 AWS 권장 사항입니다.',
  },
  26: {
    id: 'SEC-26', title: 'SEC-26 RDS 자동 백업 및 스냅샷 관리',
    scenario: '서비스 장애 복구 훈련 중 "RDS 자동 백업이 꺼져 있고 마지막 스냅샷도 없다"는 치명적인 문제를 발견했습니다. 즉시 백업 정책을 설정하고 수동 스냅샷을 생성하세요.',
    steps: [
      { title: 'RDS 인스턴스 백업 설정 확인', desc: '운영 DB의 현재 백업 설정을 확인하세요.',
        hint: 'aws rds describe-db-instances --db-instance-identifier prod-mysql --query "DBInstances[0].{Backup:BackupRetentionPeriod,Encrypted:StorageEncrypted}"',
        answers: ['aws rds describe-db-instances --db-instance-identifier prod-mysql --query "dbinstances[0].{backup:backupretentionperiod,encrypted:storageencrypted}"', 'aws rds describe-db-instances --db-instance-identifier prod-mysql'],
        successOutput: ['{"Backup": 0, "Encrypted": false}'] },
      { title: '자동 백업 7일 보존 설정', desc: '자동 백업을 7일 보존으로 활성화하세요.',
        hint: 'aws rds modify-db-instance --db-instance-identifier prod-mysql --backup-retention-period 7 --apply-immediately',
        answers: ['aws rds modify-db-instance --db-instance-identifier prod-mysql --backup-retention-period 7 --apply-immediately'],
        successOutput: ['{"DBInstance": {"DBInstanceIdentifier": "prod-mysql", "BackupRetentionPeriod": 7, "PendingModifiedValues": {}}}'] },
      { title: '백업 윈도우 설정', desc: '트래픽이 적은 새벽 3시에 백업이 실행되도록 설정하세요.',
        hint: 'aws rds modify-db-instance --db-instance-identifier prod-mysql --preferred-backup-window 03:00-03:30',
        answers: ['aws rds modify-db-instance --db-instance-identifier prod-mysql --preferred-backup-window 03:00-03:30'],
        successOutput: ['{"DBInstance": {"DBInstanceIdentifier": "prod-mysql", "PreferredBackupWindow": "03:00-03:30"}}'] },
      { title: '수동 스냅샷 즉시 생성', desc: '설정 변경 전 현재 상태의 스냅샷을 즉시 생성하세요.',
        hint: 'aws rds create-db-snapshot --db-instance-identifier prod-mysql --db-snapshot-identifier prod-mysql-manual-20260413',
        answers: ['aws rds create-db-snapshot --db-instance-identifier prod-mysql --db-snapshot-identifier prod-mysql-manual-20260413'],
        successOutput: ['{"DBSnapshot": {"DBSnapshotIdentifier": "prod-mysql-manual-20260413", "DBInstanceIdentifier": "prod-mysql", "SnapshotType": "manual", "Status": "creating"}}'] },
    ],
    explanation: 'RDS 자동 백업 보존 기간 0은 백업 비활성화입니다. 운영 환경에서는 최소 7일 이상 보존해야 합니다. 백업 윈도우는 트래픽이 적은 시간대를 선택하고, 유지보수 윈도우와 겹치지 않도록 주의하세요.',
  },
  27: {
    id: 'SEC-27', title: 'SEC-27 CloudFront + S3 OAI로 직접 접근 차단',
    scenario: '정적 웹사이트를 S3로 호스팅하고 CloudFront로 배포 중인데 S3 URL로 직접 접근도 됩니다. CloudFront를 통해서만 접근 가능하도록 OAI를 설정하세요.',
    steps: [
      { title: '현재 S3 버킷 정책 확인', desc: 'static-web-content 버킷의 현재 정책을 확인하세요.',
        hint: 'aws s3api get-bucket-policy --bucket static-web-content',
        answers: ['aws s3api get-bucket-policy --bucket static-web-content'],
        successOutput: ['{"Policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::static-web-content/*\"}]}"}'] },
      { title: 'OAI 생성', desc: 'CloudFront 전용 Origin Access Identity를 생성하세요.',
        hint: 'aws cloudfront create-cloud-front-origin-access-identity --cloud-front-origin-access-identity-config CallerReference=myoai,Comment=S3AccessOAI',
        answers: ['aws cloudfront create-cloud-front-origin-access-identity --cloud-front-origin-access-identity-config callerreference=myoai,comment=s3accessoai'],
        successOutput: ['{"CloudFrontOriginAccessIdentity": {"Id": "E2QWRUHEXAMPLE", "S3CanonicalUserId": "79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be"}}'] },
      { title: 'OAI 기반 버킷 정책 업데이트', desc: 'OAI만 접근 허용하는 버킷 정책으로 교체하세요.',
        hint: 'aws s3api put-bucket-policy --bucket static-web-content --policy file://oai-policy.json',
        answers: ['aws s3api put-bucket-policy --bucket static-web-content --policy file://oai-policy.json'],
        successOutput: [''] },
      { title: 'S3 퍼블릭 액세스 완전 차단', desc: 'S3 직접 접근을 완전히 차단하세요.',
        hint: 'aws s3api put-public-access-block --bucket static-web-content --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true',
        answers: ['aws s3api put-public-access-block --bucket static-web-content --public-access-block-configuration blockpublicacls=true,ignorepublicacls=true,blockpublicpolicy=true,restrictpublicbuckets=true'],
        successOutput: [''] },
      { title: '설정 최종 확인', desc: '버킷의 퍼블릭 액세스 차단이 적용됐는지 확인하세요.',
        hint: 'aws s3api get-public-access-block --bucket static-web-content',
        answers: ['aws s3api get-public-access-block --bucket static-web-content'],
        successOutput: ['{"PublicAccessBlockConfiguration": {"BlockPublicAcls": true, "IgnorePublicAcls": true, "BlockPublicPolicy": true, "RestrictPublicBuckets": true}}'] },
    ],
    explanation: 'OAI는 CloudFront가 S3에 접근할 때 사용하는 특수 ID입니다. 버킷 정책에서 이 OAI만 허용하고 퍼블릭 액세스를 차단하면, S3 URL 직접 접근이 불가능해지고 CloudFront URL로만 콘텐츠를 서비스할 수 있습니다.',
  },
  28: {
    id: 'SEC-28', title: 'SEC-28 Lambda Role 신뢰 정책 오류 수정',
    scenario: 'Lambda 함수가 "AccessDenied: sts:AssumeRole"로 실패하고 있습니다. 신뢰 정책(Trust Policy)에 Principal이 잘못 설정되어 있습니다. 원인을 파악하고 수정하세요.',
    steps: [
      { title: 'Lambda 함수 현재 Role 확인', desc: 'lambda-processing 함수의 현재 실행 Role을 확인하세요.',
        hint: 'aws lambda get-function-configuration --function-name lambda-processing --query "Role"',
        answers: ['aws lambda get-function-configuration --function-name lambda-processing --query "role"', 'aws lambda get-function-configuration --function-name lambda-processing'],
        successOutput: ['"arn:aws:iam::123456789012:role/lambda-processing-role"'] },
      { title: 'Role 신뢰 정책 확인', desc: 'lambda-processing-role의 신뢰 정책을 확인하세요.',
        hint: 'aws iam get-role --role-name lambda-processing-role --query "Role.AssumeRolePolicyDocument"',
        answers: ['aws iam get-role --role-name lambda-processing-role --query "role.assumerolepolicydocument"', 'aws iam get-role --role-name lambda-processing-role'],
        successOutput: ['{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Principal": {"Service": "ec2.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'] },
      { title: '신뢰 정책 수정', desc: 'Principal을 lambda.amazonaws.com으로 수정하세요.',
        hint: 'aws iam update-assume-role-policy --role-name lambda-processing-role --policy-document file://lambda-trust.json',
        answers: ['aws iam update-assume-role-policy --role-name lambda-processing-role --policy-document file://lambda-trust.json'],
        successOutput: [''] },
      { title: '수정 결과 확인', desc: '신뢰 정책이 올바르게 수정됐는지 확인하세요.',
        hint: 'aws iam get-role --role-name lambda-processing-role --query "Role.AssumeRolePolicyDocument"',
        answers: ['aws iam get-role --role-name lambda-processing-role --query "role.assumerolepolicydocument"'],
        successOutput: ['{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'] },
    ],
    explanation: 'IAM Role의 신뢰 정책(Trust Policy)은 누가 이 Role을 Assume할 수 있는지 정의합니다. Lambda Role은 반드시 lambda.amazonaws.com을 신뢰해야 하는데, ec2.amazonaws.com으로 잘못 설정하면 Lambda가 Role을 사용할 수 없습니다.',
  },
  29: {
    id: 'SEC-29', title: 'SEC-29 결제 알람 및 예산 설정',
    scenario: '지난달 갑자기 청구서가 $5,000이 나왔습니다. 무단 GPU 인스턴스 생성이 원인이었습니다. 월 $500 초과 시 알림과 AWS Budgets로 예산 초과 방지를 설정하세요.',
    steps: [
      { title: '알림용 SNS 토픽 생성', desc: '결제 알림을 받을 SNS 토픽을 생성하세요.',
        hint: 'aws sns create-topic --name billing-alerts --region us-east-1',
        answers: ['aws sns create-topic --name billing-alerts --region us-east-1', 'aws sns create-topic --name billing-alerts'],
        successOutput: ['{"TopicArn": "arn:aws:sns:us-east-1:123456789012:billing-alerts"}'] },
      { title: '이메일 구독 추가', desc: 'billing-alerts 토픽에 이메일 구독을 추가하세요.',
        hint: 'aws sns subscribe --topic-arn arn:aws:sns:us-east-1:123456789012:billing-alerts --protocol email --notification-endpoint admin@company.com',
        answers: ['aws sns subscribe --topic-arn arn:aws:sns:us-east-1:123456789012:billing-alerts --protocol email --notification-endpoint admin@company.com'],
        successOutput: ['{"SubscriptionArn": "pending confirmation"}'] },
      { title: '결제 CloudWatch 알람 생성', desc: '월 예상 비용 $500 초과 시 SNS 알림 알람을 생성하세요.',
        hint: 'aws cloudwatch put-metric-alarm --alarm-name MonthlyBillingAlarm --metric-name EstimatedCharges --namespace AWS/Billing --threshold 500 --comparison-operator GreaterThanOrEqualToThreshold --evaluation-periods 1 --period 86400 --statistic Maximum --dimensions Name=Currency,Value=USD --alarm-actions arn:aws:sns:us-east-1:123456789012:billing-alerts --region us-east-1',
        answers: ['aws cloudwatch put-metric-alarm --alarm-name monthlybillingalarm --metric-name estimatedcharges --namespace aws/billing --threshold 500 --comparison-operator greaterthanorequaltothreshold --evaluation-periods 1 --period 86400 --statistic maximum --dimensions name=currency,value=usd --alarm-actions arn:aws:sns:us-east-1:123456789012:billing-alerts --region us-east-1'],
        successOutput: [''] },
      { title: 'AWS Budgets 예산 생성', desc: '월 $500 예산을 생성하고 80% 사용 시 알림이 가도록 설정하세요.',
        hint: 'aws budgets create-budget --account-id 123456789012 --budget file://budget.json --notifications-with-subscribers file://budget-notification.json',
        answers: ['aws budgets create-budget --account-id 123456789012 --budget file://budget.json --notifications-with-subscribers file://budget-notification.json'],
        successOutput: [''] },
    ],
    explanation: 'CloudWatch 결제 알람은 us-east-1에서만 생성 가능합니다. AWS Budgets는 알람보다 세밀한 비용 제어가 가능하며, 서비스별·태그별·리전별 예산을 따로 설정할 수 있습니다. 두 가지를 함께 사용하는 것이 좋습니다.',
  },
  30: {
    id: 'SEC-30', title: 'SEC-30 전체 보안 현황 점검 — Security Hub',
    scenario: '신규 CTO가 "AWS 보안 현황을 오늘 오후까지 보고하라"고 했습니다. Security Hub로 계정 전체 보안 점수와 취약점을 파악하고, 주요 취약점에 대한 조치 상태를 업데이트하세요.',
    steps: [
      { title: 'Security Hub 활성화', desc: 'CIS Benchmark 표준을 포함해 Security Hub를 활성화하세요.',
        hint: 'aws securityhub enable-security-hub --enable-default-standards',
        answers: ['aws securityhub enable-security-hub --enable-default-standards', 'aws securityhub enable-security-hub'],
        successOutput: [''] },
      { title: 'Critical 취약점 조회', desc: '심각도 Critical 이상의 보안 결과를 조회하세요.',
        hint: 'aws securityhub get-findings --filters file://critical-filter.json --max-results 10',
        answers: ['aws securityhub get-findings --filters file://critical-filter.json --max-results 10', 'aws securityhub get-findings'],
        successOutput: ['{"Findings": [{"Title": "IAM root user access key should not exist", "Severity": {"Label": "CRITICAL"}, "Compliance": {"Status": "FAILED"}}, {"Title": "MFA should be enabled for the root user", "Severity": {"Label": "CRITICAL"}, "Compliance": {"Status": "FAILED"}}, {"Title": "CloudTrail should be enabled and configured", "Severity": {"Label": "HIGH"}, "Compliance": {"Status": "PASSED"}}]}'] },
      { title: '인사이트 요약 조회', desc: 'Security Hub 인사이트에서 취약한 리소스를 조회하세요.',
        hint: 'aws securityhub get-insights',
        answers: ['aws securityhub get-insights'],
        successOutput: ['{"Insights": [{"InsightArn": "arn:aws:securityhub:us-east-1:123456789012:insight/default/1", "Name": "Top accounts by count of critical severity findings", "ResultField": "AwsAccountId"}, {"InsightArn": "arn:aws:securityhub:us-east-1:123456789012:insight/default/2", "Name": "AWS resources with the most failed security checks", "ResultField": "ResourceId"}]}'] },
      { title: '취약점 조치 상태 업데이트', desc: '조치 완료된 취약점의 워크플로 상태를 RESOLVED로 업데이트하세요.',
        hint: 'aws securityhub batch-update-findings --finding-identifiers Id=arn:aws:securityhub:us-east-1:123456789012:finding/abc123,ProductArn=arn:aws:securityhub:us-east-1::product/aws/securityhub --workflow Status=RESOLVED',
        answers: ['aws securityhub batch-update-findings --finding-identifiers id=arn:aws:securityhub:us-east-1:123456789012:finding/abc123,productarn=arn:aws:securityhub:us-east-1::product/aws/securityhub --workflow status=resolved'],
        successOutput: ['{"ProcessedFindings": [{"Id": "arn:aws:securityhub:us-east-1:123456789012:finding/abc123", "ProductArn": "arn:aws:securityhub:us-east-1::product/aws/securityhub"}], "UnprocessedFindings": []}'] },
    ],
    explanation: 'AWS Security Hub는 GuardDuty, Inspector, Macie 등 여러 보안 서비스의 결과를 통합합니다. CIS AWS Foundations Benchmark·FSBP를 자동 점검하며, 보안 점수를 정기적으로 확인하고 RESOLVED로 업데이트해 추적 관리하는 것이 중요합니다.',
  },
"""

with open('src/web-app.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = '  11: {\n    id: \'SEC-11\''
end_marker = '  30: {\n    id: \'SEC-30\''

start = content.find(start_marker)
if start == -1:
    print('ERROR: start marker not found')
    exit(1)

# Find end of entry 30: find '  30: {' and then find the next '};' after that
end_pos = content.find(end_marker, start)
if end_pos == -1:
    print('ERROR: end marker not found')
    exit(1)

# Find closing of entry 30: look for the `  },\n` that closes it, then `};\n`
# The block ends at `};\n\nconst CHALLENGE_SCENARIOS`
close_marker = '};\n\nconst CHALLENGE_SCENARIOS'
close_pos = content.find(close_marker, end_pos)
if close_pos == -1:
    print('ERROR: close marker not found')
    exit(1)

# We want to replace from start_marker to close_pos (exclusive)
old_block = content[start:close_pos]
print(f'Replacing {len(old_block)} chars starting at position {start}')

new_content = content[:start] + NEW_BLOCK + content[close_pos:]

with open('src/web-app.tsx', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'Done. File size: {len(new_content)} chars')
